// Reviewed official public web 5.7.0+173855, modules 27369,15631,41918 and modulesBuilder.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: wire/auxiliary.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MiniAppBotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotUserId     uint32                 `protobuf:"varint,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppBotRequest) Reset() {
	*x = MiniAppBotRequest{}
	mi := &file_wire_auxiliary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppBotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppBotRequest) ProtoMessage() {}

func (x *MiniAppBotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppBotRequest.ProtoReflect.Descriptor instead.
func (*MiniAppBotRequest) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{0}
}

func (x *MiniAppBotRequest) GetBotUserId() uint32 {
	if x != nil {
		return x.BotUserId
	}
	return 0
}

type MiniAppMain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartParam    *StringValue           `protobuf:"bytes,1,opt,name=start_param,json=startParam,proto3" json:"start_param,omitempty"`
	Peer          *Peer                  `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppMain) Reset() {
	*x = MiniAppMain{}
	mi := &file_wire_auxiliary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppMain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppMain) ProtoMessage() {}

func (x *MiniAppMain) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppMain.ProtoReflect.Descriptor instead.
func (*MiniAppMain) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{1}
}

func (x *MiniAppMain) GetStartParam() *StringValue {
	if x != nil {
		return x.StartParam
	}
	return nil
}

func (x *MiniAppMain) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type MiniAppMenu struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *StringValue           `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppMenu) Reset() {
	*x = MiniAppMenu{}
	mi := &file_wire_auxiliary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppMenu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppMenu) ProtoMessage() {}

func (x *MiniAppMenu) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppMenu.ProtoReflect.Descriptor instead.
func (*MiniAppMenu) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{2}
}

func (x *MiniAppMenu) GetUrl() *StringValue {
	if x != nil {
		return x.Url
	}
	return nil
}

type MiniAppKeyboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppKeyboard) Reset() {
	*x = MiniAppKeyboard{}
	mi := &file_wire_auxiliary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppKeyboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppKeyboard) ProtoMessage() {}

func (x *MiniAppKeyboard) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppKeyboard.ProtoReflect.Descriptor instead.
func (*MiniAppKeyboard) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{3}
}

func (x *MiniAppKeyboard) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MiniAppDirect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortName     string                 `protobuf:"bytes,1,opt,name=short_name,json=shortName,proto3" json:"short_name,omitempty"`
	StartParam    *StringValue           `protobuf:"bytes,2,opt,name=start_param,json=startParam,proto3" json:"start_param,omitempty"`
	Peer          *Peer                  `protobuf:"bytes,3,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppDirect) Reset() {
	*x = MiniAppDirect{}
	mi := &file_wire_auxiliary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppDirect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppDirect) ProtoMessage() {}

func (x *MiniAppDirect) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppDirect.ProtoReflect.Descriptor instead.
func (*MiniAppDirect) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{4}
}

func (x *MiniAppDirect) GetShortName() string {
	if x != nil {
		return x.ShortName
	}
	return ""
}

func (x *MiniAppDirect) GetStartParam() *StringValue {
	if x != nil {
		return x.StartParam
	}
	return nil
}

func (x *MiniAppDirect) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type MiniAppTheme struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	BgColor                *StringValue           `protobuf:"bytes,1,opt,name=bg_color,json=bgColor,proto3" json:"bg_color,omitempty"`
	SecondaryBgColor       *StringValue           `protobuf:"bytes,2,opt,name=secondary_bg_color,json=secondaryBgColor,proto3" json:"secondary_bg_color,omitempty"`
	TextColor              *StringValue           `protobuf:"bytes,3,opt,name=text_color,json=textColor,proto3" json:"text_color,omitempty"`
	HintColor              *StringValue           `protobuf:"bytes,4,opt,name=hint_color,json=hintColor,proto3" json:"hint_color,omitempty"`
	LinkColor              *StringValue           `protobuf:"bytes,5,opt,name=link_color,json=linkColor,proto3" json:"link_color,omitempty"`
	ButtonColor            *StringValue           `protobuf:"bytes,6,opt,name=button_color,json=buttonColor,proto3" json:"button_color,omitempty"`
	ButtonTextColor        *StringValue           `protobuf:"bytes,7,opt,name=button_text_color,json=buttonTextColor,proto3" json:"button_text_color,omitempty"`
	HeaderBgColor          *StringValue           `protobuf:"bytes,8,opt,name=header_bg_color,json=headerBgColor,proto3" json:"header_bg_color,omitempty"`
	AccentTextColor        *StringValue           `protobuf:"bytes,9,opt,name=accent_text_color,json=accentTextColor,proto3" json:"accent_text_color,omitempty"`
	SectionBgColor         *StringValue           `protobuf:"bytes,10,opt,name=section_bg_color,json=sectionBgColor,proto3" json:"section_bg_color,omitempty"`
	SectionHeaderTextColor *StringValue           `protobuf:"bytes,11,opt,name=section_header_text_color,json=sectionHeaderTextColor,proto3" json:"section_header_text_color,omitempty"`
	SectionSeparatorColor  *StringValue           `protobuf:"bytes,12,opt,name=section_separator_color,json=sectionSeparatorColor,proto3" json:"section_separator_color,omitempty"`
	SubtitleTextColor      *StringValue           `protobuf:"bytes,13,opt,name=subtitle_text_color,json=subtitleTextColor,proto3" json:"subtitle_text_color,omitempty"`
	DestructiveTextColor   *StringValue           `protobuf:"bytes,14,opt,name=destructive_text_color,json=destructiveTextColor,proto3" json:"destructive_text_color,omitempty"`
	BottomBarBgColor       *StringValue           `protobuf:"bytes,15,opt,name=bottom_bar_bg_color,json=bottomBarBgColor,proto3" json:"bottom_bar_bg_color,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MiniAppTheme) Reset() {
	*x = MiniAppTheme{}
	mi := &file_wire_auxiliary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppTheme) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppTheme) ProtoMessage() {}

func (x *MiniAppTheme) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppTheme.ProtoReflect.Descriptor instead.
func (*MiniAppTheme) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{5}
}

func (x *MiniAppTheme) GetBgColor() *StringValue {
	if x != nil {
		return x.BgColor
	}
	return nil
}

func (x *MiniAppTheme) GetSecondaryBgColor() *StringValue {
	if x != nil {
		return x.SecondaryBgColor
	}
	return nil
}

func (x *MiniAppTheme) GetTextColor() *StringValue {
	if x != nil {
		return x.TextColor
	}
	return nil
}

func (x *MiniAppTheme) GetHintColor() *StringValue {
	if x != nil {
		return x.HintColor
	}
	return nil
}

func (x *MiniAppTheme) GetLinkColor() *StringValue {
	if x != nil {
		return x.LinkColor
	}
	return nil
}

func (x *MiniAppTheme) GetButtonColor() *StringValue {
	if x != nil {
		return x.ButtonColor
	}
	return nil
}

func (x *MiniAppTheme) GetButtonTextColor() *StringValue {
	if x != nil {
		return x.ButtonTextColor
	}
	return nil
}

func (x *MiniAppTheme) GetHeaderBgColor() *StringValue {
	if x != nil {
		return x.HeaderBgColor
	}
	return nil
}

func (x *MiniAppTheme) GetAccentTextColor() *StringValue {
	if x != nil {
		return x.AccentTextColor
	}
	return nil
}

func (x *MiniAppTheme) GetSectionBgColor() *StringValue {
	if x != nil {
		return x.SectionBgColor
	}
	return nil
}

func (x *MiniAppTheme) GetSectionHeaderTextColor() *StringValue {
	if x != nil {
		return x.SectionHeaderTextColor
	}
	return nil
}

func (x *MiniAppTheme) GetSectionSeparatorColor() *StringValue {
	if x != nil {
		return x.SectionSeparatorColor
	}
	return nil
}

func (x *MiniAppTheme) GetSubtitleTextColor() *StringValue {
	if x != nil {
		return x.SubtitleTextColor
	}
	return nil
}

func (x *MiniAppTheme) GetDestructiveTextColor() *StringValue {
	if x != nil {
		return x.DestructiveTextColor
	}
	return nil
}

func (x *MiniAppTheme) GetBottomBarBgColor() *StringValue {
	if x != nil {
		return x.BottomBarBgColor
	}
	return nil
}

type MiniAppURLRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BotUserId      uint32                 `protobuf:"varint,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	ScreenMode     int32                  `protobuf:"varint,2,opt,name=screen_mode,json=screenMode,proto3" json:"screen_mode,omitempty"`
	Theme          *MiniAppTheme          `protobuf:"bytes,3,opt,name=theme,proto3" json:"theme,omitempty"`
	Main           *MiniAppMain           `protobuf:"bytes,4,opt,name=main,proto3" json:"main,omitempty"`
	MenuButton     *MiniAppMenu           `protobuf:"bytes,5,opt,name=menu_button,json=menuButton,proto3" json:"menu_button,omitempty"`
	KeyboardButton *MiniAppKeyboard       `protobuf:"bytes,6,opt,name=keyboard_button,json=keyboardButton,proto3" json:"keyboard_button,omitempty"`
	DirectLink     *MiniAppDirect         `protobuf:"bytes,7,opt,name=direct_link,json=directLink,proto3" json:"direct_link,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MiniAppURLRequest) Reset() {
	*x = MiniAppURLRequest{}
	mi := &file_wire_auxiliary_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppURLRequest) ProtoMessage() {}

func (x *MiniAppURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppURLRequest.ProtoReflect.Descriptor instead.
func (*MiniAppURLRequest) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{6}
}

func (x *MiniAppURLRequest) GetBotUserId() uint32 {
	if x != nil {
		return x.BotUserId
	}
	return 0
}

func (x *MiniAppURLRequest) GetScreenMode() int32 {
	if x != nil {
		return x.ScreenMode
	}
	return 0
}

func (x *MiniAppURLRequest) GetTheme() *MiniAppTheme {
	if x != nil {
		return x.Theme
	}
	return nil
}

func (x *MiniAppURLRequest) GetMain() *MiniAppMain {
	if x != nil {
		return x.Main
	}
	return nil
}

func (x *MiniAppURLRequest) GetMenuButton() *MiniAppMenu {
	if x != nil {
		return x.MenuButton
	}
	return nil
}

func (x *MiniAppURLRequest) GetKeyboardButton() *MiniAppKeyboard {
	if x != nil {
		return x.KeyboardButton
	}
	return nil
}

func (x *MiniAppURLRequest) GetDirectLink() *MiniAppDirect {
	if x != nil {
		return x.DirectLink
	}
	return nil
}

type MiniAppURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ScreenMode    int32                  `protobuf:"varint,2,opt,name=screen_mode,json=screenMode,proto3" json:"screen_mode,omitempty"`
	QueryId       *StringValue           `protobuf:"bytes,3,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppURLResponse) Reset() {
	*x = MiniAppURLResponse{}
	mi := &file_wire_auxiliary_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppURLResponse) ProtoMessage() {}

func (x *MiniAppURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppURLResponse.ProtoReflect.Descriptor instead.
func (*MiniAppURLResponse) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{7}
}

func (x *MiniAppURLResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MiniAppURLResponse) GetScreenMode() int32 {
	if x != nil {
		return x.ScreenMode
	}
	return 0
}

func (x *MiniAppURLResponse) GetQueryId() *StringValue {
	if x != nil {
		return x.QueryId
	}
	return nil
}

type MiniAppHashRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotUserId     uint32                 `protobuf:"varint,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppHashRequest) Reset() {
	*x = MiniAppHashRequest{}
	mi := &file_wire_auxiliary_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppHashRequest) ProtoMessage() {}

func (x *MiniAppHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppHashRequest.ProtoReflect.Descriptor instead.
func (*MiniAppHashRequest) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{8}
}

func (x *MiniAppHashRequest) GetBotUserId() uint32 {
	if x != nil {
		return x.BotUserId
	}
	return 0
}

func (x *MiniAppHashRequest) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type MiniAppHashResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	QueryId       string                 `protobuf:"bytes,2,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	AuthDate      int64                  `protobuf:"varint,3,opt,name=auth_date,json=authDate,proto3" json:"auth_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppHashResponse) Reset() {
	*x = MiniAppHashResponse{}
	mi := &file_wire_auxiliary_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppHashResponse) ProtoMessage() {}

func (x *MiniAppHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppHashResponse.ProtoReflect.Descriptor instead.
func (*MiniAppHashResponse) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{9}
}

func (x *MiniAppHashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *MiniAppHashResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *MiniAppHashResponse) GetAuthDate() int64 {
	if x != nil {
		return x.AuthDate
	}
	return 0
}

type MiniAppDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotUserId     uint32                 `protobuf:"varint,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	QueryId       *StringValue           `protobuf:"bytes,2,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Data          *StringValue           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	ButtonText    *StringValue           `protobuf:"bytes,4,opt,name=button_text,json=buttonText,proto3" json:"button_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppDataRequest) Reset() {
	*x = MiniAppDataRequest{}
	mi := &file_wire_auxiliary_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppDataRequest) ProtoMessage() {}

func (x *MiniAppDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppDataRequest.ProtoReflect.Descriptor instead.
func (*MiniAppDataRequest) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{10}
}

func (x *MiniAppDataRequest) GetBotUserId() uint32 {
	if x != nil {
		return x.BotUserId
	}
	return 0
}

func (x *MiniAppDataRequest) GetQueryId() *StringValue {
	if x != nil {
		return x.QueryId
	}
	return nil
}

func (x *MiniAppDataRequest) GetData() *StringValue {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MiniAppDataRequest) GetButtonText() *StringValue {
	if x != nil {
		return x.ButtonText
	}
	return nil
}

type MiniAppMenuEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppMenuEntry) Reset() {
	*x = MiniAppMenuEntry{}
	mi := &file_wire_auxiliary_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppMenuEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppMenuEntry) ProtoMessage() {}

func (x *MiniAppMenuEntry) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppMenuEntry.ProtoReflect.Descriptor instead.
func (*MiniAppMenuEntry) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{11}
}

func (x *MiniAppMenuEntry) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MiniAppMenuEntry) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MiniAppMenuButton struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      *Empty                 `protobuf:"bytes,1,opt,name=commands,proto3" json:"commands,omitempty"`
	MiniApp       *MiniAppMenuEntry      `protobuf:"bytes,2,opt,name=mini_app,json=miniApp,proto3" json:"mini_app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppMenuButton) Reset() {
	*x = MiniAppMenuButton{}
	mi := &file_wire_auxiliary_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppMenuButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppMenuButton) ProtoMessage() {}

func (x *MiniAppMenuButton) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppMenuButton.ProtoReflect.Descriptor instead.
func (*MiniAppMenuButton) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{12}
}

func (x *MiniAppMenuButton) GetCommands() *Empty {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *MiniAppMenuButton) GetMiniApp() *MiniAppMenuEntry {
	if x != nil {
		return x.MiniApp
	}
	return nil
}

type MiniAppMenuResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuButton    *MiniAppMenuButton     `protobuf:"bytes,1,opt,name=menu_button,json=menuButton,proto3" json:"menu_button,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppMenuResponse) Reset() {
	*x = MiniAppMenuResponse{}
	mi := &file_wire_auxiliary_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppMenuResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppMenuResponse) ProtoMessage() {}

func (x *MiniAppMenuResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppMenuResponse.ProtoReflect.Descriptor instead.
func (*MiniAppMenuResponse) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{13}
}

func (x *MiniAppMenuResponse) GetMenuButton() *MiniAppMenuButton {
	if x != nil {
		return x.MenuButton
	}
	return nil
}

type MiniAppCustomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BotUserId     uint32                 `protobuf:"varint,1,opt,name=bot_user_id,json=botUserId,proto3" json:"bot_user_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Params        string                 `protobuf:"bytes,3,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppCustomRequest) Reset() {
	*x = MiniAppCustomRequest{}
	mi := &file_wire_auxiliary_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppCustomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppCustomRequest) ProtoMessage() {}

func (x *MiniAppCustomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppCustomRequest.ProtoReflect.Descriptor instead.
func (*MiniAppCustomRequest) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{14}
}

func (x *MiniAppCustomRequest) GetBotUserId() uint32 {
	if x != nil {
		return x.BotUserId
	}
	return 0
}

func (x *MiniAppCustomRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MiniAppCustomRequest) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

type MiniAppCustomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppCustomResponse) Reset() {
	*x = MiniAppCustomResponse{}
	mi := &file_wire_auxiliary_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppCustomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppCustomResponse) ProtoMessage() {}

func (x *MiniAppCustomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppCustomResponse.ProtoReflect.Descriptor instead.
func (*MiniAppCustomResponse) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{15}
}

func (x *MiniAppCustomResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type MiniAppCallbackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *Peer                  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	MessageId     *MessagePosition       `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Data          *StringValue           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiniAppCallbackRequest) Reset() {
	*x = MiniAppCallbackRequest{}
	mi := &file_wire_auxiliary_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiniAppCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiniAppCallbackRequest) ProtoMessage() {}

func (x *MiniAppCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiniAppCallbackRequest.ProtoReflect.Descriptor instead.
func (*MiniAppCallbackRequest) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{16}
}

func (x *MiniAppCallbackRequest) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *MiniAppCallbackRequest) GetMessageId() *MessagePosition {
	if x != nil {
		return x.MessageId
	}
	return nil
}

func (x *MiniAppCallbackRequest) GetData() *StringValue {
	if x != nil {
		return x.Data
	}
	return nil
}

type LinkSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkSummaryRequest) Reset() {
	*x = LinkSummaryRequest{}
	mi := &file_wire_auxiliary_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkSummaryRequest) ProtoMessage() {}

func (x *LinkSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkSummaryRequest.ProtoReflect.Descriptor instead.
func (*LinkSummaryRequest) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{17}
}

func (x *LinkSummaryRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LinkSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       string                 `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkSummaryResponse) Reset() {
	*x = LinkSummaryResponse{}
	mi := &file_wire_auxiliary_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkSummaryResponse) ProtoMessage() {}

func (x *LinkSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkSummaryResponse.ProtoReflect.Descriptor instead.
func (*LinkSummaryResponse) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{18}
}

func (x *LinkSummaryResponse) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

// Story IDs are opaque strings; do not coerce them to numeric identifiers.
type StoryIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryIDRequest) Reset() {
	*x = StoryIDRequest{}
	mi := &file_wire_auxiliary_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryIDRequest) ProtoMessage() {}

func (x *StoryIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryIDRequest.ProtoReflect.Descriptor instead.
func (*StoryIDRequest) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{19}
}

func (x *StoryIDRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

type StoryText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryText) Reset() {
	*x = StoryText{}
	mi := &file_wire_auxiliary_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryText) ProtoMessage() {}

func (x *StoryText) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryText.ProtoReflect.Descriptor instead.
func (*StoryText) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{20}
}

func (x *StoryText) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type StoryMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileLocation  *FileLocation          `protobuf:"bytes,1,opt,name=file_location,json=fileLocation,proto3" json:"file_location,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Video         *StoryVideo            `protobuf:"bytes,4,opt,name=video,proto3" json:"video,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryMedia) Reset() {
	*x = StoryMedia{}
	mi := &file_wire_auxiliary_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryMedia) ProtoMessage() {}

func (x *StoryMedia) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryMedia.ProtoReflect.Descriptor instead.
func (*StoryMedia) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{21}
}

func (x *StoryMedia) GetFileLocation() *FileLocation {
	if x != nil {
		return x.FileLocation
	}
	return nil
}

func (x *StoryMedia) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *StoryMedia) GetVideo() *StoryVideo {
	if x != nil {
		return x.Video
	}
	return nil
}

type StoryVideo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileLocation  *FileLocation          `protobuf:"bytes,1,opt,name=file_location,json=fileLocation,proto3" json:"file_location,omitempty"`
	FileSize      int64                  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	Duration      float32                `protobuf:"fixed32,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Format        string                 `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryVideo) Reset() {
	*x = StoryVideo{}
	mi := &file_wire_auxiliary_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryVideo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryVideo) ProtoMessage() {}

func (x *StoryVideo) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryVideo.ProtoReflect.Descriptor instead.
func (*StoryVideo) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{22}
}

func (x *StoryVideo) GetFileLocation() *FileLocation {
	if x != nil {
		return x.FileLocation
	}
	return nil
}

func (x *StoryVideo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *StoryVideo) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *StoryVideo) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type StoryContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *StoryMedia            `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Text          *StoryText             `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryContent) Reset() {
	*x = StoryContent{}
	mi := &file_wire_auxiliary_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryContent) ProtoMessage() {}

func (x *StoryContent) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryContent.ProtoReflect.Descriptor instead.
func (*StoryContent) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{23}
}

func (x *StoryContent) GetMedia() *StoryMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *StoryContent) GetText() *StoryText {
	if x != nil {
		return x.Text
	}
	return nil
}

type StoryReaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Text          *StringValue           `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryReaction) Reset() {
	*x = StoryReaction{}
	mi := &file_wire_auxiliary_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryReaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryReaction) ProtoMessage() {}

func (x *StoryReaction) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryReaction.ProtoReflect.Descriptor instead.
func (*StoryReaction) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{24}
}

func (x *StoryReaction) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *StoryReaction) GetText() *StringValue {
	if x != nil {
		return x.Text
	}
	return nil
}

type StoryRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerUserId   uint32                 `protobuf:"varint,2,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Reaction      *StringValue           `protobuf:"bytes,3,opt,name=reaction,proto3" json:"reaction,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Content       *StoryContent          `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	HasWidget     bool                   `protobuf:"varint,6,opt,name=has_widget,json=hasWidget,proto3" json:"has_widget,omitempty"`
	HasReply      bool                   `protobuf:"varint,7,opt,name=has_reply,json=hasReply,proto3" json:"has_reply,omitempty"`
	IsHidden      bool                   `protobuf:"varint,8,opt,name=is_hidden,json=isHidden,proto3" json:"is_hidden,omitempty"`
	IsMutual      bool                   `protobuf:"varint,9,opt,name=is_mutual,json=isMutual,proto3" json:"is_mutual,omitempty"`
	TagIds        []int32                `protobuf:"varint,10,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	ContentType   int32                  `protobuf:"varint,11,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Reactions     []*StoryReaction       `protobuf:"bytes,12,rep,name=reactions,proto3" json:"reactions,omitempty"`
	ExceptionType int32                  `protobuf:"varint,13,opt,name=exception_type,json=exceptionType,proto3" json:"exception_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryRecord) Reset() {
	*x = StoryRecord{}
	mi := &file_wire_auxiliary_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryRecord) ProtoMessage() {}

func (x *StoryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryRecord.ProtoReflect.Descriptor instead.
func (*StoryRecord) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{25}
}

func (x *StoryRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StoryRecord) GetOwnerUserId() uint32 {
	if x != nil {
		return x.OwnerUserId
	}
	return 0
}

func (x *StoryRecord) GetReaction() *StringValue {
	if x != nil {
		return x.Reaction
	}
	return nil
}

func (x *StoryRecord) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *StoryRecord) GetContent() *StoryContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *StoryRecord) GetHasWidget() bool {
	if x != nil {
		return x.HasWidget
	}
	return false
}

func (x *StoryRecord) GetHasReply() bool {
	if x != nil {
		return x.HasReply
	}
	return false
}

func (x *StoryRecord) GetIsHidden() bool {
	if x != nil {
		return x.IsHidden
	}
	return false
}

func (x *StoryRecord) GetIsMutual() bool {
	if x != nil {
		return x.IsMutual
	}
	return false
}

func (x *StoryRecord) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *StoryRecord) GetContentType() int32 {
	if x != nil {
		return x.ContentType
	}
	return 0
}

func (x *StoryRecord) GetReactions() []*StoryReaction {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *StoryRecord) GetExceptionType() int32 {
	if x != nil {
		return x.ExceptionType
	}
	return 0
}

type StoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GetUnmutual   *BoolValue             `protobuf:"bytes,1,opt,name=get_unmutual,json=getUnmutual,proto3" json:"get_unmutual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryListRequest) Reset() {
	*x = StoryListRequest{}
	mi := &file_wire_auxiliary_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryListRequest) ProtoMessage() {}

func (x *StoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryListRequest.ProtoReflect.Descriptor instead.
func (*StoryListRequest) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{26}
}

func (x *StoryListRequest) GetGetUnmutual() *BoolValue {
	if x != nil {
		return x.GetUnmutual
	}
	return nil
}

type StoryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []*StoryRecord         `protobuf:"bytes,1,rep,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryListResponse) Reset() {
	*x = StoryListResponse{}
	mi := &file_wire_auxiliary_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryListResponse) ProtoMessage() {}

func (x *StoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryListResponse.ProtoReflect.Descriptor instead.
func (*StoryListResponse) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{27}
}

func (x *StoryListResponse) GetResult() []*StoryRecord {
	if x != nil {
		return x.Result
	}
	return nil
}

type StorySingleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Story         *StoryRecord           `protobuf:"bytes,1,opt,name=story,proto3" json:"story,omitempty"`
	ChannelStory  *Empty                 `protobuf:"bytes,2,opt,name=channel_story,json=channelStory,proto3" json:"channel_story,omitempty"`
	BotStory      *Empty                 `protobuf:"bytes,3,opt,name=bot_story,json=botStory,proto3" json:"bot_story,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorySingleResponse) Reset() {
	*x = StorySingleResponse{}
	mi := &file_wire_auxiliary_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorySingleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorySingleResponse) ProtoMessage() {}

func (x *StorySingleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorySingleResponse.ProtoReflect.Descriptor instead.
func (*StorySingleResponse) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{28}
}

func (x *StorySingleResponse) GetStory() *StoryRecord {
	if x != nil {
		return x.Story
	}
	return nil
}

func (x *StorySingleResponse) GetChannelStory() *Empty {
	if x != nil {
		return x.ChannelStory
	}
	return nil
}

func (x *StorySingleResponse) GetBotStory() *Empty {
	if x != nil {
		return x.BotStory
	}
	return nil
}

type StoryPagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryPagination) Reset() {
	*x = StoryPagination{}
	mi := &file_wire_auxiliary_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryPagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryPagination) ProtoMessage() {}

func (x *StoryPagination) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryPagination.ProtoReflect.Descriptor instead.
func (*StoryPagination) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{29}
}

func (x *StoryPagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *StoryPagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type StoryViewersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	Pagination    *StoryPagination       `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryViewersRequest) Reset() {
	*x = StoryViewersRequest{}
	mi := &file_wire_auxiliary_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryViewersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryViewersRequest) ProtoMessage() {}

func (x *StoryViewersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryViewersRequest.ProtoReflect.Descriptor instead.
func (*StoryViewersRequest) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{30}
}

func (x *StoryViewersRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *StoryViewersRequest) GetPagination() *StoryPagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type StoryViewer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reaction      string                 `protobuf:"bytes,1,opt,name=reaction,proto3" json:"reaction,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ReactedAt     int64                  `protobuf:"varint,3,opt,name=reacted_at,json=reactedAt,proto3" json:"reacted_at,omitempty"`
	ReactionData  []*StoryReaction       `protobuf:"bytes,4,rep,name=reaction_data,json=reactionData,proto3" json:"reaction_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryViewer) Reset() {
	*x = StoryViewer{}
	mi := &file_wire_auxiliary_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryViewer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryViewer) ProtoMessage() {}

func (x *StoryViewer) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryViewer.ProtoReflect.Descriptor instead.
func (*StoryViewer) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{31}
}

func (x *StoryViewer) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

func (x *StoryViewer) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *StoryViewer) GetReactedAt() int64 {
	if x != nil {
		return x.ReactedAt
	}
	return 0
}

func (x *StoryViewer) GetReactionData() []*StoryReaction {
	if x != nil {
		return x.ReactionData
	}
	return nil
}

type StoryViewersResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Viewers        []*StoryViewer         `protobuf:"bytes,1,rep,name=viewers,proto3" json:"viewers,omitempty"`
	ViewCount      int32                  `protobuf:"varint,2,opt,name=view_count,json=viewCount,proto3" json:"view_count,omitempty"`
	LikeCount      int32                  `protobuf:"varint,3,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	LinkClickCount int32                  `protobuf:"varint,4,opt,name=link_click_count,json=linkClickCount,proto3" json:"link_click_count,omitempty"`
	EmojiCount     int32                  `protobuf:"varint,5,opt,name=emoji_count,json=emojiCount,proto3" json:"emoji_count,omitempty"`
	RestoryCount   int32                  `protobuf:"varint,6,opt,name=restory_count,json=restoryCount,proto3" json:"restory_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoryViewersResponse) Reset() {
	*x = StoryViewersResponse{}
	mi := &file_wire_auxiliary_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryViewersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryViewersResponse) ProtoMessage() {}

func (x *StoryViewersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryViewersResponse.ProtoReflect.Descriptor instead.
func (*StoryViewersResponse) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{32}
}

func (x *StoryViewersResponse) GetViewers() []*StoryViewer {
	if x != nil {
		return x.Viewers
	}
	return nil
}

func (x *StoryViewersResponse) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *StoryViewersResponse) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *StoryViewersResponse) GetLinkClickCount() int32 {
	if x != nil {
		return x.LinkClickCount
	}
	return 0
}

func (x *StoryViewersResponse) GetEmojiCount() int32 {
	if x != nil {
		return x.EmojiCount
	}
	return 0
}

func (x *StoryViewersResponse) GetRestoryCount() int32 {
	if x != nil {
		return x.RestoryCount
	}
	return 0
}

type StoryReactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	Reaction      string                 `protobuf:"bytes,2,opt,name=reaction,proto3" json:"reaction,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	ReactionType  int32                  `protobuf:"varint,4,opt,name=reaction_type,json=reactionType,proto3" json:"reaction_type,omitempty"`
	ReactionText  *StringValue           `protobuf:"bytes,5,opt,name=reaction_text,json=reactionText,proto3" json:"reaction_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryReactRequest) Reset() {
	*x = StoryReactRequest{}
	mi := &file_wire_auxiliary_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryReactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryReactRequest) ProtoMessage() {}

func (x *StoryReactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryReactRequest.ProtoReflect.Descriptor instead.
func (*StoryReactRequest) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{33}
}

func (x *StoryReactRequest) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

func (x *StoryReactRequest) GetReaction() string {
	if x != nil {
		return x.Reaction
	}
	return ""
}

func (x *StoryReactRequest) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *StoryReactRequest) GetReactionType() int32 {
	if x != nil {
		return x.ReactionType
	}
	return 0
}

func (x *StoryReactRequest) GetReactionText() *StringValue {
	if x != nil {
		return x.ReactionText
	}
	return nil
}

type StoryAddRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Media          *StoryMedia            `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Text           *StoryText             `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	TagIds         []int32                `protobuf:"varint,10,rep,packed,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	ExpirationType int32                  `protobuf:"varint,11,opt,name=expiration_type,json=expirationType,proto3" json:"expiration_type,omitempty"`
	ExceptionType  int32                  `protobuf:"varint,12,opt,name=exception_type,json=exceptionType,proto3" json:"exception_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StoryAddRequest) Reset() {
	*x = StoryAddRequest{}
	mi := &file_wire_auxiliary_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryAddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryAddRequest) ProtoMessage() {}

func (x *StoryAddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryAddRequest.ProtoReflect.Descriptor instead.
func (*StoryAddRequest) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{34}
}

func (x *StoryAddRequest) GetMedia() *StoryMedia {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *StoryAddRequest) GetText() *StoryText {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *StoryAddRequest) GetTagIds() []int32 {
	if x != nil {
		return x.TagIds
	}
	return nil
}

func (x *StoryAddRequest) GetExpirationType() int32 {
	if x != nil {
		return x.ExpirationType
	}
	return 0
}

func (x *StoryAddRequest) GetExceptionType() int32 {
	if x != nil {
		return x.ExceptionType
	}
	return 0
}

type StoryAddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoryId       string                 `protobuf:"bytes,1,opt,name=story_id,json=storyId,proto3" json:"story_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoryAddResponse) Reset() {
	*x = StoryAddResponse{}
	mi := &file_wire_auxiliary_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoryAddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoryAddResponse) ProtoMessage() {}

func (x *StoryAddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_auxiliary_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoryAddResponse.ProtoReflect.Descriptor instead.
func (*StoryAddResponse) Descriptor() ([]byte, []int) {
	return file_wire_auxiliary_proto_rawDescGZIP(), []int{35}
}

func (x *StoryAddResponse) GetStoryId() string {
	if x != nil {
		return x.StoryId
	}
	return ""
}

var File_wire_auxiliary_proto protoreflect.FileDescriptor

const file_wire_auxiliary_proto_rawDesc = "" +
	"\n" +
	"\x14wire/auxiliary.proto\x12\x15gobale.bale.reference\x1a\x0fwire/bale.proto\"3\n" +
	"\x11MiniAppBotRequest\x12\x1e\n" +
	"\vbot_user_id\x18\x01 \x01(\rR\tbotUserId\"\x83\x01\n" +
	"\vMiniAppMain\x12C\n" +
	"\vstart_param\x18\x01 \x01(\v2\".gobale.bale.reference.StringValueR\n" +
	"startParam\x12/\n" +
	"\x04peer\x18\x02 \x01(\v2\x1b.gobale.bale.reference.PeerR\x04peer\"C\n" +
	"\vMiniAppMenu\x124\n" +
	"\x03url\x18\x01 \x01(\v2\".gobale.bale.reference.StringValueR\x03url\"#\n" +
	"\x0fMiniAppKeyboard\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\xa4\x01\n" +
	"\rMiniAppDirect\x12\x1d\n" +
	"\n" +
	"short_name\x18\x01 \x01(\tR\tshortName\x12C\n" +
	"\vstart_param\x18\x02 \x01(\v2\".gobale.bale.reference.StringValueR\n" +
	"startParam\x12/\n" +
	"\x04peer\x18\x03 \x01(\v2\x1b.gobale.bale.reference.PeerR\x04peer\"\xa5\t\n" +
	"\fMiniAppTheme\x12=\n" +
	"\bbg_color\x18\x01 \x01(\v2\".gobale.bale.reference.StringValueR\abgColor\x12P\n" +
	"\x12secondary_bg_color\x18\x02 \x01(\v2\".gobale.bale.reference.StringValueR\x10secondaryBgColor\x12A\n" +
	"\n" +
	"text_color\x18\x03 \x01(\v2\".gobale.bale.reference.StringValueR\ttextColor\x12A\n" +
	"\n" +
	"hint_color\x18\x04 \x01(\v2\".gobale.bale.reference.StringValueR\thintColor\x12A\n" +
	"\n" +
	"link_color\x18\x05 \x01(\v2\".gobale.bale.reference.StringValueR\tlinkColor\x12E\n" +
	"\fbutton_color\x18\x06 \x01(\v2\".gobale.bale.reference.StringValueR\vbuttonColor\x12N\n" +
	"\x11button_text_color\x18\a \x01(\v2\".gobale.bale.reference.StringValueR\x0fbuttonTextColor\x12J\n" +
	"\x0fheader_bg_color\x18\b \x01(\v2\".gobale.bale.reference.StringValueR\rheaderBgColor\x12N\n" +
	"\x11accent_text_color\x18\t \x01(\v2\".gobale.bale.reference.StringValueR\x0faccentTextColor\x12L\n" +
	"\x10section_bg_color\x18\n" +
	" \x01(\v2\".gobale.bale.reference.StringValueR\x0esectionBgColor\x12]\n" +
	"\x19section_header_text_color\x18\v \x01(\v2\".gobale.bale.reference.StringValueR\x16sectionHeaderTextColor\x12Z\n" +
	"\x17section_separator_color\x18\f \x01(\v2\".gobale.bale.reference.StringValueR\x15sectionSeparatorColor\x12R\n" +
	"\x13subtitle_text_color\x18\r \x01(\v2\".gobale.bale.reference.StringValueR\x11subtitleTextColor\x12X\n" +
	"\x16destructive_text_color\x18\x0e \x01(\v2\".gobale.bale.reference.StringValueR\x14destructiveTextColor\x12Q\n" +
	"\x13bottom_bar_bg_color\x18\x0f \x01(\v2\".gobale.bale.reference.StringValueR\x10bottomBarBgColor\"\xa4\x03\n" +
	"\x11MiniAppURLRequest\x12\x1e\n" +
	"\vbot_user_id\x18\x01 \x01(\rR\tbotUserId\x12\x1f\n" +
	"\vscreen_mode\x18\x02 \x01(\x05R\n" +
	"screenMode\x129\n" +
	"\x05theme\x18\x03 \x01(\v2#.gobale.bale.reference.MiniAppThemeR\x05theme\x126\n" +
	"\x04main\x18\x04 \x01(\v2\".gobale.bale.reference.MiniAppMainR\x04main\x12C\n" +
	"\vmenu_button\x18\x05 \x01(\v2\".gobale.bale.reference.MiniAppMenuR\n" +
	"menuButton\x12O\n" +
	"\x0fkeyboard_button\x18\x06 \x01(\v2&.gobale.bale.reference.MiniAppKeyboardR\x0ekeyboardButton\x12E\n" +
	"\vdirect_link\x18\a \x01(\v2$.gobale.bale.reference.MiniAppDirectR\n" +
	"directLink\"\x86\x01\n" +
	"\x12MiniAppURLResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1f\n" +
	"\vscreen_mode\x18\x02 \x01(\x05R\n" +
	"screenMode\x12=\n" +
	"\bquery_id\x18\x03 \x01(\v2\".gobale.bale.reference.StringValueR\aqueryId\"H\n" +
	"\x12MiniAppHashRequest\x12\x1e\n" +
	"\vbot_user_id\x18\x01 \x01(\rR\tbotUserId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"a\n" +
	"\x13MiniAppHashResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\x12\x19\n" +
	"\bquery_id\x18\x02 \x01(\tR\aqueryId\x12\x1b\n" +
	"\tauth_date\x18\x03 \x01(\x03R\bauthDate\"\xf0\x01\n" +
	"\x12MiniAppDataRequest\x12\x1e\n" +
	"\vbot_user_id\x18\x01 \x01(\rR\tbotUserId\x12=\n" +
	"\bquery_id\x18\x02 \x01(\v2\".gobale.bale.reference.StringValueR\aqueryId\x126\n" +
	"\x04data\x18\x03 \x01(\v2\".gobale.bale.reference.StringValueR\x04data\x12C\n" +
	"\vbutton_text\x18\x04 \x01(\v2\".gobale.bale.reference.StringValueR\n" +
	"buttonText\"8\n" +
	"\x10MiniAppMenuEntry\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"\x91\x01\n" +
	"\x11MiniAppMenuButton\x128\n" +
	"\bcommands\x18\x01 \x01(\v2\x1c.gobale.bale.reference.EmptyR\bcommands\x12B\n" +
	"\bmini_app\x18\x02 \x01(\v2'.gobale.bale.reference.MiniAppMenuEntryR\aminiApp\"`\n" +
	"\x13MiniAppMenuResponse\x12I\n" +
	"\vmenu_button\x18\x01 \x01(\v2(.gobale.bale.reference.MiniAppMenuButtonR\n" +
	"menuButton\"f\n" +
	"\x14MiniAppCustomRequest\x12\x1e\n" +
	"\vbot_user_id\x18\x01 \x01(\rR\tbotUserId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x16\n" +
	"\x06params\x18\x03 \x01(\tR\x06params\"+\n" +
	"\x15MiniAppCustomResponse\x12\x12\n" +
	"\x04data\x18\x04 \x01(\tR\x04data\"\xc8\x01\n" +
	"\x16MiniAppCallbackRequest\x12/\n" +
	"\x04peer\x18\x01 \x01(\v2\x1b.gobale.bale.reference.PeerR\x04peer\x12E\n" +
	"\n" +
	"message_id\x18\x02 \x01(\v2&.gobale.bale.reference.MessagePositionR\tmessageId\x126\n" +
	"\x04data\x18\x03 \x01(\v2\".gobale.bale.reference.StringValueR\x04data\"&\n" +
	"\x12LinkSummaryRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"/\n" +
	"\x13LinkSummaryResponse\x12\x18\n" +
	"\asummary\x18\x01 \x01(\tR\asummary\"+\n" +
	"\x0eStoryIDRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\"\x1f\n" +
	"\tStoryText\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\xb2\x01\n" +
	"\n" +
	"StoryMedia\x12H\n" +
	"\rfile_location\x18\x01 \x01(\v2#.gobale.bale.reference.FileLocationR\ffileLocation\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x127\n" +
	"\x05video\x18\x04 \x01(\v2!.gobale.bale.reference.StoryVideoR\x05videoJ\x04\b\x02\x10\x03\"\xad\x01\n" +
	"\n" +
	"StoryVideo\x12H\n" +
	"\rfile_location\x18\x01 \x01(\v2#.gobale.bale.reference.FileLocationR\ffileLocation\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\x03R\bfileSize\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x02R\bduration\x12\x16\n" +
	"\x06format\x18\x05 \x01(\tR\x06formatJ\x04\b\x02\x10\x03\"}\n" +
	"\fStoryContent\x127\n" +
	"\x05media\x18\x01 \x01(\v2!.gobale.bale.reference.StoryMediaR\x05media\x124\n" +
	"\x04text\x18\x02 \x01(\v2 .gobale.bale.reference.StoryTextR\x04text\"[\n" +
	"\rStoryReaction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x126\n" +
	"\x04text\x18\x02 \x01(\v2\".gobale.bale.reference.StringValueR\x04text\"\xfc\x03\n" +
	"\vStoryRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\rowner_user_id\x18\x02 \x01(\rR\vownerUserId\x12>\n" +
	"\breaction\x18\x03 \x01(\v2\".gobale.bale.reference.StringValueR\breaction\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12=\n" +
	"\acontent\x18\x05 \x01(\v2#.gobale.bale.reference.StoryContentR\acontent\x12\x1d\n" +
	"\n" +
	"has_widget\x18\x06 \x01(\bR\thasWidget\x12\x1b\n" +
	"\thas_reply\x18\a \x01(\bR\bhasReply\x12\x1b\n" +
	"\tis_hidden\x18\b \x01(\bR\bisHidden\x12\x1b\n" +
	"\tis_mutual\x18\t \x01(\bR\bisMutual\x12\x17\n" +
	"\atag_ids\x18\n" +
	" \x03(\x05R\x06tagIds\x12!\n" +
	"\fcontent_type\x18\v \x01(\x05R\vcontentType\x12B\n" +
	"\treactions\x18\f \x03(\v2$.gobale.bale.reference.StoryReactionR\treactions\x12%\n" +
	"\x0eexception_type\x18\r \x01(\x05R\rexceptionType\"W\n" +
	"\x10StoryListRequest\x12C\n" +
	"\fget_unmutual\x18\x01 \x01(\v2 .gobale.bale.reference.BoolValueR\vgetUnmutual\"O\n" +
	"\x11StoryListResponse\x12:\n" +
	"\x06result\x18\x01 \x03(\v2\".gobale.bale.reference.StoryRecordR\x06result\"\xcd\x01\n" +
	"\x13StorySingleResponse\x128\n" +
	"\x05story\x18\x01 \x01(\v2\".gobale.bale.reference.StoryRecordR\x05story\x12A\n" +
	"\rchannel_story\x18\x02 \x01(\v2\x1c.gobale.bale.reference.EmptyR\fchannelStory\x129\n" +
	"\tbot_story\x18\x03 \x01(\v2\x1c.gobale.bale.reference.EmptyR\bbotStory\";\n" +
	"\x0fStoryPagination\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"x\n" +
	"\x13StoryViewersRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.gobale.bale.reference.StoryPaginationR\n" +
	"pagination\"\xac\x01\n" +
	"\vStoryViewer\x12\x1a\n" +
	"\breaction\x18\x01 \x01(\tR\breaction\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1d\n" +
	"\n" +
	"reacted_at\x18\x03 \x01(\x03R\treactedAt\x12I\n" +
	"\rreaction_data\x18\x04 \x03(\v2$.gobale.bale.reference.StoryReactionR\freactionData\"\x82\x02\n" +
	"\x14StoryViewersResponse\x12<\n" +
	"\aviewers\x18\x01 \x03(\v2\".gobale.bale.reference.StoryViewerR\aviewers\x12\x1d\n" +
	"\n" +
	"view_count\x18\x02 \x01(\x05R\tviewCount\x12\x1d\n" +
	"\n" +
	"like_count\x18\x03 \x01(\x05R\tlikeCount\x12(\n" +
	"\x10link_click_count\x18\x04 \x01(\x05R\x0elinkClickCount\x12\x1f\n" +
	"\vemoji_count\x18\x05 \x01(\x05R\n" +
	"emojiCount\x12#\n" +
	"\rrestory_count\x18\x06 \x01(\x05R\frestoryCount\"\xcc\x01\n" +
	"\x11StoryReactRequest\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryId\x12\x1a\n" +
	"\breaction\x18\x02 \x01(\tR\breaction\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12#\n" +
	"\rreaction_type\x18\x04 \x01(\x05R\freactionType\x12G\n" +
	"\rreaction_text\x18\x05 \x01(\v2\".gobale.bale.reference.StringValueR\freactionText\"\xe9\x01\n" +
	"\x0fStoryAddRequest\x127\n" +
	"\x05media\x18\x01 \x01(\v2!.gobale.bale.reference.StoryMediaR\x05media\x124\n" +
	"\x04text\x18\x02 \x01(\v2 .gobale.bale.reference.StoryTextR\x04text\x12\x17\n" +
	"\atag_ids\x18\n" +
	" \x03(\x05R\x06tagIds\x12'\n" +
	"\x0fexpiration_type\x18\v \x01(\x05R\x0eexpirationType\x12%\n" +
	"\x0eexception_type\x18\f \x01(\x05R\rexceptionType\"-\n" +
	"\x10StoryAddResponse\x12\x19\n" +
	"\bstory_id\x18\x01 \x01(\tR\astoryIdB8Z6github.com/mimalef70/goomni/src/internal/balemeow/wireb\x06proto3"

var (
	file_wire_auxiliary_proto_rawDescOnce sync.Once
	file_wire_auxiliary_proto_rawDescData []byte
)

func file_wire_auxiliary_proto_rawDescGZIP() []byte {
	file_wire_auxiliary_proto_rawDescOnce.Do(func() {
		file_wire_auxiliary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_auxiliary_proto_rawDesc), len(file_wire_auxiliary_proto_rawDesc)))
	})
	return file_wire_auxiliary_proto_rawDescData
}

var file_wire_auxiliary_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_wire_auxiliary_proto_goTypes = []any{
	(*MiniAppBotRequest)(nil),      // 0: gobale.bale.reference.MiniAppBotRequest
	(*MiniAppMain)(nil),            // 1: gobale.bale.reference.MiniAppMain
	(*MiniAppMenu)(nil),            // 2: gobale.bale.reference.MiniAppMenu
	(*MiniAppKeyboard)(nil),        // 3: gobale.bale.reference.MiniAppKeyboard
	(*MiniAppDirect)(nil),          // 4: gobale.bale.reference.MiniAppDirect
	(*MiniAppTheme)(nil),           // 5: gobale.bale.reference.MiniAppTheme
	(*MiniAppURLRequest)(nil),      // 6: gobale.bale.reference.MiniAppURLRequest
	(*MiniAppURLResponse)(nil),     // 7: gobale.bale.reference.MiniAppURLResponse
	(*MiniAppHashRequest)(nil),     // 8: gobale.bale.reference.MiniAppHashRequest
	(*MiniAppHashResponse)(nil),    // 9: gobale.bale.reference.MiniAppHashResponse
	(*MiniAppDataRequest)(nil),     // 10: gobale.bale.reference.MiniAppDataRequest
	(*MiniAppMenuEntry)(nil),       // 11: gobale.bale.reference.MiniAppMenuEntry
	(*MiniAppMenuButton)(nil),      // 12: gobale.bale.reference.MiniAppMenuButton
	(*MiniAppMenuResponse)(nil),    // 13: gobale.bale.reference.MiniAppMenuResponse
	(*MiniAppCustomRequest)(nil),   // 14: gobale.bale.reference.MiniAppCustomRequest
	(*MiniAppCustomResponse)(nil),  // 15: gobale.bale.reference.MiniAppCustomResponse
	(*MiniAppCallbackRequest)(nil), // 16: gobale.bale.reference.MiniAppCallbackRequest
	(*LinkSummaryRequest)(nil),     // 17: gobale.bale.reference.LinkSummaryRequest
	(*LinkSummaryResponse)(nil),    // 18: gobale.bale.reference.LinkSummaryResponse
	(*StoryIDRequest)(nil),         // 19: gobale.bale.reference.StoryIDRequest
	(*StoryText)(nil),              // 20: gobale.bale.reference.StoryText
	(*StoryMedia)(nil),             // 21: gobale.bale.reference.StoryMedia
	(*StoryVideo)(nil),             // 22: gobale.bale.reference.StoryVideo
	(*StoryContent)(nil),           // 23: gobale.bale.reference.StoryContent
	(*StoryReaction)(nil),          // 24: gobale.bale.reference.StoryReaction
	(*StoryRecord)(nil),            // 25: gobale.bale.reference.StoryRecord
	(*StoryListRequest)(nil),       // 26: gobale.bale.reference.StoryListRequest
	(*StoryListResponse)(nil),      // 27: gobale.bale.reference.StoryListResponse
	(*StorySingleResponse)(nil),    // 28: gobale.bale.reference.StorySingleResponse
	(*StoryPagination)(nil),        // 29: gobale.bale.reference.StoryPagination
	(*StoryViewersRequest)(nil),    // 30: gobale.bale.reference.StoryViewersRequest
	(*StoryViewer)(nil),            // 31: gobale.bale.reference.StoryViewer
	(*StoryViewersResponse)(nil),   // 32: gobale.bale.reference.StoryViewersResponse
	(*StoryReactRequest)(nil),      // 33: gobale.bale.reference.StoryReactRequest
	(*StoryAddRequest)(nil),        // 34: gobale.bale.reference.StoryAddRequest
	(*StoryAddResponse)(nil),       // 35: gobale.bale.reference.StoryAddResponse
	(*StringValue)(nil),            // 36: gobale.bale.reference.StringValue
	(*Peer)(nil),                   // 37: gobale.bale.reference.Peer
	(*Empty)(nil),                  // 38: gobale.bale.reference.Empty
	(*MessagePosition)(nil),        // 39: gobale.bale.reference.MessagePosition
	(*FileLocation)(nil),           // 40: gobale.bale.reference.FileLocation
	(*BoolValue)(nil),              // 41: gobale.bale.reference.BoolValue
}
var file_wire_auxiliary_proto_depIdxs = []int32{
	36, // 0: gobale.bale.reference.MiniAppMain.start_param:type_name -> gobale.bale.reference.StringValue
	37, // 1: gobale.bale.reference.MiniAppMain.peer:type_name -> gobale.bale.reference.Peer
	36, // 2: gobale.bale.reference.MiniAppMenu.url:type_name -> gobale.bale.reference.StringValue
	36, // 3: gobale.bale.reference.MiniAppDirect.start_param:type_name -> gobale.bale.reference.StringValue
	37, // 4: gobale.bale.reference.MiniAppDirect.peer:type_name -> gobale.bale.reference.Peer
	36, // 5: gobale.bale.reference.MiniAppTheme.bg_color:type_name -> gobale.bale.reference.StringValue
	36, // 6: gobale.bale.reference.MiniAppTheme.secondary_bg_color:type_name -> gobale.bale.reference.StringValue
	36, // 7: gobale.bale.reference.MiniAppTheme.text_color:type_name -> gobale.bale.reference.StringValue
	36, // 8: gobale.bale.reference.MiniAppTheme.hint_color:type_name -> gobale.bale.reference.StringValue
	36, // 9: gobale.bale.reference.MiniAppTheme.link_color:type_name -> gobale.bale.reference.StringValue
	36, // 10: gobale.bale.reference.MiniAppTheme.button_color:type_name -> gobale.bale.reference.StringValue
	36, // 11: gobale.bale.reference.MiniAppTheme.button_text_color:type_name -> gobale.bale.reference.StringValue
	36, // 12: gobale.bale.reference.MiniAppTheme.header_bg_color:type_name -> gobale.bale.reference.StringValue
	36, // 13: gobale.bale.reference.MiniAppTheme.accent_text_color:type_name -> gobale.bale.reference.StringValue
	36, // 14: gobale.bale.reference.MiniAppTheme.section_bg_color:type_name -> gobale.bale.reference.StringValue
	36, // 15: gobale.bale.reference.MiniAppTheme.section_header_text_color:type_name -> gobale.bale.reference.StringValue
	36, // 16: gobale.bale.reference.MiniAppTheme.section_separator_color:type_name -> gobale.bale.reference.StringValue
	36, // 17: gobale.bale.reference.MiniAppTheme.subtitle_text_color:type_name -> gobale.bale.reference.StringValue
	36, // 18: gobale.bale.reference.MiniAppTheme.destructive_text_color:type_name -> gobale.bale.reference.StringValue
	36, // 19: gobale.bale.reference.MiniAppTheme.bottom_bar_bg_color:type_name -> gobale.bale.reference.StringValue
	5,  // 20: gobale.bale.reference.MiniAppURLRequest.theme:type_name -> gobale.bale.reference.MiniAppTheme
	1,  // 21: gobale.bale.reference.MiniAppURLRequest.main:type_name -> gobale.bale.reference.MiniAppMain
	2,  // 22: gobale.bale.reference.MiniAppURLRequest.menu_button:type_name -> gobale.bale.reference.MiniAppMenu
	3,  // 23: gobale.bale.reference.MiniAppURLRequest.keyboard_button:type_name -> gobale.bale.reference.MiniAppKeyboard
	4,  // 24: gobale.bale.reference.MiniAppURLRequest.direct_link:type_name -> gobale.bale.reference.MiniAppDirect
	36, // 25: gobale.bale.reference.MiniAppURLResponse.query_id:type_name -> gobale.bale.reference.StringValue
	36, // 26: gobale.bale.reference.MiniAppDataRequest.query_id:type_name -> gobale.bale.reference.StringValue
	36, // 27: gobale.bale.reference.MiniAppDataRequest.data:type_name -> gobale.bale.reference.StringValue
	36, // 28: gobale.bale.reference.MiniAppDataRequest.button_text:type_name -> gobale.bale.reference.StringValue
	38, // 29: gobale.bale.reference.MiniAppMenuButton.commands:type_name -> gobale.bale.reference.Empty
	11, // 30: gobale.bale.reference.MiniAppMenuButton.mini_app:type_name -> gobale.bale.reference.MiniAppMenuEntry
	12, // 31: gobale.bale.reference.MiniAppMenuResponse.menu_button:type_name -> gobale.bale.reference.MiniAppMenuButton
	37, // 32: gobale.bale.reference.MiniAppCallbackRequest.peer:type_name -> gobale.bale.reference.Peer
	39, // 33: gobale.bale.reference.MiniAppCallbackRequest.message_id:type_name -> gobale.bale.reference.MessagePosition
	36, // 34: gobale.bale.reference.MiniAppCallbackRequest.data:type_name -> gobale.bale.reference.StringValue
	40, // 35: gobale.bale.reference.StoryMedia.file_location:type_name -> gobale.bale.reference.FileLocation
	22, // 36: gobale.bale.reference.StoryMedia.video:type_name -> gobale.bale.reference.StoryVideo
	40, // 37: gobale.bale.reference.StoryVideo.file_location:type_name -> gobale.bale.reference.FileLocation
	21, // 38: gobale.bale.reference.StoryContent.media:type_name -> gobale.bale.reference.StoryMedia
	20, // 39: gobale.bale.reference.StoryContent.text:type_name -> gobale.bale.reference.StoryText
	36, // 40: gobale.bale.reference.StoryReaction.text:type_name -> gobale.bale.reference.StringValue
	36, // 41: gobale.bale.reference.StoryRecord.reaction:type_name -> gobale.bale.reference.StringValue
	23, // 42: gobale.bale.reference.StoryRecord.content:type_name -> gobale.bale.reference.StoryContent
	24, // 43: gobale.bale.reference.StoryRecord.reactions:type_name -> gobale.bale.reference.StoryReaction
	41, // 44: gobale.bale.reference.StoryListRequest.get_unmutual:type_name -> gobale.bale.reference.BoolValue
	25, // 45: gobale.bale.reference.StoryListResponse.result:type_name -> gobale.bale.reference.StoryRecord
	25, // 46: gobale.bale.reference.StorySingleResponse.story:type_name -> gobale.bale.reference.StoryRecord
	38, // 47: gobale.bale.reference.StorySingleResponse.channel_story:type_name -> gobale.bale.reference.Empty
	38, // 48: gobale.bale.reference.StorySingleResponse.bot_story:type_name -> gobale.bale.reference.Empty
	29, // 49: gobale.bale.reference.StoryViewersRequest.pagination:type_name -> gobale.bale.reference.StoryPagination
	24, // 50: gobale.bale.reference.StoryViewer.reaction_data:type_name -> gobale.bale.reference.StoryReaction
	31, // 51: gobale.bale.reference.StoryViewersResponse.viewers:type_name -> gobale.bale.reference.StoryViewer
	36, // 52: gobale.bale.reference.StoryReactRequest.reaction_text:type_name -> gobale.bale.reference.StringValue
	21, // 53: gobale.bale.reference.StoryAddRequest.media:type_name -> gobale.bale.reference.StoryMedia
	20, // 54: gobale.bale.reference.StoryAddRequest.text:type_name -> gobale.bale.reference.StoryText
	55, // [55:55] is the sub-list for method output_type
	55, // [55:55] is the sub-list for method input_type
	55, // [55:55] is the sub-list for extension type_name
	55, // [55:55] is the sub-list for extension extendee
	0,  // [0:55] is the sub-list for field type_name
}

func init() { file_wire_auxiliary_proto_init() }
func file_wire_auxiliary_proto_init() {
	if File_wire_auxiliary_proto != nil {
		return
	}
	file_wire_bale_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_auxiliary_proto_rawDesc), len(file_wire_auxiliary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_auxiliary_proto_goTypes,
		DependencyIndexes: file_wire_auxiliary_proto_depIdxs,
		MessageInfos:      file_wire_auxiliary_proto_msgTypes,
	}.Build()
	File_wire_auxiliary_proto = out.File
	file_wire_auxiliary_proto_goTypes = nil
	file_wire_auxiliary_proto_depIdxs = nil
}
