// Current official web 5.7.0+173855, inspected 2026-10-06.
// GetFullUser returns FullUser at field1; its current avatar is field6.
// This deliberately projects only the fields required for avatar download.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: wire/avatar.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAvatarResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserAvatarProjection  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAvatarResponse) Reset() {
	*x = UserAvatarResponse{}
	mi := &file_wire_avatar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAvatarResponse) ProtoMessage() {}

func (x *UserAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_avatar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAvatarResponse.ProtoReflect.Descriptor instead.
func (*UserAvatarResponse) Descriptor() ([]byte, []int) {
	return file_wire_avatar_proto_rawDescGZIP(), []int{0}
}

func (x *UserAvatarResponse) GetUser() *UserAvatarProjection {
	if x != nil {
		return x.User
	}
	return nil
}

type UserAvatarProjection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Avatar        *AvatarImageSet        `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAvatarProjection) Reset() {
	*x = UserAvatarProjection{}
	mi := &file_wire_avatar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAvatarProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAvatarProjection) ProtoMessage() {}

func (x *UserAvatarProjection) ProtoReflect() protoreflect.Message {
	mi := &file_wire_avatar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAvatarProjection.ProtoReflect.Descriptor instead.
func (*UserAvatarProjection) Descriptor() ([]byte, []int) {
	return file_wire_avatar_proto_rawDescGZIP(), []int{1}
}

func (x *UserAvatarProjection) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserAvatarProjection) GetAvatar() *AvatarImageSet {
	if x != nil {
		return x.Avatar
	}
	return nil
}

type AvatarImageSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Small         *AvatarImage           `protobuf:"bytes,1,opt,name=small,proto3" json:"small,omitempty"`
	Large         *AvatarImage           `protobuf:"bytes,2,opt,name=large,proto3" json:"large,omitempty"`
	Full          *AvatarImage           `protobuf:"bytes,3,opt,name=full,proto3" json:"full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarImageSet) Reset() {
	*x = AvatarImageSet{}
	mi := &file_wire_avatar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarImageSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarImageSet) ProtoMessage() {}

func (x *AvatarImageSet) ProtoReflect() protoreflect.Message {
	mi := &file_wire_avatar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarImageSet.ProtoReflect.Descriptor instead.
func (*AvatarImageSet) Descriptor() ([]byte, []int) {
	return file_wire_avatar_proto_rawDescGZIP(), []int{2}
}

func (x *AvatarImageSet) GetSmall() *AvatarImage {
	if x != nil {
		return x.Small
	}
	return nil
}

func (x *AvatarImageSet) GetLarge() *AvatarImage {
	if x != nil {
		return x.Large
	}
	return nil
}

func (x *AvatarImageSet) GetFull() *AvatarImage {
	if x != nil {
		return x.Full
	}
	return nil
}

type AvatarImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileLocation          `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	FileSize      int32                  `protobuf:"varint,4,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvatarImage) Reset() {
	*x = AvatarImage{}
	mi := &file_wire_avatar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvatarImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarImage) ProtoMessage() {}

func (x *AvatarImage) ProtoReflect() protoreflect.Message {
	mi := &file_wire_avatar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarImage.ProtoReflect.Descriptor instead.
func (*AvatarImage) Descriptor() ([]byte, []int) {
	return file_wire_avatar_proto_rawDescGZIP(), []int{3}
}

func (x *AvatarImage) GetFile() *FileLocation {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *AvatarImage) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *AvatarImage) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *AvatarImage) GetFileSize() int32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

var File_wire_avatar_proto protoreflect.FileDescriptor

const file_wire_avatar_proto_rawDesc = "" +
	"\n" +
	"\x11wire/avatar.proto\x12\x15gobale.bale.reference\x1a\x0fwire/bale.proto\"U\n" +
	"\x12UserAvatarResponse\x12?\n" +
	"\x04user\x18\x01 \x01(\v2+.gobale.bale.reference.UserAvatarProjectionR\x04user\"e\n" +
	"\x14UserAvatarProjection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12=\n" +
	"\x06avatar\x18\x06 \x01(\v2%.gobale.bale.reference.AvatarImageSetR\x06avatar\"\xbc\x01\n" +
	"\x0eAvatarImageSet\x128\n" +
	"\x05small\x18\x01 \x01(\v2\".gobale.bale.reference.AvatarImageR\x05small\x128\n" +
	"\x05large\x18\x02 \x01(\v2\".gobale.bale.reference.AvatarImageR\x05large\x126\n" +
	"\x04full\x18\x03 \x01(\v2\".gobale.bale.reference.AvatarImageR\x04full\"\x91\x01\n" +
	"\vAvatarImage\x127\n" +
	"\x04file\x18\x01 \x01(\v2#.gobale.bale.reference.FileLocationR\x04file\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12\x1b\n" +
	"\tfile_size\x18\x04 \x01(\x05R\bfileSizeB8Z6github.com/mimalef70/goomni/src/internal/balemeow/wireb\x06proto3"

var (
	file_wire_avatar_proto_rawDescOnce sync.Once
	file_wire_avatar_proto_rawDescData []byte
)

func file_wire_avatar_proto_rawDescGZIP() []byte {
	file_wire_avatar_proto_rawDescOnce.Do(func() {
		file_wire_avatar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_avatar_proto_rawDesc), len(file_wire_avatar_proto_rawDesc)))
	})
	return file_wire_avatar_proto_rawDescData
}

var file_wire_avatar_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_wire_avatar_proto_goTypes = []any{
	(*UserAvatarResponse)(nil),   // 0: gobale.bale.reference.UserAvatarResponse
	(*UserAvatarProjection)(nil), // 1: gobale.bale.reference.UserAvatarProjection
	(*AvatarImageSet)(nil),       // 2: gobale.bale.reference.AvatarImageSet
	(*AvatarImage)(nil),          // 3: gobale.bale.reference.AvatarImage
	(*FileLocation)(nil),         // 4: gobale.bale.reference.FileLocation
}
var file_wire_avatar_proto_depIdxs = []int32{
	1, // 0: gobale.bale.reference.UserAvatarResponse.user:type_name -> gobale.bale.reference.UserAvatarProjection
	2, // 1: gobale.bale.reference.UserAvatarProjection.avatar:type_name -> gobale.bale.reference.AvatarImageSet
	3, // 2: gobale.bale.reference.AvatarImageSet.small:type_name -> gobale.bale.reference.AvatarImage
	3, // 3: gobale.bale.reference.AvatarImageSet.large:type_name -> gobale.bale.reference.AvatarImage
	3, // 4: gobale.bale.reference.AvatarImageSet.full:type_name -> gobale.bale.reference.AvatarImage
	4, // 5: gobale.bale.reference.AvatarImage.file:type_name -> gobale.bale.reference.FileLocation
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_wire_avatar_proto_init() }
func file_wire_avatar_proto_init() {
	if File_wire_avatar_proto != nil {
		return
	}
	file_wire_bale_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_avatar_proto_rawDesc), len(file_wire_avatar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_avatar_proto_goTypes,
		DependencyIndexes: file_wire_avatar_proto_depIdxs,
		MessageInfos:      file_wire_avatar_proto_msgTypes,
	}.Build()
	File_wire_avatar_proto = out.File
	file_wire_avatar_proto_goTypes = nil
	file_wire_avatar_proto_depIdxs = nil
}
