// Field numbers reviewed against the public Bale Web 5.7.0 bundle, 2026-10-06.
// 9216.fb97157470.js service encoders and index module 11125, not inferred values.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: wire/groups_extended.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupPermissions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SeeMessage           bool                   `protobuf:"varint,1,opt,name=see_message,json=seeMessage,proto3" json:"see_message,omitempty"`
	DeleteMessage        bool                   `protobuf:"varint,2,opt,name=delete_message,json=deleteMessage,proto3" json:"delete_message,omitempty"`
	KickUser             bool                   `protobuf:"varint,3,opt,name=kick_user,json=kickUser,proto3" json:"kick_user,omitempty"`
	PinMessage           bool                   `protobuf:"varint,4,opt,name=pin_message,json=pinMessage,proto3" json:"pin_message,omitempty"`
	InviteUser           bool                   `protobuf:"varint,5,opt,name=invite_user,json=inviteUser,proto3" json:"invite_user,omitempty"`
	AddAdmin             bool                   `protobuf:"varint,6,opt,name=add_admin,json=addAdmin,proto3" json:"add_admin,omitempty"`
	ChangeInfo           bool                   `protobuf:"varint,7,opt,name=change_info,json=changeInfo,proto3" json:"change_info,omitempty"`
	SendMessage          bool                   `protobuf:"varint,8,opt,name=send_message,json=sendMessage,proto3" json:"send_message,omitempty"`
	SeeMembers           bool                   `protobuf:"varint,9,opt,name=see_members,json=seeMembers,proto3" json:"see_members,omitempty"`
	EditMessage          bool                   `protobuf:"varint,10,opt,name=edit_message,json=editMessage,proto3" json:"edit_message,omitempty"`
	SendMedia            *BoolValue             `protobuf:"bytes,11,opt,name=send_media,json=sendMedia,proto3" json:"send_media,omitempty"`
	SendGifStickers      *BoolValue             `protobuf:"bytes,12,opt,name=send_gif_stickers,json=sendGifStickers,proto3" json:"send_gif_stickers,omitempty"`
	ReplyToStory         *BoolValue             `protobuf:"bytes,13,opt,name=reply_to_story,json=replyToStory,proto3" json:"reply_to_story,omitempty"`
	ForwardMessageFrom   *BoolValue             `protobuf:"bytes,14,opt,name=forward_message_from,json=forwardMessageFrom,proto3" json:"forward_message_from,omitempty"`
	SendGiftPacket       *BoolValue             `protobuf:"bytes,15,opt,name=send_gift_packet,json=sendGiftPacket,proto3" json:"send_gift_packet,omitempty"`
	StartCall            *BoolValue             `protobuf:"bytes,16,opt,name=start_call,json=startCall,proto3" json:"start_call,omitempty"`
	SendLinkMessage      *BoolValue             `protobuf:"bytes,17,opt,name=send_link_message,json=sendLinkMessage,proto3" json:"send_link_message,omitempty"`
	SendForwardedMessage *BoolValue             `protobuf:"bytes,18,opt,name=send_forwarded_message,json=sendForwardedMessage,proto3" json:"send_forwarded_message,omitempty"`
	AddStory             *BoolValue             `protobuf:"bytes,19,opt,name=add_story,json=addStory,proto3" json:"add_story,omitempty"`
	ManageCall           *BoolValue             `protobuf:"bytes,20,opt,name=manage_call,json=manageCall,proto3" json:"manage_call,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GroupPermissions) Reset() {
	*x = GroupPermissions{}
	mi := &file_wire_groups_extended_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPermissions) ProtoMessage() {}

func (x *GroupPermissions) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPermissions.ProtoReflect.Descriptor instead.
func (*GroupPermissions) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{0}
}

func (x *GroupPermissions) GetSeeMessage() bool {
	if x != nil {
		return x.SeeMessage
	}
	return false
}

func (x *GroupPermissions) GetDeleteMessage() bool {
	if x != nil {
		return x.DeleteMessage
	}
	return false
}

func (x *GroupPermissions) GetKickUser() bool {
	if x != nil {
		return x.KickUser
	}
	return false
}

func (x *GroupPermissions) GetPinMessage() bool {
	if x != nil {
		return x.PinMessage
	}
	return false
}

func (x *GroupPermissions) GetInviteUser() bool {
	if x != nil {
		return x.InviteUser
	}
	return false
}

func (x *GroupPermissions) GetAddAdmin() bool {
	if x != nil {
		return x.AddAdmin
	}
	return false
}

func (x *GroupPermissions) GetChangeInfo() bool {
	if x != nil {
		return x.ChangeInfo
	}
	return false
}

func (x *GroupPermissions) GetSendMessage() bool {
	if x != nil {
		return x.SendMessage
	}
	return false
}

func (x *GroupPermissions) GetSeeMembers() bool {
	if x != nil {
		return x.SeeMembers
	}
	return false
}

func (x *GroupPermissions) GetEditMessage() bool {
	if x != nil {
		return x.EditMessage
	}
	return false
}

func (x *GroupPermissions) GetSendMedia() *BoolValue {
	if x != nil {
		return x.SendMedia
	}
	return nil
}

func (x *GroupPermissions) GetSendGifStickers() *BoolValue {
	if x != nil {
		return x.SendGifStickers
	}
	return nil
}

func (x *GroupPermissions) GetReplyToStory() *BoolValue {
	if x != nil {
		return x.ReplyToStory
	}
	return nil
}

func (x *GroupPermissions) GetForwardMessageFrom() *BoolValue {
	if x != nil {
		return x.ForwardMessageFrom
	}
	return nil
}

func (x *GroupPermissions) GetSendGiftPacket() *BoolValue {
	if x != nil {
		return x.SendGiftPacket
	}
	return nil
}

func (x *GroupPermissions) GetStartCall() *BoolValue {
	if x != nil {
		return x.StartCall
	}
	return nil
}

func (x *GroupPermissions) GetSendLinkMessage() *BoolValue {
	if x != nil {
		return x.SendLinkMessage
	}
	return nil
}

func (x *GroupPermissions) GetSendForwardedMessage() *BoolValue {
	if x != nil {
		return x.SendForwardedMessage
	}
	return nil
}

func (x *GroupPermissions) GetAddStory() *BoolValue {
	if x != nil {
		return x.AddStory
	}
	return nil
}

func (x *GroupPermissions) GetManageCall() *BoolValue {
	if x != nil {
		return x.ManageCall
	}
	return nil
}

type GroupExtendedMember struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Uid            uint32                 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	InviterUid     uint32                 `protobuf:"varint,2,opt,name=inviter_uid,json=inviterUid,proto3" json:"inviter_uid,omitempty"`
	Date           int64                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	IsAdmin        *BoolValue             `protobuf:"bytes,4,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	PromoterUserId *Int32Value            `protobuf:"bytes,5,opt,name=promoter_user_id,json=promoterUserId,proto3" json:"promoter_user_id,omitempty"`
	PromotedAt     *Int64Value            `protobuf:"bytes,6,opt,name=promoted_at,json=promotedAt,proto3" json:"promoted_at,omitempty"`
	Permissions    *GroupPermissions      `protobuf:"bytes,7,opt,name=permissions,proto3" json:"permissions,omitempty"`
	Title          *StringValue           `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroupExtendedMember) Reset() {
	*x = GroupExtendedMember{}
	mi := &file_wire_groups_extended_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupExtendedMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupExtendedMember) ProtoMessage() {}

func (x *GroupExtendedMember) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupExtendedMember.ProtoReflect.Descriptor instead.
func (*GroupExtendedMember) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{1}
}

func (x *GroupExtendedMember) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GroupExtendedMember) GetInviterUid() uint32 {
	if x != nil {
		return x.InviterUid
	}
	return 0
}

func (x *GroupExtendedMember) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *GroupExtendedMember) GetIsAdmin() *BoolValue {
	if x != nil {
		return x.IsAdmin
	}
	return nil
}

func (x *GroupExtendedMember) GetPromoterUserId() *Int32Value {
	if x != nil {
		return x.PromoterUserId
	}
	return nil
}

func (x *GroupExtendedMember) GetPromotedAt() *Int64Value {
	if x != nil {
		return x.PromotedAt
	}
	return nil
}

func (x *GroupExtendedMember) GetPermissions() *GroupPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GroupExtendedMember) GetTitle() *StringValue {
	if x != nil {
		return x.Title
	}
	return nil
}

type GroupFullExtended struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccessHash         int64                  `protobuf:"varint,2,opt,name=access_hash,json=accessHash,proto3" json:"access_hash,omitempty"`
	Title              string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	OwnerUid           uint32                 `protobuf:"varint,5,opt,name=owner_uid,json=ownerUid,proto3" json:"owner_uid,omitempty"`
	CreateDate         int64                  `protobuf:"varint,6,opt,name=create_date,json=createDate,proto3" json:"create_date,omitempty"`
	GroupType          int32                  `protobuf:"varint,7,opt,name=group_type,json=groupType,proto3" json:"group_type,omitempty"`
	IsMember           *BoolValue             `protobuf:"bytes,8,opt,name=is_member,json=isMember,proto3" json:"is_member,omitempty"`
	MembersCount       *Int32Value            `protobuf:"bytes,10,opt,name=members_count,json=membersCount,proto3" json:"members_count,omitempty"`
	Nick               *StringValue           `protobuf:"bytes,11,opt,name=nick,proto3" json:"nick,omitempty"`
	Permissions        *GroupPermissions      `protobuf:"bytes,13,opt,name=permissions,proto3" json:"permissions,omitempty"`
	DefaultPermissions *GroupPermissions      `protobuf:"bytes,14,opt,name=default_permissions,json=defaultPermissions,proto3" json:"default_permissions,omitempty"`
	About              *StringValue           `protobuf:"bytes,16,opt,name=about,proto3" json:"about,omitempty"`
	Members            []*GroupExtendedMember `protobuf:"bytes,17,rep,name=members,proto3" json:"members,omitempty"`
	Restriction        int32                  `protobuf:"varint,20,opt,name=restriction,proto3" json:"restriction,omitempty"`
	AvailableReactions []string               `protobuf:"bytes,24,rep,name=available_reactions,json=availableReactions,proto3" json:"available_reactions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GroupFullExtended) Reset() {
	*x = GroupFullExtended{}
	mi := &file_wire_groups_extended_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupFullExtended) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupFullExtended) ProtoMessage() {}

func (x *GroupFullExtended) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupFullExtended.ProtoReflect.Descriptor instead.
func (*GroupFullExtended) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{2}
}

func (x *GroupFullExtended) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupFullExtended) GetAccessHash() int64 {
	if x != nil {
		return x.AccessHash
	}
	return 0
}

func (x *GroupFullExtended) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GroupFullExtended) GetOwnerUid() uint32 {
	if x != nil {
		return x.OwnerUid
	}
	return 0
}

func (x *GroupFullExtended) GetCreateDate() int64 {
	if x != nil {
		return x.CreateDate
	}
	return 0
}

func (x *GroupFullExtended) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *GroupFullExtended) GetIsMember() *BoolValue {
	if x != nil {
		return x.IsMember
	}
	return nil
}

func (x *GroupFullExtended) GetMembersCount() *Int32Value {
	if x != nil {
		return x.MembersCount
	}
	return nil
}

func (x *GroupFullExtended) GetNick() *StringValue {
	if x != nil {
		return x.Nick
	}
	return nil
}

func (x *GroupFullExtended) GetPermissions() *GroupPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *GroupFullExtended) GetDefaultPermissions() *GroupPermissions {
	if x != nil {
		return x.DefaultPermissions
	}
	return nil
}

func (x *GroupFullExtended) GetAbout() *StringValue {
	if x != nil {
		return x.About
	}
	return nil
}

func (x *GroupFullExtended) GetMembers() []*GroupExtendedMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GroupFullExtended) GetRestriction() int32 {
	if x != nil {
		return x.Restriction
	}
	return 0
}

func (x *GroupFullExtended) GetAvailableReactions() []string {
	if x != nil {
		return x.AvailableReactions
	}
	return nil
}

type GroupFullExtendedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *GroupFullExtended     `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Action        int32                  `protobuf:"varint,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupFullExtendedResponse) Reset() {
	*x = GroupFullExtendedResponse{}
	mi := &file_wire_groups_extended_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupFullExtendedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupFullExtendedResponse) ProtoMessage() {}

func (x *GroupFullExtendedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupFullExtendedResponse.ProtoReflect.Descriptor instead.
func (*GroupFullExtendedResponse) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{3}
}

func (x *GroupFullExtendedResponse) GetGroup() *GroupFullExtended {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupFullExtendedResponse) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

type GroupCreateExtendedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rid           int64                  `protobuf:"varint,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Users         []*PeerRef             `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	GroupType     int32                  `protobuf:"varint,6,opt,name=group_type,json=groupType,proto3" json:"group_type,omitempty"`
	Nick          *StringValue           `protobuf:"bytes,8,opt,name=nick,proto3" json:"nick,omitempty"`
	Restriction   int32                  `protobuf:"varint,9,opt,name=restriction,proto3" json:"restriction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupCreateExtendedRequest) Reset() {
	*x = GroupCreateExtendedRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupCreateExtendedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupCreateExtendedRequest) ProtoMessage() {}

func (x *GroupCreateExtendedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupCreateExtendedRequest.ProtoReflect.Descriptor instead.
func (*GroupCreateExtendedRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{4}
}

func (x *GroupCreateExtendedRequest) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *GroupCreateExtendedRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GroupCreateExtendedRequest) GetUsers() []*PeerRef {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GroupCreateExtendedRequest) GetGroupType() int32 {
	if x != nil {
		return x.GroupType
	}
	return 0
}

func (x *GroupCreateExtendedRequest) GetNick() *StringValue {
	if x != nil {
		return x.Nick
	}
	return nil
}

func (x *GroupCreateExtendedRequest) GetRestriction() int32 {
	if x != nil {
		return x.Restriction
	}
	return 0
}

type GroupAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	User          *PeerRef               `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	AdminTitle    *StringValue           `protobuf:"bytes,3,opt,name=admin_title,json=adminTitle,proto3" json:"admin_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAdminRequest) Reset() {
	*x = GroupAdminRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAdminRequest) ProtoMessage() {}

func (x *GroupAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAdminRequest.ProtoReflect.Descriptor instead.
func (*GroupAdminRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{5}
}

func (x *GroupAdminRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupAdminRequest) GetUser() *PeerRef {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GroupAdminRequest) GetAdminTitle() *StringValue {
	if x != nil {
		return x.AdminTitle
	}
	return nil
}

type GroupTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	NewOwner      uint32                 `protobuf:"varint,2,opt,name=new_owner,json=newOwner,proto3" json:"new_owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupTransferRequest) Reset() {
	*x = GroupTransferRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTransferRequest) ProtoMessage() {}

func (x *GroupTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTransferRequest.ProtoReflect.Descriptor instead.
func (*GroupTransferRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{6}
}

func (x *GroupTransferRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupTransferRequest) GetNewOwner() uint32 {
	if x != nil {
		return x.NewOwner
	}
	return 0
}

type GroupMemberPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	User          *PeerRef               `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberPermissionsRequest) Reset() {
	*x = GroupMemberPermissionsRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberPermissionsRequest) ProtoMessage() {}

func (x *GroupMemberPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GroupMemberPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{7}
}

func (x *GroupMemberPermissionsRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupMemberPermissionsRequest) GetUser() *PeerRef {
	if x != nil {
		return x.User
	}
	return nil
}

type GroupMemberPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   *GroupPermissions      `protobuf:"bytes,1,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberPermissionsResponse) Reset() {
	*x = GroupMemberPermissionsResponse{}
	mi := &file_wire_groups_extended_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberPermissionsResponse) ProtoMessage() {}

func (x *GroupMemberPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberPermissionsResponse.ProtoReflect.Descriptor instead.
func (*GroupMemberPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{8}
}

func (x *GroupMemberPermissionsResponse) GetPermissions() *GroupPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GroupSetMemberPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	User          *PeerRef               `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Permissions   *GroupPermissions      `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSetMemberPermissionsRequest) Reset() {
	*x = GroupSetMemberPermissionsRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSetMemberPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSetMemberPermissionsRequest) ProtoMessage() {}

func (x *GroupSetMemberPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSetMemberPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GroupSetMemberPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{9}
}

func (x *GroupSetMemberPermissionsRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupSetMemberPermissionsRequest) GetUser() *PeerRef {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GroupSetMemberPermissionsRequest) GetPermissions() *GroupPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GroupSetDefaultPermissionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Permissions   *GroupPermissions      `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupSetDefaultPermissionsRequest) Reset() {
	*x = GroupSetDefaultPermissionsRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupSetDefaultPermissionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupSetDefaultPermissionsRequest) ProtoMessage() {}

func (x *GroupSetDefaultPermissionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupSetDefaultPermissionsRequest.ProtoReflect.Descriptor instead.
func (*GroupSetDefaultPermissionsRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{10}
}

func (x *GroupSetDefaultPermissionsRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupSetDefaultPermissionsRequest) GetPermissions() *GroupPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GroupJoinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupJoinRequest) Reset() {
	*x = GroupJoinRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupJoinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupJoinRequest) ProtoMessage() {}

func (x *GroupJoinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupJoinRequest.ProtoReflect.Descriptor instead.
func (*GroupJoinRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{11}
}

func (x *GroupJoinRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GroupJoinPublicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *Peer                  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupJoinPublicRequest) Reset() {
	*x = GroupJoinPublicRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupJoinPublicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupJoinPublicRequest) ProtoMessage() {}

func (x *GroupJoinPublicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupJoinPublicRequest.ProtoReflect.Descriptor instead.
func (*GroupJoinPublicRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{12}
}

func (x *GroupJoinPublicRequest) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type GroupJoinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Sequence      int32                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	Date          int64                  `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	Users         []*User                `protobuf:"bytes,5,rep,name=users,proto3" json:"users,omitempty"`
	Rid           int64                  `protobuf:"varint,6,opt,name=rid,proto3" json:"rid,omitempty"`
	UserPeers     []*PeerRef             `protobuf:"bytes,7,rep,name=user_peers,json=userPeers,proto3" json:"user_peers,omitempty"`
	InviterUid    uint32                 `protobuf:"varint,8,opt,name=inviter_uid,json=inviterUid,proto3" json:"inviter_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupJoinResponse) Reset() {
	*x = GroupJoinResponse{}
	mi := &file_wire_groups_extended_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupJoinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupJoinResponse) ProtoMessage() {}

func (x *GroupJoinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupJoinResponse.ProtoReflect.Descriptor instead.
func (*GroupJoinResponse) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{13}
}

func (x *GroupJoinResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupJoinResponse) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GroupJoinResponse) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *GroupJoinResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GroupJoinResponse) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *GroupJoinResponse) GetUserPeers() []*PeerRef {
	if x != nil {
		return x.UserPeers
	}
	return nil
}

func (x *GroupJoinResponse) GetInviterUid() uint32 {
	if x != nil {
		return x.InviterUid
	}
	return 0
}

type GroupLeaveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Rid           int64                  `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty"`
	MakeOrphan    *BoolValue             `protobuf:"bytes,4,opt,name=make_orphan,json=makeOrphan,proto3" json:"make_orphan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupLeaveRequest) Reset() {
	*x = GroupLeaveRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupLeaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupLeaveRequest) ProtoMessage() {}

func (x *GroupLeaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupLeaveRequest.ProtoReflect.Descriptor instead.
func (*GroupLeaveRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{14}
}

func (x *GroupLeaveRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupLeaveRequest) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *GroupLeaveRequest) GetMakeOrphan() *BoolValue {
	if x != nil {
		return x.MakeOrphan
	}
	return nil
}

type GroupUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Nick          string                 `protobuf:"bytes,2,opt,name=nick,proto3" json:"nick,omitempty"`
	Rid           int64                  `protobuf:"varint,3,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUsernameRequest) Reset() {
	*x = GroupUsernameRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUsernameRequest) ProtoMessage() {}

func (x *GroupUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUsernameRequest.ProtoReflect.Descriptor instead.
func (*GroupUsernameRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{15}
}

func (x *GroupUsernameRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupUsernameRequest) GetNick() string {
	if x != nil {
		return x.Nick
	}
	return ""
}

func (x *GroupUsernameRequest) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

type GroupRestrictionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Restriction   int32                  `protobuf:"varint,2,opt,name=restriction,proto3" json:"restriction,omitempty"`
	Nick          *StringValue           `protobuf:"bytes,3,opt,name=nick,proto3" json:"nick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRestrictionRequest) Reset() {
	*x = GroupRestrictionRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRestrictionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRestrictionRequest) ProtoMessage() {}

func (x *GroupRestrictionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRestrictionRequest.ProtoReflect.Descriptor instead.
func (*GroupRestrictionRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{16}
}

func (x *GroupRestrictionRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupRestrictionRequest) GetRestriction() int32 {
	if x != nil {
		return x.Restriction
	}
	return 0
}

func (x *GroupRestrictionRequest) GetNick() *StringValue {
	if x != nil {
		return x.Nick
	}
	return nil
}

type GroupHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	CanSeeHistory bool                   `protobuf:"varint,2,opt,name=can_see_history,json=canSeeHistory,proto3" json:"can_see_history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupHistoryRequest) Reset() {
	*x = GroupHistoryRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupHistoryRequest) ProtoMessage() {}

func (x *GroupHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupHistoryRequest.ProtoReflect.Descriptor instead.
func (*GroupHistoryRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{17}
}

func (x *GroupHistoryRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupHistoryRequest) GetCanSeeHistory() bool {
	if x != nil {
		return x.CanSeeHistory
	}
	return false
}

type GroupVisibilityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Group          *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	UserId         uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CanSeeMessages bool                   `protobuf:"varint,3,opt,name=can_see_messages,json=canSeeMessages,proto3" json:"can_see_messages,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GroupVisibilityRequest) Reset() {
	*x = GroupVisibilityRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupVisibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupVisibilityRequest) ProtoMessage() {}

func (x *GroupVisibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupVisibilityRequest.ProtoReflect.Descriptor instead.
func (*GroupVisibilityRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{18}
}

func (x *GroupVisibilityRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupVisibilityRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupVisibilityRequest) GetCanSeeMessages() bool {
	if x != nil {
		return x.CanSeeMessages
	}
	return false
}

type GroupPinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderUid     uint32                 `protobuf:"varint,1,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty"`
	Group         *PeerRef               `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Date          int64                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Rid           int64                  `protobuf:"varint,4,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPinRequest) Reset() {
	*x = GroupPinRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPinRequest) ProtoMessage() {}

func (x *GroupPinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPinRequest.ProtoReflect.Descriptor instead.
func (*GroupPinRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{19}
}

func (x *GroupPinRequest) GetSenderUid() uint32 {
	if x != nil {
		return x.SenderUid
	}
	return 0
}

func (x *GroupPinRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupPinRequest) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *GroupPinRequest) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

type GroupUnpinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Rid           int64                  `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Date          int64                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUnpinRequest) Reset() {
	*x = GroupUnpinRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUnpinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUnpinRequest) ProtoMessage() {}

func (x *GroupUnpinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUnpinRequest.ProtoReflect.Descriptor instead.
func (*GroupUnpinRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{20}
}

func (x *GroupUnpinRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupUnpinRequest) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *GroupUnpinRequest) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

type GroupPinsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPinsRequest) Reset() {
	*x = GroupPinsRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPinsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPinsRequest) ProtoMessage() {}

func (x *GroupPinsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPinsRequest.ProtoReflect.Descriptor instead.
func (*GroupPinsRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{21}
}

func (x *GroupPinsRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupPinsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GroupPinsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GroupPinnedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderUid     uint32                 `protobuf:"varint,1,opt,name=sender_uid,json=senderUid,proto3" json:"sender_uid,omitempty"`
	Rid           int64                  `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Date          int64                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	Message       *Message               `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	State         int32                  `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPinnedMessage) Reset() {
	*x = GroupPinnedMessage{}
	mi := &file_wire_groups_extended_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPinnedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPinnedMessage) ProtoMessage() {}

func (x *GroupPinnedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPinnedMessage.ProtoReflect.Descriptor instead.
func (*GroupPinnedMessage) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{22}
}

func (x *GroupPinnedMessage) GetSenderUid() uint32 {
	if x != nil {
		return x.SenderUid
	}
	return 0
}

func (x *GroupPinnedMessage) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *GroupPinnedMessage) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *GroupPinnedMessage) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *GroupPinnedMessage) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type GroupPinsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pins          []*GroupPinnedMessage  `protobuf:"bytes,1,rep,name=pins,proto3" json:"pins,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPinsResponse) Reset() {
	*x = GroupPinsResponse{}
	mi := &file_wire_groups_extended_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPinsResponse) ProtoMessage() {}

func (x *GroupPinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPinsResponse.ProtoReflect.Descriptor instead.
func (*GroupPinsResponse) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{23}
}

func (x *GroupPinsResponse) GetPins() []*GroupPinnedMessage {
	if x != nil {
		return x.Pins
	}
	return nil
}

func (x *GroupPinsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GroupBanRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannedUser    *PeerRef               `protobuf:"bytes,1,opt,name=banned_user,json=bannedUser,proto3" json:"banned_user,omitempty"`
	BannerUser    *PeerRef               `protobuf:"bytes,2,opt,name=banner_user,json=bannerUser,proto3" json:"banner_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupBanRecord) Reset() {
	*x = GroupBanRecord{}
	mi := &file_wire_groups_extended_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupBanRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupBanRecord) ProtoMessage() {}

func (x *GroupBanRecord) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupBanRecord.ProtoReflect.Descriptor instead.
func (*GroupBanRecord) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{24}
}

func (x *GroupBanRecord) GetBannedUser() *PeerRef {
	if x != nil {
		return x.BannedUser
	}
	return nil
}

func (x *GroupBanRecord) GetBannerUser() *PeerRef {
	if x != nil {
		return x.BannerUser
	}
	return nil
}

type GroupBannedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BannedUsers   []*GroupBanRecord      `protobuf:"bytes,3,rep,name=banned_users,json=bannedUsers,proto3" json:"banned_users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupBannedResponse) Reset() {
	*x = GroupBannedResponse{}
	mi := &file_wire_groups_extended_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupBannedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupBannedResponse) ProtoMessage() {}

func (x *GroupBannedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupBannedResponse.ProtoReflect.Descriptor instead.
func (*GroupBannedResponse) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{25}
}

func (x *GroupBannedResponse) GetBannedUsers() []*GroupBanRecord {
	if x != nil {
		return x.BannedUsers
	}
	return nil
}

type GroupAdminsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*PeerRef             `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Admins        []*GroupExtendedMember `protobuf:"bytes,2,rep,name=admins,proto3" json:"admins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAdminsResponse) Reset() {
	*x = GroupAdminsResponse{}
	mi := &file_wire_groups_extended_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAdminsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAdminsResponse) ProtoMessage() {}

func (x *GroupAdminsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAdminsResponse.ProtoReflect.Descriptor instead.
func (*GroupAdminsResponse) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{26}
}

func (x *GroupAdminsResponse) GetUsers() []*PeerRef {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *GroupAdminsResponse) GetAdmins() []*GroupExtendedMember {
	if x != nil {
		return x.Admins
	}
	return nil
}

type GroupPhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	FileLocation  *FileLocation          `protobuf:"bytes,3,opt,name=file_location,json=fileLocation,proto3" json:"file_location,omitempty"`
	Rid           int64                  `protobuf:"varint,4,opt,name=rid,proto3" json:"rid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupPhotoRequest) Reset() {
	*x = GroupPhotoRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupPhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupPhotoRequest) ProtoMessage() {}

func (x *GroupPhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupPhotoRequest.ProtoReflect.Descriptor instead.
func (*GroupPhotoRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{27}
}

func (x *GroupPhotoRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupPhotoRequest) GetFileLocation() *FileLocation {
	if x != nil {
		return x.FileLocation
	}
	return nil
}

func (x *GroupPhotoRequest) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

type GroupRemovePhotoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Rid           int64                  `protobuf:"varint,4,opt,name=rid,proto3" json:"rid,omitempty"`
	AvatarId      *Int64Value            `protobuf:"bytes,6,opt,name=avatar_id,json=avatarId,proto3" json:"avatar_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupRemovePhotoRequest) Reset() {
	*x = GroupRemovePhotoRequest{}
	mi := &file_wire_groups_extended_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupRemovePhotoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupRemovePhotoRequest) ProtoMessage() {}

func (x *GroupRemovePhotoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_groups_extended_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupRemovePhotoRequest.ProtoReflect.Descriptor instead.
func (*GroupRemovePhotoRequest) Descriptor() ([]byte, []int) {
	return file_wire_groups_extended_proto_rawDescGZIP(), []int{28}
}

func (x *GroupRemovePhotoRequest) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupRemovePhotoRequest) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *GroupRemovePhotoRequest) GetAvatarId() *Int64Value {
	if x != nil {
		return x.AvatarId
	}
	return nil
}

var File_wire_groups_extended_proto protoreflect.FileDescriptor

const file_wire_groups_extended_proto_rawDesc = "" +
	"\n" +
	"\x1awire/groups_extended.proto\x12\x15gobale.bale.reference\x1a\x0fwire/bale.proto\"\xbe\b\n" +
	"\x10GroupPermissions\x12\x1f\n" +
	"\vsee_message\x18\x01 \x01(\bR\n" +
	"seeMessage\x12%\n" +
	"\x0edelete_message\x18\x02 \x01(\bR\rdeleteMessage\x12\x1b\n" +
	"\tkick_user\x18\x03 \x01(\bR\bkickUser\x12\x1f\n" +
	"\vpin_message\x18\x04 \x01(\bR\n" +
	"pinMessage\x12\x1f\n" +
	"\vinvite_user\x18\x05 \x01(\bR\n" +
	"inviteUser\x12\x1b\n" +
	"\tadd_admin\x18\x06 \x01(\bR\baddAdmin\x12\x1f\n" +
	"\vchange_info\x18\a \x01(\bR\n" +
	"changeInfo\x12!\n" +
	"\fsend_message\x18\b \x01(\bR\vsendMessage\x12\x1f\n" +
	"\vsee_members\x18\t \x01(\bR\n" +
	"seeMembers\x12!\n" +
	"\fedit_message\x18\n" +
	" \x01(\bR\veditMessage\x12?\n" +
	"\n" +
	"send_media\x18\v \x01(\v2 .gobale.bale.reference.BoolValueR\tsendMedia\x12L\n" +
	"\x11send_gif_stickers\x18\f \x01(\v2 .gobale.bale.reference.BoolValueR\x0fsendGifStickers\x12F\n" +
	"\x0ereply_to_story\x18\r \x01(\v2 .gobale.bale.reference.BoolValueR\freplyToStory\x12R\n" +
	"\x14forward_message_from\x18\x0e \x01(\v2 .gobale.bale.reference.BoolValueR\x12forwardMessageFrom\x12J\n" +
	"\x10send_gift_packet\x18\x0f \x01(\v2 .gobale.bale.reference.BoolValueR\x0esendGiftPacket\x12?\n" +
	"\n" +
	"start_call\x18\x10 \x01(\v2 .gobale.bale.reference.BoolValueR\tstartCall\x12L\n" +
	"\x11send_link_message\x18\x11 \x01(\v2 .gobale.bale.reference.BoolValueR\x0fsendLinkMessage\x12V\n" +
	"\x16send_forwarded_message\x18\x12 \x01(\v2 .gobale.bale.reference.BoolValueR\x14sendForwardedMessage\x12=\n" +
	"\tadd_story\x18\x13 \x01(\v2 .gobale.bale.reference.BoolValueR\baddStory\x12A\n" +
	"\vmanage_call\x18\x14 \x01(\v2 .gobale.bale.reference.BoolValueR\n" +
	"manageCall\"\xaf\x03\n" +
	"\x13GroupExtendedMember\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\rR\x03uid\x12\x1f\n" +
	"\vinviter_uid\x18\x02 \x01(\rR\n" +
	"inviterUid\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x03R\x04date\x12;\n" +
	"\bis_admin\x18\x04 \x01(\v2 .gobale.bale.reference.BoolValueR\aisAdmin\x12K\n" +
	"\x10promoter_user_id\x18\x05 \x01(\v2!.gobale.bale.reference.Int32ValueR\x0epromoterUserId\x12B\n" +
	"\vpromoted_at\x18\x06 \x01(\v2!.gobale.bale.reference.Int64ValueR\n" +
	"promotedAt\x12I\n" +
	"\vpermissions\x18\a \x01(\v2'.gobale.bale.reference.GroupPermissionsR\vpermissions\x128\n" +
	"\x05title\x18\b \x01(\v2\".gobale.bale.reference.StringValueR\x05title\"\xee\x05\n" +
	"\x11GroupFullExtended\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vaccess_hash\x18\x02 \x01(\x03R\n" +
	"accessHash\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1b\n" +
	"\towner_uid\x18\x05 \x01(\rR\bownerUid\x12\x1f\n" +
	"\vcreate_date\x18\x06 \x01(\x03R\n" +
	"createDate\x12\x1d\n" +
	"\n" +
	"group_type\x18\a \x01(\x05R\tgroupType\x12=\n" +
	"\tis_member\x18\b \x01(\v2 .gobale.bale.reference.BoolValueR\bisMember\x12F\n" +
	"\rmembers_count\x18\n" +
	" \x01(\v2!.gobale.bale.reference.Int32ValueR\fmembersCount\x126\n" +
	"\x04nick\x18\v \x01(\v2\".gobale.bale.reference.StringValueR\x04nick\x12I\n" +
	"\vpermissions\x18\r \x01(\v2'.gobale.bale.reference.GroupPermissionsR\vpermissions\x12X\n" +
	"\x13default_permissions\x18\x0e \x01(\v2'.gobale.bale.reference.GroupPermissionsR\x12defaultPermissions\x128\n" +
	"\x05about\x18\x10 \x01(\v2\".gobale.bale.reference.StringValueR\x05about\x12D\n" +
	"\amembers\x18\x11 \x03(\v2*.gobale.bale.reference.GroupExtendedMemberR\amembers\x12 \n" +
	"\vrestriction\x18\x14 \x01(\x05R\vrestriction\x12/\n" +
	"\x13available_reactions\x18\x18 \x03(\tR\x12availableReactions\"s\n" +
	"\x19GroupFullExtendedResponse\x12>\n" +
	"\x05group\x18\x01 \x01(\v2(.gobale.bale.reference.GroupFullExtendedR\x05group\x12\x16\n" +
	"\x06action\x18\x02 \x01(\x05R\x06action\"\xf3\x01\n" +
	"\x1aGroupCreateExtendedRequest\x12\x10\n" +
	"\x03rid\x18\x01 \x01(\x03R\x03rid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x124\n" +
	"\x05users\x18\x03 \x03(\v2\x1e.gobale.bale.reference.PeerRefR\x05users\x12\x1d\n" +
	"\n" +
	"group_type\x18\x06 \x01(\x05R\tgroupType\x126\n" +
	"\x04nick\x18\b \x01(\v2\".gobale.bale.reference.StringValueR\x04nick\x12 \n" +
	"\vrestriction\x18\t \x01(\x05R\vrestriction\"\xc2\x01\n" +
	"\x11GroupAdminRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x122\n" +
	"\x04user\x18\x02 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x04user\x12C\n" +
	"\vadmin_title\x18\x03 \x01(\v2\".gobale.bale.reference.StringValueR\n" +
	"adminTitle\"i\n" +
	"\x14GroupTransferRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12\x1b\n" +
	"\tnew_owner\x18\x02 \x01(\rR\bnewOwner\"\x89\x01\n" +
	"\x1dGroupMemberPermissionsRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x122\n" +
	"\x04user\x18\x02 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x04user\"k\n" +
	"\x1eGroupMemberPermissionsResponse\x12I\n" +
	"\vpermissions\x18\x01 \x01(\v2'.gobale.bale.reference.GroupPermissionsR\vpermissions\"\xd7\x01\n" +
	" GroupSetMemberPermissionsRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x122\n" +
	"\x04user\x18\x02 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x04user\x12I\n" +
	"\vpermissions\x18\x03 \x01(\v2'.gobale.bale.reference.GroupPermissionsR\vpermissions\"\xa4\x01\n" +
	"!GroupSetDefaultPermissionsRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12I\n" +
	"\vpermissions\x18\x02 \x01(\v2'.gobale.bale.reference.GroupPermissionsR\vpermissions\"(\n" +
	"\x10GroupJoinRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"I\n" +
	"\x16GroupJoinPublicRequest\x12/\n" +
	"\x04peer\x18\x01 \x01(\v2\x1b.gobale.bale.reference.PeerR\x04peer\"\x9c\x02\n" +
	"\x11GroupJoinResponse\x122\n" +
	"\x05group\x18\x01 \x01(\v2\x1c.gobale.bale.reference.GroupR\x05group\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x05R\bsequence\x12\x12\n" +
	"\x04date\x18\x04 \x01(\x03R\x04date\x121\n" +
	"\x05users\x18\x05 \x03(\v2\x1b.gobale.bale.reference.UserR\x05users\x12\x10\n" +
	"\x03rid\x18\x06 \x01(\x03R\x03rid\x12=\n" +
	"\n" +
	"user_peers\x18\a \x03(\v2\x1e.gobale.bale.reference.PeerRefR\tuserPeers\x12\x1f\n" +
	"\vinviter_uid\x18\b \x01(\rR\n" +
	"inviterUid\"\x9e\x01\n" +
	"\x11GroupLeaveRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12\x10\n" +
	"\x03rid\x18\x02 \x01(\x03R\x03rid\x12A\n" +
	"\vmake_orphan\x18\x04 \x01(\v2 .gobale.bale.reference.BoolValueR\n" +
	"makeOrphan\"r\n" +
	"\x14GroupUsernameRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12\x12\n" +
	"\x04nick\x18\x02 \x01(\tR\x04nick\x12\x10\n" +
	"\x03rid\x18\x03 \x01(\x03R\x03rid\"\xa9\x01\n" +
	"\x17GroupRestrictionRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12 \n" +
	"\vrestriction\x18\x02 \x01(\x05R\vrestriction\x126\n" +
	"\x04nick\x18\x03 \x01(\v2\".gobale.bale.reference.StringValueR\x04nick\"s\n" +
	"\x13GroupHistoryRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12&\n" +
	"\x0fcan_see_history\x18\x02 \x01(\bR\rcanSeeHistory\"\x91\x01\n" +
	"\x16GroupVisibilityRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12(\n" +
	"\x10can_see_messages\x18\x03 \x01(\bR\x0ecanSeeMessages\"\x8c\x01\n" +
	"\x0fGroupPinRequest\x12\x1d\n" +
	"\n" +
	"sender_uid\x18\x01 \x01(\rR\tsenderUid\x124\n" +
	"\x05group\x18\x02 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x03R\x04date\x12\x10\n" +
	"\x03rid\x18\x04 \x01(\x03R\x03rid\"o\n" +
	"\x11GroupUnpinRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12\x10\n" +
	"\x03rid\x18\x02 \x01(\x03R\x03rid\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x03R\x04date\"r\n" +
	"\x10GroupPinsRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\xa9\x01\n" +
	"\x12GroupPinnedMessage\x12\x1d\n" +
	"\n" +
	"sender_uid\x18\x01 \x01(\rR\tsenderUid\x12\x10\n" +
	"\x03rid\x18\x02 \x01(\x03R\x03rid\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x03R\x04date\x128\n" +
	"\amessage\x18\x04 \x01(\v2\x1e.gobale.bale.reference.MessageR\amessage\x12\x14\n" +
	"\x05state\x18\x05 \x01(\x05R\x05state\"h\n" +
	"\x11GroupPinsResponse\x12=\n" +
	"\x04pins\x18\x01 \x03(\v2).gobale.bale.reference.GroupPinnedMessageR\x04pins\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\x92\x01\n" +
	"\x0eGroupBanRecord\x12?\n" +
	"\vbanned_user\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\n" +
	"bannedUser\x12?\n" +
	"\vbanner_user\x18\x02 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\n" +
	"bannerUser\"_\n" +
	"\x13GroupBannedResponse\x12H\n" +
	"\fbanned_users\x18\x03 \x03(\v2%.gobale.bale.reference.GroupBanRecordR\vbannedUsers\"\x8f\x01\n" +
	"\x13GroupAdminsResponse\x124\n" +
	"\x05users\x18\x01 \x03(\v2\x1e.gobale.bale.reference.PeerRefR\x05users\x12B\n" +
	"\x06admins\x18\x02 \x03(\v2*.gobale.bale.reference.GroupExtendedMemberR\x06admins\"\xa5\x01\n" +
	"\x11GroupPhotoRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12H\n" +
	"\rfile_location\x18\x03 \x01(\v2#.gobale.bale.reference.FileLocationR\ffileLocation\x12\x10\n" +
	"\x03rid\x18\x04 \x01(\x03R\x03rid\"\xa1\x01\n" +
	"\x17GroupRemovePhotoRequest\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12\x10\n" +
	"\x03rid\x18\x04 \x01(\x03R\x03rid\x12>\n" +
	"\tavatar_id\x18\x06 \x01(\v2!.gobale.bale.reference.Int64ValueR\bavatarIdB8Z6github.com/mimalef70/gobale/src/internal/balemeow/wireb\x06proto3"

var (
	file_wire_groups_extended_proto_rawDescOnce sync.Once
	file_wire_groups_extended_proto_rawDescData []byte
)

func file_wire_groups_extended_proto_rawDescGZIP() []byte {
	file_wire_groups_extended_proto_rawDescOnce.Do(func() {
		file_wire_groups_extended_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_groups_extended_proto_rawDesc), len(file_wire_groups_extended_proto_rawDesc)))
	})
	return file_wire_groups_extended_proto_rawDescData
}

var file_wire_groups_extended_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_wire_groups_extended_proto_goTypes = []any{
	(*GroupPermissions)(nil),                  // 0: gobale.bale.reference.GroupPermissions
	(*GroupExtendedMember)(nil),               // 1: gobale.bale.reference.GroupExtendedMember
	(*GroupFullExtended)(nil),                 // 2: gobale.bale.reference.GroupFullExtended
	(*GroupFullExtendedResponse)(nil),         // 3: gobale.bale.reference.GroupFullExtendedResponse
	(*GroupCreateExtendedRequest)(nil),        // 4: gobale.bale.reference.GroupCreateExtendedRequest
	(*GroupAdminRequest)(nil),                 // 5: gobale.bale.reference.GroupAdminRequest
	(*GroupTransferRequest)(nil),              // 6: gobale.bale.reference.GroupTransferRequest
	(*GroupMemberPermissionsRequest)(nil),     // 7: gobale.bale.reference.GroupMemberPermissionsRequest
	(*GroupMemberPermissionsResponse)(nil),    // 8: gobale.bale.reference.GroupMemberPermissionsResponse
	(*GroupSetMemberPermissionsRequest)(nil),  // 9: gobale.bale.reference.GroupSetMemberPermissionsRequest
	(*GroupSetDefaultPermissionsRequest)(nil), // 10: gobale.bale.reference.GroupSetDefaultPermissionsRequest
	(*GroupJoinRequest)(nil),                  // 11: gobale.bale.reference.GroupJoinRequest
	(*GroupJoinPublicRequest)(nil),            // 12: gobale.bale.reference.GroupJoinPublicRequest
	(*GroupJoinResponse)(nil),                 // 13: gobale.bale.reference.GroupJoinResponse
	(*GroupLeaveRequest)(nil),                 // 14: gobale.bale.reference.GroupLeaveRequest
	(*GroupUsernameRequest)(nil),              // 15: gobale.bale.reference.GroupUsernameRequest
	(*GroupRestrictionRequest)(nil),           // 16: gobale.bale.reference.GroupRestrictionRequest
	(*GroupHistoryRequest)(nil),               // 17: gobale.bale.reference.GroupHistoryRequest
	(*GroupVisibilityRequest)(nil),            // 18: gobale.bale.reference.GroupVisibilityRequest
	(*GroupPinRequest)(nil),                   // 19: gobale.bale.reference.GroupPinRequest
	(*GroupUnpinRequest)(nil),                 // 20: gobale.bale.reference.GroupUnpinRequest
	(*GroupPinsRequest)(nil),                  // 21: gobale.bale.reference.GroupPinsRequest
	(*GroupPinnedMessage)(nil),                // 22: gobale.bale.reference.GroupPinnedMessage
	(*GroupPinsResponse)(nil),                 // 23: gobale.bale.reference.GroupPinsResponse
	(*GroupBanRecord)(nil),                    // 24: gobale.bale.reference.GroupBanRecord
	(*GroupBannedResponse)(nil),               // 25: gobale.bale.reference.GroupBannedResponse
	(*GroupAdminsResponse)(nil),               // 26: gobale.bale.reference.GroupAdminsResponse
	(*GroupPhotoRequest)(nil),                 // 27: gobale.bale.reference.GroupPhotoRequest
	(*GroupRemovePhotoRequest)(nil),           // 28: gobale.bale.reference.GroupRemovePhotoRequest
	(*BoolValue)(nil),                         // 29: gobale.bale.reference.BoolValue
	(*Int32Value)(nil),                        // 30: gobale.bale.reference.Int32Value
	(*Int64Value)(nil),                        // 31: gobale.bale.reference.Int64Value
	(*StringValue)(nil),                       // 32: gobale.bale.reference.StringValue
	(*PeerRef)(nil),                           // 33: gobale.bale.reference.PeerRef
	(*Peer)(nil),                              // 34: gobale.bale.reference.Peer
	(*Group)(nil),                             // 35: gobale.bale.reference.Group
	(*User)(nil),                              // 36: gobale.bale.reference.User
	(*Message)(nil),                           // 37: gobale.bale.reference.Message
	(*FileLocation)(nil),                      // 38: gobale.bale.reference.FileLocation
}
var file_wire_groups_extended_proto_depIdxs = []int32{
	29, // 0: gobale.bale.reference.GroupPermissions.send_media:type_name -> gobale.bale.reference.BoolValue
	29, // 1: gobale.bale.reference.GroupPermissions.send_gif_stickers:type_name -> gobale.bale.reference.BoolValue
	29, // 2: gobale.bale.reference.GroupPermissions.reply_to_story:type_name -> gobale.bale.reference.BoolValue
	29, // 3: gobale.bale.reference.GroupPermissions.forward_message_from:type_name -> gobale.bale.reference.BoolValue
	29, // 4: gobale.bale.reference.GroupPermissions.send_gift_packet:type_name -> gobale.bale.reference.BoolValue
	29, // 5: gobale.bale.reference.GroupPermissions.start_call:type_name -> gobale.bale.reference.BoolValue
	29, // 6: gobale.bale.reference.GroupPermissions.send_link_message:type_name -> gobale.bale.reference.BoolValue
	29, // 7: gobale.bale.reference.GroupPermissions.send_forwarded_message:type_name -> gobale.bale.reference.BoolValue
	29, // 8: gobale.bale.reference.GroupPermissions.add_story:type_name -> gobale.bale.reference.BoolValue
	29, // 9: gobale.bale.reference.GroupPermissions.manage_call:type_name -> gobale.bale.reference.BoolValue
	29, // 10: gobale.bale.reference.GroupExtendedMember.is_admin:type_name -> gobale.bale.reference.BoolValue
	30, // 11: gobale.bale.reference.GroupExtendedMember.promoter_user_id:type_name -> gobale.bale.reference.Int32Value
	31, // 12: gobale.bale.reference.GroupExtendedMember.promoted_at:type_name -> gobale.bale.reference.Int64Value
	0,  // 13: gobale.bale.reference.GroupExtendedMember.permissions:type_name -> gobale.bale.reference.GroupPermissions
	32, // 14: gobale.bale.reference.GroupExtendedMember.title:type_name -> gobale.bale.reference.StringValue
	29, // 15: gobale.bale.reference.GroupFullExtended.is_member:type_name -> gobale.bale.reference.BoolValue
	30, // 16: gobale.bale.reference.GroupFullExtended.members_count:type_name -> gobale.bale.reference.Int32Value
	32, // 17: gobale.bale.reference.GroupFullExtended.nick:type_name -> gobale.bale.reference.StringValue
	0,  // 18: gobale.bale.reference.GroupFullExtended.permissions:type_name -> gobale.bale.reference.GroupPermissions
	0,  // 19: gobale.bale.reference.GroupFullExtended.default_permissions:type_name -> gobale.bale.reference.GroupPermissions
	32, // 20: gobale.bale.reference.GroupFullExtended.about:type_name -> gobale.bale.reference.StringValue
	1,  // 21: gobale.bale.reference.GroupFullExtended.members:type_name -> gobale.bale.reference.GroupExtendedMember
	2,  // 22: gobale.bale.reference.GroupFullExtendedResponse.group:type_name -> gobale.bale.reference.GroupFullExtended
	33, // 23: gobale.bale.reference.GroupCreateExtendedRequest.users:type_name -> gobale.bale.reference.PeerRef
	32, // 24: gobale.bale.reference.GroupCreateExtendedRequest.nick:type_name -> gobale.bale.reference.StringValue
	33, // 25: gobale.bale.reference.GroupAdminRequest.group:type_name -> gobale.bale.reference.PeerRef
	33, // 26: gobale.bale.reference.GroupAdminRequest.user:type_name -> gobale.bale.reference.PeerRef
	32, // 27: gobale.bale.reference.GroupAdminRequest.admin_title:type_name -> gobale.bale.reference.StringValue
	33, // 28: gobale.bale.reference.GroupTransferRequest.group:type_name -> gobale.bale.reference.PeerRef
	33, // 29: gobale.bale.reference.GroupMemberPermissionsRequest.group:type_name -> gobale.bale.reference.PeerRef
	33, // 30: gobale.bale.reference.GroupMemberPermissionsRequest.user:type_name -> gobale.bale.reference.PeerRef
	0,  // 31: gobale.bale.reference.GroupMemberPermissionsResponse.permissions:type_name -> gobale.bale.reference.GroupPermissions
	33, // 32: gobale.bale.reference.GroupSetMemberPermissionsRequest.group:type_name -> gobale.bale.reference.PeerRef
	33, // 33: gobale.bale.reference.GroupSetMemberPermissionsRequest.user:type_name -> gobale.bale.reference.PeerRef
	0,  // 34: gobale.bale.reference.GroupSetMemberPermissionsRequest.permissions:type_name -> gobale.bale.reference.GroupPermissions
	33, // 35: gobale.bale.reference.GroupSetDefaultPermissionsRequest.group:type_name -> gobale.bale.reference.PeerRef
	0,  // 36: gobale.bale.reference.GroupSetDefaultPermissionsRequest.permissions:type_name -> gobale.bale.reference.GroupPermissions
	34, // 37: gobale.bale.reference.GroupJoinPublicRequest.peer:type_name -> gobale.bale.reference.Peer
	35, // 38: gobale.bale.reference.GroupJoinResponse.group:type_name -> gobale.bale.reference.Group
	36, // 39: gobale.bale.reference.GroupJoinResponse.users:type_name -> gobale.bale.reference.User
	33, // 40: gobale.bale.reference.GroupJoinResponse.user_peers:type_name -> gobale.bale.reference.PeerRef
	33, // 41: gobale.bale.reference.GroupLeaveRequest.group:type_name -> gobale.bale.reference.PeerRef
	29, // 42: gobale.bale.reference.GroupLeaveRequest.make_orphan:type_name -> gobale.bale.reference.BoolValue
	33, // 43: gobale.bale.reference.GroupUsernameRequest.group:type_name -> gobale.bale.reference.PeerRef
	33, // 44: gobale.bale.reference.GroupRestrictionRequest.group:type_name -> gobale.bale.reference.PeerRef
	32, // 45: gobale.bale.reference.GroupRestrictionRequest.nick:type_name -> gobale.bale.reference.StringValue
	33, // 46: gobale.bale.reference.GroupHistoryRequest.group:type_name -> gobale.bale.reference.PeerRef
	33, // 47: gobale.bale.reference.GroupVisibilityRequest.group:type_name -> gobale.bale.reference.PeerRef
	33, // 48: gobale.bale.reference.GroupPinRequest.group:type_name -> gobale.bale.reference.PeerRef
	33, // 49: gobale.bale.reference.GroupUnpinRequest.group:type_name -> gobale.bale.reference.PeerRef
	33, // 50: gobale.bale.reference.GroupPinsRequest.group:type_name -> gobale.bale.reference.PeerRef
	37, // 51: gobale.bale.reference.GroupPinnedMessage.message:type_name -> gobale.bale.reference.Message
	22, // 52: gobale.bale.reference.GroupPinsResponse.pins:type_name -> gobale.bale.reference.GroupPinnedMessage
	33, // 53: gobale.bale.reference.GroupBanRecord.banned_user:type_name -> gobale.bale.reference.PeerRef
	33, // 54: gobale.bale.reference.GroupBanRecord.banner_user:type_name -> gobale.bale.reference.PeerRef
	24, // 55: gobale.bale.reference.GroupBannedResponse.banned_users:type_name -> gobale.bale.reference.GroupBanRecord
	33, // 56: gobale.bale.reference.GroupAdminsResponse.users:type_name -> gobale.bale.reference.PeerRef
	1,  // 57: gobale.bale.reference.GroupAdminsResponse.admins:type_name -> gobale.bale.reference.GroupExtendedMember
	33, // 58: gobale.bale.reference.GroupPhotoRequest.group:type_name -> gobale.bale.reference.PeerRef
	38, // 59: gobale.bale.reference.GroupPhotoRequest.file_location:type_name -> gobale.bale.reference.FileLocation
	33, // 60: gobale.bale.reference.GroupRemovePhotoRequest.group:type_name -> gobale.bale.reference.PeerRef
	31, // 61: gobale.bale.reference.GroupRemovePhotoRequest.avatar_id:type_name -> gobale.bale.reference.Int64Value
	62, // [62:62] is the sub-list for method output_type
	62, // [62:62] is the sub-list for method input_type
	62, // [62:62] is the sub-list for extension type_name
	62, // [62:62] is the sub-list for extension extendee
	0,  // [0:62] is the sub-list for field type_name
}

func init() { file_wire_groups_extended_proto_init() }
func file_wire_groups_extended_proto_init() {
	if File_wire_groups_extended_proto != nil {
		return
	}
	file_wire_bale_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_groups_extended_proto_rawDesc), len(file_wire_groups_extended_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_groups_extended_proto_goTypes,
		DependencyIndexes: file_wire_groups_extended_proto_depIdxs,
		MessageInfos:      file_wire_groups_extended_proto_msgTypes,
	}.Build()
	File_wire_groups_extended_proto = out.File
	file_wire_groups_extended_proto_goTypes = nil
	file_wire_groups_extended_proto_depIdxs = nil
}
