// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: wire/messaging_extended.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reviewed official web 5.7.0+173855, modules 18913/77108/5594.
// Peer fields here named ex_peer use ExPeer semantics (channel=3), not legacy Peer.
type ChatPeerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *Peer                  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPeerRequest) Reset() {
	*x = ChatPeerRequest{}
	mi := &file_wire_messaging_extended_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPeerRequest) ProtoMessage() {}

func (x *ChatPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPeerRequest.ProtoReflect.Descriptor instead.
func (*ChatPeerRequest) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{0}
}

func (x *ChatPeerRequest) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

type ChatPinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExPeer        *Peer                  `protobuf:"bytes,1,opt,name=ex_peer,json=exPeer,proto3" json:"ex_peer,omitempty"`
	Message       *MessagePosition       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	JustMine      bool                   `protobuf:"varint,3,opt,name=just_mine,json=justMine,proto3" json:"just_mine,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPinRequest) Reset() {
	*x = ChatPinRequest{}
	mi := &file_wire_messaging_extended_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPinRequest) ProtoMessage() {}

func (x *ChatPinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPinRequest.ProtoReflect.Descriptor instead.
func (*ChatPinRequest) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{1}
}

func (x *ChatPinRequest) GetExPeer() *Peer {
	if x != nil {
		return x.ExPeer
	}
	return nil
}

func (x *ChatPinRequest) GetMessage() *MessagePosition {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatPinRequest) GetJustMine() bool {
	if x != nil {
		return x.JustMine
	}
	return false
}

type ChatUnpinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExPeer        *Peer                  `protobuf:"bytes,1,opt,name=ex_peer,json=exPeer,proto3" json:"ex_peer,omitempty"`
	Messages      []*MessagePosition     `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	All           bool                   `protobuf:"varint,3,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatUnpinRequest) Reset() {
	*x = ChatUnpinRequest{}
	mi := &file_wire_messaging_extended_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUnpinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUnpinRequest) ProtoMessage() {}

func (x *ChatUnpinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUnpinRequest.ProtoReflect.Descriptor instead.
func (*ChatUnpinRequest) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{2}
}

func (x *ChatUnpinRequest) GetExPeer() *Peer {
	if x != nil {
		return x.ExPeer
	}
	return nil
}

func (x *ChatUnpinRequest) GetMessages() []*MessagePosition {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatUnpinRequest) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type ChatPinsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*HistoryItem         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPinsResponse) Reset() {
	*x = ChatPinsResponse{}
	mi := &file_wire_messaging_extended_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPinsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPinsResponse) ProtoMessage() {}

func (x *ChatPinsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPinsResponse.ProtoReflect.Descriptor instead.
func (*ChatPinsResponse) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{3}
}

func (x *ChatPinsResponse) GetMessages() []*HistoryItem {
	if x != nil {
		return x.Messages
	}
	return nil
}

type FolderListRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	IncludeMutedUnreadPeers bool                   `protobuf:"varint,1,opt,name=include_muted_unread_peers,json=includeMutedUnreadPeers,proto3" json:"include_muted_unread_peers,omitempty"`
	IsNewUser               bool                   `protobuf:"varint,2,opt,name=is_new_user,json=isNewUser,proto3" json:"is_new_user,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *FolderListRequest) Reset() {
	*x = FolderListRequest{}
	mi := &file_wire_messaging_extended_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderListRequest) ProtoMessage() {}

func (x *FolderListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderListRequest.ProtoReflect.Descriptor instead.
func (*FolderListRequest) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{4}
}

func (x *FolderListRequest) GetIncludeMutedUnreadPeers() bool {
	if x != nil {
		return x.IncludeMutedUnreadPeers
	}
	return false
}

func (x *FolderListRequest) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

type ChatFolder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Peers         []*Peer                `protobuf:"bytes,3,rep,name=peers,proto3" json:"peers,omitempty"`
	UnreadPeers   []*Peer                `protobuf:"bytes,4,rep,name=unread_peers,json=unreadPeers,proto3" json:"unread_peers,omitempty"`
	IsReserved    bool                   `protobuf:"varint,5,opt,name=is_reserved,json=isReserved,proto3" json:"is_reserved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatFolder) Reset() {
	*x = ChatFolder{}
	mi := &file_wire_messaging_extended_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatFolder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatFolder) ProtoMessage() {}

func (x *ChatFolder) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatFolder.ProtoReflect.Descriptor instead.
func (*ChatFolder) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{5}
}

func (x *ChatFolder) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChatFolder) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChatFolder) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *ChatFolder) GetUnreadPeers() []*Peer {
	if x != nil {
		return x.UnreadPeers
	}
	return nil
}

func (x *ChatFolder) GetIsReserved() bool {
	if x != nil {
		return x.IsReserved
	}
	return false
}

type FolderUnreadPeer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Peer            *Peer                  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	LastMessageDate int64                  `protobuf:"varint,2,opt,name=last_message_date,json=lastMessageDate,proto3" json:"last_message_date,omitempty"`
	IsMuted         bool                   `protobuf:"varint,3,opt,name=is_muted,json=isMuted,proto3" json:"is_muted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FolderUnreadPeer) Reset() {
	*x = FolderUnreadPeer{}
	mi := &file_wire_messaging_extended_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderUnreadPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderUnreadPeer) ProtoMessage() {}

func (x *FolderUnreadPeer) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderUnreadPeer.ProtoReflect.Descriptor instead.
func (*FolderUnreadPeer) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{6}
}

func (x *FolderUnreadPeer) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *FolderUnreadPeer) GetLastMessageDate() int64 {
	if x != nil {
		return x.LastMessageDate
	}
	return 0
}

func (x *FolderUnreadPeer) GetIsMuted() bool {
	if x != nil {
		return x.IsMuted
	}
	return false
}

type FolderListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Folders       []*ChatFolder          `protobuf:"bytes,1,rep,name=folders,proto3" json:"folders,omitempty"`
	UnreadPeers   []*FolderUnreadPeer    `protobuf:"bytes,2,rep,name=unread_peers,json=unreadPeers,proto3" json:"unread_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderListResponse) Reset() {
	*x = FolderListResponse{}
	mi := &file_wire_messaging_extended_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderListResponse) ProtoMessage() {}

func (x *FolderListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderListResponse.ProtoReflect.Descriptor instead.
func (*FolderListResponse) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{7}
}

func (x *FolderListResponse) GetFolders() []*ChatFolder {
	if x != nil {
		return x.Folders
	}
	return nil
}

func (x *FolderListResponse) GetUnreadPeers() []*FolderUnreadPeer {
	if x != nil {
		return x.UnreadPeers
	}
	return nil
}

type FolderCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Peers         []*Peer                `protobuf:"bytes,2,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderCreateRequest) Reset() {
	*x = FolderCreateRequest{}
	mi := &file_wire_messaging_extended_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderCreateRequest) ProtoMessage() {}

func (x *FolderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderCreateRequest.ProtoReflect.Descriptor instead.
func (*FolderCreateRequest) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{8}
}

func (x *FolderCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FolderCreateRequest) GetPeers() []*Peer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type FolderCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      int32                  `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	UnreadPeers   []*Peer                `protobuf:"bytes,3,rep,name=unread_peers,json=unreadPeers,proto3" json:"unread_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderCreateResponse) Reset() {
	*x = FolderCreateResponse{}
	mi := &file_wire_messaging_extended_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderCreateResponse) ProtoMessage() {}

func (x *FolderCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderCreateResponse.ProtoReflect.Descriptor instead.
func (*FolderCreateResponse) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{9}
}

func (x *FolderCreateResponse) GetFolderId() int32 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

func (x *FolderCreateResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *FolderCreateResponse) GetUnreadPeers() []*Peer {
	if x != nil {
		return x.UnreadPeers
	}
	return nil
}

type FolderDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      int32                  `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderDeleteRequest) Reset() {
	*x = FolderDeleteRequest{}
	mi := &file_wire_messaging_extended_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderDeleteRequest) ProtoMessage() {}

func (x *FolderDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderDeleteRequest.ProtoReflect.Descriptor instead.
func (*FolderDeleteRequest) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{10}
}

func (x *FolderDeleteRequest) GetFolderId() int32 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

type FolderEditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FolderId      int32                  `protobuf:"varint,1,opt,name=folder_id,json=folderId,proto3" json:"folder_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AddedPeers    []*Peer                `protobuf:"bytes,3,rep,name=added_peers,json=addedPeers,proto3" json:"added_peers,omitempty"`
	DeletedPeers  []*Peer                `protobuf:"bytes,4,rep,name=deleted_peers,json=deletedPeers,proto3" json:"deleted_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderEditRequest) Reset() {
	*x = FolderEditRequest{}
	mi := &file_wire_messaging_extended_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderEditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderEditRequest) ProtoMessage() {}

func (x *FolderEditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderEditRequest.ProtoReflect.Descriptor instead.
func (*FolderEditRequest) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{11}
}

func (x *FolderEditRequest) GetFolderId() int32 {
	if x != nil {
		return x.FolderId
	}
	return 0
}

func (x *FolderEditRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FolderEditRequest) GetAddedPeers() []*Peer {
	if x != nil {
		return x.AddedPeers
	}
	return nil
}

func (x *FolderEditRequest) GetDeletedPeers() []*Peer {
	if x != nil {
		return x.DeletedPeers
	}
	return nil
}

type FolderEditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadPeers   []*Peer                `protobuf:"bytes,1,rep,name=unread_peers,json=unreadPeers,proto3" json:"unread_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FolderEditResponse) Reset() {
	*x = FolderEditResponse{}
	mi := &file_wire_messaging_extended_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FolderEditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FolderEditResponse) ProtoMessage() {}

func (x *FolderEditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_messaging_extended_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FolderEditResponse.ProtoReflect.Descriptor instead.
func (*FolderEditResponse) Descriptor() ([]byte, []int) {
	return file_wire_messaging_extended_proto_rawDescGZIP(), []int{12}
}

func (x *FolderEditResponse) GetUnreadPeers() []*Peer {
	if x != nil {
		return x.UnreadPeers
	}
	return nil
}

var File_wire_messaging_extended_proto protoreflect.FileDescriptor

const file_wire_messaging_extended_proto_rawDesc = "" +
	"\n" +
	"\x1dwire/messaging_extended.proto\x12\x15gobale.bale.reference\x1a\x0fwire/bale.proto\"B\n" +
	"\x0fChatPeerRequest\x12/\n" +
	"\x04peer\x18\x01 \x01(\v2\x1b.gobale.bale.reference.PeerR\x04peer\"\xa5\x01\n" +
	"\x0eChatPinRequest\x124\n" +
	"\aex_peer\x18\x01 \x01(\v2\x1b.gobale.bale.reference.PeerR\x06exPeer\x12@\n" +
	"\amessage\x18\x02 \x01(\v2&.gobale.bale.reference.MessagePositionR\amessage\x12\x1b\n" +
	"\tjust_mine\x18\x03 \x01(\bR\bjustMine\"\x9e\x01\n" +
	"\x10ChatUnpinRequest\x124\n" +
	"\aex_peer\x18\x01 \x01(\v2\x1b.gobale.bale.reference.PeerR\x06exPeer\x12B\n" +
	"\bmessages\x18\x02 \x03(\v2&.gobale.bale.reference.MessagePositionR\bmessages\x12\x10\n" +
	"\x03all\x18\x03 \x01(\bR\x03all\"R\n" +
	"\x10ChatPinsResponse\x12>\n" +
	"\bmessages\x18\x01 \x03(\v2\".gobale.bale.reference.HistoryItemR\bmessages\"p\n" +
	"\x11FolderListRequest\x12;\n" +
	"\x1ainclude_muted_unread_peers\x18\x01 \x01(\bR\x17includeMutedUnreadPeers\x12\x1e\n" +
	"\vis_new_user\x18\x02 \x01(\bR\tisNewUser\"\xc4\x01\n" +
	"\n" +
	"ChatFolder\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x121\n" +
	"\x05peers\x18\x03 \x03(\v2\x1b.gobale.bale.reference.PeerR\x05peers\x12>\n" +
	"\funread_peers\x18\x04 \x03(\v2\x1b.gobale.bale.reference.PeerR\vunreadPeers\x12\x1f\n" +
	"\vis_reserved\x18\x05 \x01(\bR\n" +
	"isReserved\"\x8a\x01\n" +
	"\x10FolderUnreadPeer\x12/\n" +
	"\x04peer\x18\x01 \x01(\v2\x1b.gobale.bale.reference.PeerR\x04peer\x12*\n" +
	"\x11last_message_date\x18\x02 \x01(\x03R\x0flastMessageDate\x12\x19\n" +
	"\bis_muted\x18\x03 \x01(\bR\aisMuted\"\x9d\x01\n" +
	"\x12FolderListResponse\x12;\n" +
	"\afolders\x18\x01 \x03(\v2!.gobale.bale.reference.ChatFolderR\afolders\x12J\n" +
	"\funread_peers\x18\x02 \x03(\v2'.gobale.bale.reference.FolderUnreadPeerR\vunreadPeers\"\\\n" +
	"\x13FolderCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x05peers\x18\x02 \x03(\v2\x1b.gobale.bale.reference.PeerR\x05peers\"\x89\x01\n" +
	"\x14FolderCreateResponse\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\x05R\bfolderId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12>\n" +
	"\funread_peers\x18\x03 \x03(\v2\x1b.gobale.bale.reference.PeerR\vunreadPeers\"2\n" +
	"\x13FolderDeleteRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\x05R\bfolderId\"\xc4\x01\n" +
	"\x11FolderEditRequest\x12\x1b\n" +
	"\tfolder_id\x18\x01 \x01(\x05R\bfolderId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12<\n" +
	"\vadded_peers\x18\x03 \x03(\v2\x1b.gobale.bale.reference.PeerR\n" +
	"addedPeers\x12@\n" +
	"\rdeleted_peers\x18\x04 \x03(\v2\x1b.gobale.bale.reference.PeerR\fdeletedPeers\"T\n" +
	"\x12FolderEditResponse\x12>\n" +
	"\funread_peers\x18\x01 \x03(\v2\x1b.gobale.bale.reference.PeerR\vunreadPeersB8Z6github.com/mimalef70/goomni/src/internal/balemeow/wireb\x06proto3"

var (
	file_wire_messaging_extended_proto_rawDescOnce sync.Once
	file_wire_messaging_extended_proto_rawDescData []byte
)

func file_wire_messaging_extended_proto_rawDescGZIP() []byte {
	file_wire_messaging_extended_proto_rawDescOnce.Do(func() {
		file_wire_messaging_extended_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_messaging_extended_proto_rawDesc), len(file_wire_messaging_extended_proto_rawDesc)))
	})
	return file_wire_messaging_extended_proto_rawDescData
}

var file_wire_messaging_extended_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_wire_messaging_extended_proto_goTypes = []any{
	(*ChatPeerRequest)(nil),      // 0: gobale.bale.reference.ChatPeerRequest
	(*ChatPinRequest)(nil),       // 1: gobale.bale.reference.ChatPinRequest
	(*ChatUnpinRequest)(nil),     // 2: gobale.bale.reference.ChatUnpinRequest
	(*ChatPinsResponse)(nil),     // 3: gobale.bale.reference.ChatPinsResponse
	(*FolderListRequest)(nil),    // 4: gobale.bale.reference.FolderListRequest
	(*ChatFolder)(nil),           // 5: gobale.bale.reference.ChatFolder
	(*FolderUnreadPeer)(nil),     // 6: gobale.bale.reference.FolderUnreadPeer
	(*FolderListResponse)(nil),   // 7: gobale.bale.reference.FolderListResponse
	(*FolderCreateRequest)(nil),  // 8: gobale.bale.reference.FolderCreateRequest
	(*FolderCreateResponse)(nil), // 9: gobale.bale.reference.FolderCreateResponse
	(*FolderDeleteRequest)(nil),  // 10: gobale.bale.reference.FolderDeleteRequest
	(*FolderEditRequest)(nil),    // 11: gobale.bale.reference.FolderEditRequest
	(*FolderEditResponse)(nil),   // 12: gobale.bale.reference.FolderEditResponse
	(*Peer)(nil),                 // 13: gobale.bale.reference.Peer
	(*MessagePosition)(nil),      // 14: gobale.bale.reference.MessagePosition
	(*HistoryItem)(nil),          // 15: gobale.bale.reference.HistoryItem
}
var file_wire_messaging_extended_proto_depIdxs = []int32{
	13, // 0: gobale.bale.reference.ChatPeerRequest.peer:type_name -> gobale.bale.reference.Peer
	13, // 1: gobale.bale.reference.ChatPinRequest.ex_peer:type_name -> gobale.bale.reference.Peer
	14, // 2: gobale.bale.reference.ChatPinRequest.message:type_name -> gobale.bale.reference.MessagePosition
	13, // 3: gobale.bale.reference.ChatUnpinRequest.ex_peer:type_name -> gobale.bale.reference.Peer
	14, // 4: gobale.bale.reference.ChatUnpinRequest.messages:type_name -> gobale.bale.reference.MessagePosition
	15, // 5: gobale.bale.reference.ChatPinsResponse.messages:type_name -> gobale.bale.reference.HistoryItem
	13, // 6: gobale.bale.reference.ChatFolder.peers:type_name -> gobale.bale.reference.Peer
	13, // 7: gobale.bale.reference.ChatFolder.unread_peers:type_name -> gobale.bale.reference.Peer
	13, // 8: gobale.bale.reference.FolderUnreadPeer.peer:type_name -> gobale.bale.reference.Peer
	5,  // 9: gobale.bale.reference.FolderListResponse.folders:type_name -> gobale.bale.reference.ChatFolder
	6,  // 10: gobale.bale.reference.FolderListResponse.unread_peers:type_name -> gobale.bale.reference.FolderUnreadPeer
	13, // 11: gobale.bale.reference.FolderCreateRequest.peers:type_name -> gobale.bale.reference.Peer
	13, // 12: gobale.bale.reference.FolderCreateResponse.unread_peers:type_name -> gobale.bale.reference.Peer
	13, // 13: gobale.bale.reference.FolderEditRequest.added_peers:type_name -> gobale.bale.reference.Peer
	13, // 14: gobale.bale.reference.FolderEditRequest.deleted_peers:type_name -> gobale.bale.reference.Peer
	13, // 15: gobale.bale.reference.FolderEditResponse.unread_peers:type_name -> gobale.bale.reference.Peer
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_wire_messaging_extended_proto_init() }
func file_wire_messaging_extended_proto_init() {
	if File_wire_messaging_extended_proto != nil {
		return
	}
	file_wire_bale_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_messaging_extended_proto_rawDesc), len(file_wire_messaging_extended_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_messaging_extended_proto_goTypes,
		DependencyIndexes: file_wire_messaging_extended_proto_depIdxs,
		MessageInfos:      file_wire_messaging_extended_proto_msgTypes,
	}.Build()
	File_wire_messaging_extended_proto = out.File
	file_wire_messaging_extended_proto_goTypes = nil
	file_wire_messaging_extended_proto_depIdxs = nil
}
