// Reviewed against Bale Web 5.7.0 MainRoutes.7a95f5bcef.js and index module 51794.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: wire/polls_extended.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PollCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollMessage   *PollMessage           `protobuf:"bytes,1,opt,name=poll_message,json=pollMessage,proto3" json:"poll_message,omitempty"`
	CreateAt      int64                  `protobuf:"varint,2,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	ExPeer        *Peer                  `protobuf:"bytes,3,opt,name=ex_peer,json=exPeer,proto3" json:"ex_peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollCreateRequest) Reset() {
	*x = PollCreateRequest{}
	mi := &file_wire_polls_extended_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollCreateRequest) ProtoMessage() {}

func (x *PollCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_polls_extended_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollCreateRequest.ProtoReflect.Descriptor instead.
func (*PollCreateRequest) Descriptor() ([]byte, []int) {
	return file_wire_polls_extended_proto_rawDescGZIP(), []int{0}
}

func (x *PollCreateRequest) GetPollMessage() *PollMessage {
	if x != nil {
		return x.PollMessage
	}
	return nil
}

func (x *PollCreateRequest) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *PollCreateRequest) GetExPeer() *Peer {
	if x != nil {
		return x.ExPeer
	}
	return nil
}

type PollCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        int64                  `protobuf:"varint,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollCreateResponse) Reset() {
	*x = PollCreateResponse{}
	mi := &file_wire_polls_extended_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollCreateResponse) ProtoMessage() {}

func (x *PollCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_polls_extended_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollCreateResponse.ProtoReflect.Descriptor instead.
func (*PollCreateResponse) Descriptor() ([]byte, []int) {
	return file_wire_polls_extended_proto_rawDescGZIP(), []int{1}
}

func (x *PollCreateResponse) GetPollId() int64 {
	if x != nil {
		return x.PollId
	}
	return 0
}

type PollVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        int64                  `protobuf:"varint,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	IsRetract     bool                   `protobuf:"varint,2,opt,name=is_retract,json=isRetract,proto3" json:"is_retract,omitempty"`
	VoteAt        int64                  `protobuf:"varint,3,opt,name=vote_at,json=voteAt,proto3" json:"vote_at,omitempty"`
	OptionIds     []int32                `protobuf:"varint,4,rep,packed,name=option_ids,json=optionIds,proto3" json:"option_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollVoteRequest) Reset() {
	*x = PollVoteRequest{}
	mi := &file_wire_polls_extended_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollVoteRequest) ProtoMessage() {}

func (x *PollVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_polls_extended_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollVoteRequest.ProtoReflect.Descriptor instead.
func (*PollVoteRequest) Descriptor() ([]byte, []int) {
	return file_wire_polls_extended_proto_rawDescGZIP(), []int{2}
}

func (x *PollVoteRequest) GetPollId() int64 {
	if x != nil {
		return x.PollId
	}
	return 0
}

func (x *PollVoteRequest) GetIsRetract() bool {
	if x != nil {
		return x.IsRetract
	}
	return false
}

func (x *PollVoteRequest) GetVoteAt() int64 {
	if x != nil {
		return x.VoteAt
	}
	return 0
}

func (x *PollVoteRequest) GetOptionIds() []int32 {
	if x != nil {
		return x.OptionIds
	}
	return nil
}

type PollVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollResult    *PollResult            `protobuf:"bytes,1,opt,name=poll_result,json=pollResult,proto3" json:"poll_result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollVoteResponse) Reset() {
	*x = PollVoteResponse{}
	mi := &file_wire_polls_extended_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollVoteResponse) ProtoMessage() {}

func (x *PollVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_polls_extended_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollVoteResponse.ProtoReflect.Descriptor instead.
func (*PollVoteResponse) Descriptor() ([]byte, []int) {
	return file_wire_polls_extended_proto_rawDescGZIP(), []int{3}
}

func (x *PollVoteResponse) GetPollResult() *PollResult {
	if x != nil {
		return x.PollResult
	}
	return nil
}

type PollResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollIds       []int64                `protobuf:"varint,1,rep,name=poll_ids,json=pollIds,proto3" json:"poll_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResultsRequest) Reset() {
	*x = PollResultsRequest{}
	mi := &file_wire_polls_extended_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResultsRequest) ProtoMessage() {}

func (x *PollResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_polls_extended_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResultsRequest.ProtoReflect.Descriptor instead.
func (*PollResultsRequest) Descriptor() ([]byte, []int) {
	return file_wire_polls_extended_proto_rawDescGZIP(), []int{4}
}

func (x *PollResultsRequest) GetPollIds() []int64 {
	if x != nil {
		return x.PollIds
	}
	return nil
}

type PollResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollResults   []*PollResult          `protobuf:"bytes,1,rep,name=poll_results,json=pollResults,proto3" json:"poll_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollResultsResponse) Reset() {
	*x = PollResultsResponse{}
	mi := &file_wire_polls_extended_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollResultsResponse) ProtoMessage() {}

func (x *PollResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_polls_extended_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollResultsResponse.ProtoReflect.Descriptor instead.
func (*PollResultsResponse) Descriptor() ([]byte, []int) {
	return file_wire_polls_extended_proto_rawDescGZIP(), []int{5}
}

func (x *PollResultsResponse) GetPollResults() []*PollResult {
	if x != nil {
		return x.PollResults
	}
	return nil
}

type PollIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PollId        int64                  `protobuf:"varint,1,opt,name=poll_id,json=pollId,proto3" json:"poll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollIDRequest) Reset() {
	*x = PollIDRequest{}
	mi := &file_wire_polls_extended_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollIDRequest) ProtoMessage() {}

func (x *PollIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_polls_extended_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollIDRequest.ProtoReflect.Descriptor instead.
func (*PollIDRequest) Descriptor() ([]byte, []int) {
	return file_wire_polls_extended_proto_rawDescGZIP(), []int{6}
}

func (x *PollIDRequest) GetPollId() int64 {
	if x != nil {
		return x.PollId
	}
	return 0
}

type PollVoter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	VotedAt       int64                  `protobuf:"varint,2,opt,name=voted_at,json=votedAt,proto3" json:"voted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollVoter) Reset() {
	*x = PollVoter{}
	mi := &file_wire_polls_extended_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollVoter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollVoter) ProtoMessage() {}

func (x *PollVoter) ProtoReflect() protoreflect.Message {
	mi := &file_wire_polls_extended_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollVoter.ProtoReflect.Descriptor instead.
func (*PollVoter) Descriptor() ([]byte, []int) {
	return file_wire_polls_extended_proto_rawDescGZIP(), []int{7}
}

func (x *PollVoter) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PollVoter) GetVotedAt() int64 {
	if x != nil {
		return x.VotedAt
	}
	return 0
}

type PollFullOptionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionId      int32                  `protobuf:"varint,1,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	VotesCount    int32                  `protobuf:"varint,2,opt,name=votes_count,json=votesCount,proto3" json:"votes_count,omitempty"`
	Voters        []*PollVoter           `protobuf:"bytes,3,rep,name=voters,proto3" json:"voters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollFullOptionResult) Reset() {
	*x = PollFullOptionResult{}
	mi := &file_wire_polls_extended_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollFullOptionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollFullOptionResult) ProtoMessage() {}

func (x *PollFullOptionResult) ProtoReflect() protoreflect.Message {
	mi := &file_wire_polls_extended_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollFullOptionResult.ProtoReflect.Descriptor instead.
func (*PollFullOptionResult) Descriptor() ([]byte, []int) {
	return file_wire_polls_extended_proto_rawDescGZIP(), []int{8}
}

func (x *PollFullOptionResult) GetOptionId() int32 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

func (x *PollFullOptionResult) GetVotesCount() int32 {
	if x != nil {
		return x.VotesCount
	}
	return 0
}

func (x *PollFullOptionResult) GetVoters() []*PollVoter {
	if x != nil {
		return x.Voters
	}
	return nil
}

type PollFullResultsResponse struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	FullPollResult []*PollFullOptionResult `protobuf:"bytes,1,rep,name=full_poll_result,json=fullPollResult,proto3" json:"full_poll_result,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PollFullResultsResponse) Reset() {
	*x = PollFullResultsResponse{}
	mi := &file_wire_polls_extended_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollFullResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollFullResultsResponse) ProtoMessage() {}

func (x *PollFullResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_polls_extended_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollFullResultsResponse.ProtoReflect.Descriptor instead.
func (*PollFullResultsResponse) Descriptor() ([]byte, []int) {
	return file_wire_polls_extended_proto_rawDescGZIP(), []int{9}
}

func (x *PollFullResultsResponse) GetFullPollResult() []*PollFullOptionResult {
	if x != nil {
		return x.FullPollResult
	}
	return nil
}

var File_wire_polls_extended_proto protoreflect.FileDescriptor

const file_wire_polls_extended_proto_rawDesc = "" +
	"\n" +
	"\x19wire/polls_extended.proto\x12\x15gobale.bale.reference\x1a\x0fwire/bale.proto\"\xad\x01\n" +
	"\x11PollCreateRequest\x12E\n" +
	"\fpoll_message\x18\x01 \x01(\v2\".gobale.bale.reference.PollMessageR\vpollMessage\x12\x1b\n" +
	"\tcreate_at\x18\x02 \x01(\x03R\bcreateAt\x124\n" +
	"\aex_peer\x18\x03 \x01(\v2\x1b.gobale.bale.reference.PeerR\x06exPeer\"-\n" +
	"\x12PollCreateResponse\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\x03R\x06pollId\"\x81\x01\n" +
	"\x0fPollVoteRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\x03R\x06pollId\x12\x1d\n" +
	"\n" +
	"is_retract\x18\x02 \x01(\bR\tisRetract\x12\x17\n" +
	"\avote_at\x18\x03 \x01(\x03R\x06voteAt\x12\x1d\n" +
	"\n" +
	"option_ids\x18\x04 \x03(\x05R\toptionIds\"V\n" +
	"\x10PollVoteResponse\x12B\n" +
	"\vpoll_result\x18\x01 \x01(\v2!.gobale.bale.reference.PollResultR\n" +
	"pollResult\"3\n" +
	"\x12PollResultsRequest\x12\x1d\n" +
	"\bpoll_ids\x18\x01 \x03(\x03B\x02\x10\x00R\apollIds\"[\n" +
	"\x13PollResultsResponse\x12D\n" +
	"\fpoll_results\x18\x01 \x03(\v2!.gobale.bale.reference.PollResultR\vpollResults\"(\n" +
	"\rPollIDRequest\x12\x17\n" +
	"\apoll_id\x18\x01 \x01(\x03R\x06pollId\"?\n" +
	"\tPollVoter\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x19\n" +
	"\bvoted_at\x18\x02 \x01(\x03R\avotedAt\"\x8e\x01\n" +
	"\x14PollFullOptionResult\x12\x1b\n" +
	"\toption_id\x18\x01 \x01(\x05R\boptionId\x12\x1f\n" +
	"\vvotes_count\x18\x02 \x01(\x05R\n" +
	"votesCount\x128\n" +
	"\x06voters\x18\x03 \x03(\v2 .gobale.bale.reference.PollVoterR\x06voters\"p\n" +
	"\x17PollFullResultsResponse\x12U\n" +
	"\x10full_poll_result\x18\x01 \x03(\v2+.gobale.bale.reference.PollFullOptionResultR\x0efullPollResultB8Z6github.com/mimalef70/goomni/src/internal/balemeow/wireb\x06proto3"

var (
	file_wire_polls_extended_proto_rawDescOnce sync.Once
	file_wire_polls_extended_proto_rawDescData []byte
)

func file_wire_polls_extended_proto_rawDescGZIP() []byte {
	file_wire_polls_extended_proto_rawDescOnce.Do(func() {
		file_wire_polls_extended_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_polls_extended_proto_rawDesc), len(file_wire_polls_extended_proto_rawDesc)))
	})
	return file_wire_polls_extended_proto_rawDescData
}

var file_wire_polls_extended_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_wire_polls_extended_proto_goTypes = []any{
	(*PollCreateRequest)(nil),       // 0: gobale.bale.reference.PollCreateRequest
	(*PollCreateResponse)(nil),      // 1: gobale.bale.reference.PollCreateResponse
	(*PollVoteRequest)(nil),         // 2: gobale.bale.reference.PollVoteRequest
	(*PollVoteResponse)(nil),        // 3: gobale.bale.reference.PollVoteResponse
	(*PollResultsRequest)(nil),      // 4: gobale.bale.reference.PollResultsRequest
	(*PollResultsResponse)(nil),     // 5: gobale.bale.reference.PollResultsResponse
	(*PollIDRequest)(nil),           // 6: gobale.bale.reference.PollIDRequest
	(*PollVoter)(nil),               // 7: gobale.bale.reference.PollVoter
	(*PollFullOptionResult)(nil),    // 8: gobale.bale.reference.PollFullOptionResult
	(*PollFullResultsResponse)(nil), // 9: gobale.bale.reference.PollFullResultsResponse
	(*PollMessage)(nil),             // 10: gobale.bale.reference.PollMessage
	(*Peer)(nil),                    // 11: gobale.bale.reference.Peer
	(*PollResult)(nil),              // 12: gobale.bale.reference.PollResult
}
var file_wire_polls_extended_proto_depIdxs = []int32{
	10, // 0: gobale.bale.reference.PollCreateRequest.poll_message:type_name -> gobale.bale.reference.PollMessage
	11, // 1: gobale.bale.reference.PollCreateRequest.ex_peer:type_name -> gobale.bale.reference.Peer
	12, // 2: gobale.bale.reference.PollVoteResponse.poll_result:type_name -> gobale.bale.reference.PollResult
	12, // 3: gobale.bale.reference.PollResultsResponse.poll_results:type_name -> gobale.bale.reference.PollResult
	7,  // 4: gobale.bale.reference.PollFullOptionResult.voters:type_name -> gobale.bale.reference.PollVoter
	8,  // 5: gobale.bale.reference.PollFullResultsResponse.full_poll_result:type_name -> gobale.bale.reference.PollFullOptionResult
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_wire_polls_extended_proto_init() }
func file_wire_polls_extended_proto_init() {
	if File_wire_polls_extended_proto != nil {
		return
	}
	file_wire_bale_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_polls_extended_proto_rawDesc), len(file_wire_polls_extended_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_polls_extended_proto_goTypes,
		DependencyIndexes: file_wire_polls_extended_proto_depIdxs,
		MessageInfos:      file_wire_polls_extended_proto_msgTypes,
	}.Build()
	File_wire_polls_extended_proto = out.File
	file_wire_polls_extended_proto_goTypes = nil
	file_wire_polls_extended_proto_depIdxs = nil
}
