// Receive-only extended updates, reviewed from official web 173855.
// Separate union view avoids circular imports with optional RPC feature schemas.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: wire/receive.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupUpdateUnion struct {
	state              protoimpl.MessageState        `protogen:"open.v1"`
	Restriction        *GroupNumberUpdate            `protobuf:"bytes,723,opt,name=restriction,proto3" json:"restriction,omitempty"`
	Title              *GroupStringUpdate            `protobuf:"bytes,2609,opt,name=title,proto3" json:"title,omitempty"`
	Avatar             *GroupIDUpdate                `protobuf:"bytes,2610,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Member             *GroupBoolUpdate              `protobuf:"bytes,2612,opt,name=member,proto3" json:"member,omitempty"`
	Members            *GroupMembersUpdate           `protobuf:"bytes,2614,opt,name=members,proto3" json:"members,omitempty"`
	AsyncMembers       *GroupIDUpdate                `protobuf:"bytes,2615,opt,name=async_members,json=asyncMembers,proto3" json:"async_members,omitempty"`
	Topic              *GroupTextUpdate              `protobuf:"bytes,2616,opt,name=topic,proto3" json:"topic,omitempty"`
	About              *GroupTextUpdate              `protobuf:"bytes,2617,opt,name=about,proto3" json:"about,omitempty"`
	Owner              *GroupOwnerUpdate             `protobuf:"bytes,2619,opt,name=owner,proto3" json:"owner,omitempty"`
	HistoryShared      *GroupIDUpdate                `protobuf:"bytes,2620,opt,name=history_shared,json=historyShared,proto3" json:"history_shared,omitempty"`
	Count              *GroupNumberUpdate            `protobuf:"bytes,2622,opt,name=count,proto3" json:"count,omitempty"`
	CanSend            *GroupBoolUpdate              `protobuf:"bytes,2624,opt,name=can_send,json=canSend,proto3" json:"can_send,omitempty"`
	CanViewMembers     *GroupBoolUpdate              `protobuf:"bytes,2625,opt,name=can_view_members,json=canViewMembers,proto3" json:"can_view_members,omitempty"`
	CanInvite          *GroupBoolUpdate              `protobuf:"bytes,2626,opt,name=can_invite,json=canInvite,proto3" json:"can_invite,omitempty"`
	Admin              *GroupAdminUpdate             `protobuf:"bytes,2627,opt,name=admin,proto3" json:"admin,omitempty"`
	Orphaned           *GroupIDUpdate                `protobuf:"bytes,2628,opt,name=orphaned,proto3" json:"orphaned,omitempty"`
	Username           *GroupStringUpdate            `protobuf:"bytes,2880,opt,name=username,proto3" json:"username,omitempty"`
	MemberPermissions  *GroupMemberPermissionUpdate  `protobuf:"bytes,52804,opt,name=member_permissions,json=memberPermissions,proto3" json:"member_permissions,omitempty"`
	DefaultPermissions *GroupDefaultPermissionUpdate `protobuf:"bytes,52805,opt,name=default_permissions,json=defaultPermissions,proto3" json:"default_permissions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GroupUpdateUnion) Reset() {
	*x = GroupUpdateUnion{}
	mi := &file_wire_receive_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUpdateUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUpdateUnion) ProtoMessage() {}

func (x *GroupUpdateUnion) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUpdateUnion.ProtoReflect.Descriptor instead.
func (*GroupUpdateUnion) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{0}
}

func (x *GroupUpdateUnion) GetRestriction() *GroupNumberUpdate {
	if x != nil {
		return x.Restriction
	}
	return nil
}

func (x *GroupUpdateUnion) GetTitle() *GroupStringUpdate {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *GroupUpdateUnion) GetAvatar() *GroupIDUpdate {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *GroupUpdateUnion) GetMember() *GroupBoolUpdate {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *GroupUpdateUnion) GetMembers() *GroupMembersUpdate {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *GroupUpdateUnion) GetAsyncMembers() *GroupIDUpdate {
	if x != nil {
		return x.AsyncMembers
	}
	return nil
}

func (x *GroupUpdateUnion) GetTopic() *GroupTextUpdate {
	if x != nil {
		return x.Topic
	}
	return nil
}

func (x *GroupUpdateUnion) GetAbout() *GroupTextUpdate {
	if x != nil {
		return x.About
	}
	return nil
}

func (x *GroupUpdateUnion) GetOwner() *GroupOwnerUpdate {
	if x != nil {
		return x.Owner
	}
	return nil
}

func (x *GroupUpdateUnion) GetHistoryShared() *GroupIDUpdate {
	if x != nil {
		return x.HistoryShared
	}
	return nil
}

func (x *GroupUpdateUnion) GetCount() *GroupNumberUpdate {
	if x != nil {
		return x.Count
	}
	return nil
}

func (x *GroupUpdateUnion) GetCanSend() *GroupBoolUpdate {
	if x != nil {
		return x.CanSend
	}
	return nil
}

func (x *GroupUpdateUnion) GetCanViewMembers() *GroupBoolUpdate {
	if x != nil {
		return x.CanViewMembers
	}
	return nil
}

func (x *GroupUpdateUnion) GetCanInvite() *GroupBoolUpdate {
	if x != nil {
		return x.CanInvite
	}
	return nil
}

func (x *GroupUpdateUnion) GetAdmin() *GroupAdminUpdate {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *GroupUpdateUnion) GetOrphaned() *GroupIDUpdate {
	if x != nil {
		return x.Orphaned
	}
	return nil
}

func (x *GroupUpdateUnion) GetUsername() *GroupStringUpdate {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *GroupUpdateUnion) GetMemberPermissions() *GroupMemberPermissionUpdate {
	if x != nil {
		return x.MemberPermissions
	}
	return nil
}

func (x *GroupUpdateUnion) GetDefaultPermissions() *GroupDefaultPermissionUpdate {
	if x != nil {
		return x.DefaultPermissions
	}
	return nil
}

type GroupIDUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint32                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupIDUpdate) Reset() {
	*x = GroupIDUpdate{}
	mi := &file_wire_receive_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupIDUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupIDUpdate) ProtoMessage() {}

func (x *GroupIDUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupIDUpdate.ProtoReflect.Descriptor instead.
func (*GroupIDUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{1}
}

func (x *GroupIDUpdate) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type GroupStringUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint32                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupStringUpdate) Reset() {
	*x = GroupStringUpdate{}
	mi := &file_wire_receive_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupStringUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupStringUpdate) ProtoMessage() {}

func (x *GroupStringUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupStringUpdate.ProtoReflect.Descriptor instead.
func (*GroupStringUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{2}
}

func (x *GroupStringUpdate) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupStringUpdate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GroupTextUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint32                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Value         *StringValue           `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupTextUpdate) Reset() {
	*x = GroupTextUpdate{}
	mi := &file_wire_receive_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupTextUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTextUpdate) ProtoMessage() {}

func (x *GroupTextUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTextUpdate.ProtoReflect.Descriptor instead.
func (*GroupTextUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{3}
}

func (x *GroupTextUpdate) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupTextUpdate) GetValue() *StringValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type GroupNumberUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint32                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupNumberUpdate) Reset() {
	*x = GroupNumberUpdate{}
	mi := &file_wire_receive_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupNumberUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupNumberUpdate) ProtoMessage() {}

func (x *GroupNumberUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupNumberUpdate.ProtoReflect.Descriptor instead.
func (*GroupNumberUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{4}
}

func (x *GroupNumberUpdate) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupNumberUpdate) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type GroupBoolUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint32                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Value         bool                   `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupBoolUpdate) Reset() {
	*x = GroupBoolUpdate{}
	mi := &file_wire_receive_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupBoolUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupBoolUpdate) ProtoMessage() {}

func (x *GroupBoolUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupBoolUpdate.ProtoReflect.Descriptor instead.
func (*GroupBoolUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{5}
}

func (x *GroupBoolUpdate) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupBoolUpdate) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type GroupOwnerUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint32                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupOwnerUpdate) Reset() {
	*x = GroupOwnerUpdate{}
	mi := &file_wire_receive_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupOwnerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupOwnerUpdate) ProtoMessage() {}

func (x *GroupOwnerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupOwnerUpdate.ProtoReflect.Descriptor instead.
func (*GroupOwnerUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{6}
}

func (x *GroupOwnerUpdate) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupOwnerUpdate) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GroupAdminUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint32                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IsAdmin       bool                   `protobuf:"varint,3,opt,name=is_admin,json=isAdmin,proto3" json:"is_admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAdminUpdate) Reset() {
	*x = GroupAdminUpdate{}
	mi := &file_wire_receive_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAdminUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAdminUpdate) ProtoMessage() {}

func (x *GroupAdminUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAdminUpdate.ProtoReflect.Descriptor instead.
func (*GroupAdminUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{7}
}

func (x *GroupAdminUpdate) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupAdminUpdate) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupAdminUpdate) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

type GroupMembersUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint32                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Members       []*GroupExtendedMember `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMembersUpdate) Reset() {
	*x = GroupMembersUpdate{}
	mi := &file_wire_receive_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMembersUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMembersUpdate) ProtoMessage() {}

func (x *GroupMembersUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMembersUpdate.ProtoReflect.Descriptor instead.
func (*GroupMembersUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{8}
}

func (x *GroupMembersUpdate) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMembersUpdate) GetMembers() []*GroupExtendedMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type GroupMemberPermissionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint32                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Permissions   *GroupPermissions      `protobuf:"bytes,3,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMemberPermissionUpdate) Reset() {
	*x = GroupMemberPermissionUpdate{}
	mi := &file_wire_receive_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMemberPermissionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMemberPermissionUpdate) ProtoMessage() {}

func (x *GroupMemberPermissionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMemberPermissionUpdate.ProtoReflect.Descriptor instead.
func (*GroupMemberPermissionUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{9}
}

func (x *GroupMemberPermissionUpdate) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GroupMemberPermissionUpdate) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMemberPermissionUpdate) GetPermissions() *GroupPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type GroupDefaultPermissionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *PeerRef               `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Permissions   *GroupPermissions      `protobuf:"bytes,2,opt,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupDefaultPermissionUpdate) Reset() {
	*x = GroupDefaultPermissionUpdate{}
	mi := &file_wire_receive_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupDefaultPermissionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupDefaultPermissionUpdate) ProtoMessage() {}

func (x *GroupDefaultPermissionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupDefaultPermissionUpdate.ProtoReflect.Descriptor instead.
func (*GroupDefaultPermissionUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{10}
}

func (x *GroupDefaultPermissionUpdate) GetGroup() *PeerRef {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupDefaultPermissionUpdate) GetPermissions() *GroupPermissions {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type PresenceUpdateUnion struct {
	state             protoimpl.MessageState  `protogen:"open.v1"`
	Typing            *TypingUpdate           `protobuf:"bytes,6,opt,name=typing,proto3" json:"typing,omitempty"`
	TypingStop        *TypingUpdate           `protobuf:"bytes,81,opt,name=typing_stop,json=typingStop,proto3" json:"typing_stop,omitempty"`
	Online            *PresenceStateUpdate    `protobuf:"bytes,7,opt,name=online,proto3" json:"online,omitempty"`
	Offline           *PresenceStateUpdate    `protobuf:"bytes,8,opt,name=offline,proto3" json:"offline,omitempty"`
	LastSeen          *LastSeenUpdate         `protobuf:"bytes,9,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Reactions         *MessageReactionUpdate  `protobuf:"bytes,222,opt,name=reactions,proto3" json:"reactions,omitempty"`
	NewReaction       *ReactionPositionUpdate `protobuf:"bytes,54323,opt,name=new_reaction,json=newReaction,proto3" json:"new_reaction,omitempty"`
	ReactionsReadByMe *ReactionPositionUpdate `protobuf:"bytes,52832,opt,name=reactions_read_by_me,json=reactionsReadByMe,proto3" json:"reactions_read_by_me,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PresenceUpdateUnion) Reset() {
	*x = PresenceUpdateUnion{}
	mi := &file_wire_receive_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceUpdateUnion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceUpdateUnion) ProtoMessage() {}

func (x *PresenceUpdateUnion) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceUpdateUnion.ProtoReflect.Descriptor instead.
func (*PresenceUpdateUnion) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{11}
}

func (x *PresenceUpdateUnion) GetTyping() *TypingUpdate {
	if x != nil {
		return x.Typing
	}
	return nil
}

func (x *PresenceUpdateUnion) GetTypingStop() *TypingUpdate {
	if x != nil {
		return x.TypingStop
	}
	return nil
}

func (x *PresenceUpdateUnion) GetOnline() *PresenceStateUpdate {
	if x != nil {
		return x.Online
	}
	return nil
}

func (x *PresenceUpdateUnion) GetOffline() *PresenceStateUpdate {
	if x != nil {
		return x.Offline
	}
	return nil
}

func (x *PresenceUpdateUnion) GetLastSeen() *LastSeenUpdate {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *PresenceUpdateUnion) GetReactions() *MessageReactionUpdate {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *PresenceUpdateUnion) GetNewReaction() *ReactionPositionUpdate {
	if x != nil {
		return x.NewReaction
	}
	return nil
}

func (x *PresenceUpdateUnion) GetReactionsReadByMe() *ReactionPositionUpdate {
	if x != nil {
		return x.ReactionsReadByMe
	}
	return nil
}

type TypingUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *Peer                  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TypingType    int32                  `protobuf:"varint,3,opt,name=typing_type,json=typingType,proto3" json:"typing_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypingUpdate) Reset() {
	*x = TypingUpdate{}
	mi := &file_wire_receive_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypingUpdate) ProtoMessage() {}

func (x *TypingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypingUpdate.ProtoReflect.Descriptor instead.
func (*TypingUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{12}
}

func (x *TypingUpdate) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *TypingUpdate) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *TypingUpdate) GetTypingType() int32 {
	if x != nil {
		return x.TypingType
	}
	return 0
}

type PresenceStateUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceType     int32                  `protobuf:"varint,2,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	DeviceCategory *StringValue           `protobuf:"bytes,3,opt,name=device_category,json=deviceCategory,proto3" json:"device_category,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PresenceStateUpdate) Reset() {
	*x = PresenceStateUpdate{}
	mi := &file_wire_receive_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceStateUpdate) ProtoMessage() {}

func (x *PresenceStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceStateUpdate.ProtoReflect.Descriptor instead.
func (*PresenceStateUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{13}
}

func (x *PresenceStateUpdate) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PresenceStateUpdate) GetDeviceType() int32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *PresenceStateUpdate) GetDeviceCategory() *StringValue {
	if x != nil {
		return x.DeviceCategory
	}
	return nil
}

type LastSeenUpdate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Date           int64                  `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	DeviceType     int32                  `protobuf:"varint,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	DeviceCategory *StringValue           `protobuf:"bytes,4,opt,name=device_category,json=deviceCategory,proto3" json:"device_category,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LastSeenUpdate) Reset() {
	*x = LastSeenUpdate{}
	mi := &file_wire_receive_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LastSeenUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LastSeenUpdate) ProtoMessage() {}

func (x *LastSeenUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LastSeenUpdate.ProtoReflect.Descriptor instead.
func (*LastSeenUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{14}
}

func (x *LastSeenUpdate) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LastSeenUpdate) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *LastSeenUpdate) GetDeviceType() int32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *LastSeenUpdate) GetDeviceCategory() *StringValue {
	if x != nil {
		return x.DeviceCategory
	}
	return nil
}

type MessageReactionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *Peer                  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Rid           int64                  `protobuf:"varint,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Reactions     []*ReactionSummary     `protobuf:"bytes,3,rep,name=reactions,proto3" json:"reactions,omitempty"`
	ReactionByMe  bool                   `protobuf:"varint,4,opt,name=reaction_by_me,json=reactionByMe,proto3" json:"reaction_by_me,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageReactionUpdate) Reset() {
	*x = MessageReactionUpdate{}
	mi := &file_wire_receive_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageReactionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageReactionUpdate) ProtoMessage() {}

func (x *MessageReactionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageReactionUpdate.ProtoReflect.Descriptor instead.
func (*MessageReactionUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{15}
}

func (x *MessageReactionUpdate) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *MessageReactionUpdate) GetRid() int64 {
	if x != nil {
		return x.Rid
	}
	return 0
}

func (x *MessageReactionUpdate) GetReactions() []*ReactionSummary {
	if x != nil {
		return x.Reactions
	}
	return nil
}

func (x *MessageReactionUpdate) GetReactionByMe() bool {
	if x != nil {
		return x.ReactionByMe
	}
	return false
}

type ReactionPositionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *Peer                  `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Message       *MessagePosition       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactionPositionUpdate) Reset() {
	*x = ReactionPositionUpdate{}
	mi := &file_wire_receive_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactionPositionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionPositionUpdate) ProtoMessage() {}

func (x *ReactionPositionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_wire_receive_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionPositionUpdate.ProtoReflect.Descriptor instead.
func (*ReactionPositionUpdate) Descriptor() ([]byte, []int) {
	return file_wire_receive_proto_rawDescGZIP(), []int{16}
}

func (x *ReactionPositionUpdate) GetPeer() *Peer {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *ReactionPositionUpdate) GetMessage() *MessagePosition {
	if x != nil {
		return x.Message
	}
	return nil
}

var File_wire_receive_proto protoreflect.FileDescriptor

const file_wire_receive_proto_rawDesc = "" +
	"\n" +
	"\x12wire/receive.proto\x12\x15gobale.bale.reference\x1a\x0fwire/bale.proto\x1a\x1awire/groups_extended.proto\x1a\x1bwire/account_extended.proto\"\xf5\n" +
	"\n" +
	"\x10GroupUpdateUnion\x12K\n" +
	"\vrestriction\x18\xd3\x05 \x01(\v2(.gobale.bale.reference.GroupNumberUpdateR\vrestriction\x12?\n" +
	"\x05title\x18\xb1\x14 \x01(\v2(.gobale.bale.reference.GroupStringUpdateR\x05title\x12=\n" +
	"\x06avatar\x18\xb2\x14 \x01(\v2$.gobale.bale.reference.GroupIDUpdateR\x06avatar\x12?\n" +
	"\x06member\x18\xb4\x14 \x01(\v2&.gobale.bale.reference.GroupBoolUpdateR\x06member\x12D\n" +
	"\amembers\x18\xb6\x14 \x01(\v2).gobale.bale.reference.GroupMembersUpdateR\amembers\x12J\n" +
	"\rasync_members\x18\xb7\x14 \x01(\v2$.gobale.bale.reference.GroupIDUpdateR\fasyncMembers\x12=\n" +
	"\x05topic\x18\xb8\x14 \x01(\v2&.gobale.bale.reference.GroupTextUpdateR\x05topic\x12=\n" +
	"\x05about\x18\xb9\x14 \x01(\v2&.gobale.bale.reference.GroupTextUpdateR\x05about\x12>\n" +
	"\x05owner\x18\xbb\x14 \x01(\v2'.gobale.bale.reference.GroupOwnerUpdateR\x05owner\x12L\n" +
	"\x0ehistory_shared\x18\xbc\x14 \x01(\v2$.gobale.bale.reference.GroupIDUpdateR\rhistoryShared\x12?\n" +
	"\x05count\x18\xbe\x14 \x01(\v2(.gobale.bale.reference.GroupNumberUpdateR\x05count\x12B\n" +
	"\bcan_send\x18\xc0\x14 \x01(\v2&.gobale.bale.reference.GroupBoolUpdateR\acanSend\x12Q\n" +
	"\x10can_view_members\x18\xc1\x14 \x01(\v2&.gobale.bale.reference.GroupBoolUpdateR\x0ecanViewMembers\x12F\n" +
	"\n" +
	"can_invite\x18\xc2\x14 \x01(\v2&.gobale.bale.reference.GroupBoolUpdateR\tcanInvite\x12>\n" +
	"\x05admin\x18\xc3\x14 \x01(\v2'.gobale.bale.reference.GroupAdminUpdateR\x05admin\x12A\n" +
	"\borphaned\x18\xc4\x14 \x01(\v2$.gobale.bale.reference.GroupIDUpdateR\borphaned\x12E\n" +
	"\busername\x18\xc0\x16 \x01(\v2(.gobale.bale.reference.GroupStringUpdateR\busername\x12c\n" +
	"\x12member_permissions\x18Ĝ\x03 \x01(\v22.gobale.bale.reference.GroupMemberPermissionUpdateR\x11memberPermissions\x12f\n" +
	"\x13default_permissions\x18Ŝ\x03 \x01(\v23.gobale.bale.reference.GroupDefaultPermissionUpdateR\x12defaultPermissions\"*\n" +
	"\rGroupIDUpdate\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\rR\agroupId\"D\n" +
	"\x11GroupStringUpdate\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\rR\agroupId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"f\n" +
	"\x0fGroupTextUpdate\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\rR\agroupId\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".gobale.bale.reference.StringValueR\x05value\"D\n" +
	"\x11GroupNumberUpdate\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\rR\agroupId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"B\n" +
	"\x0fGroupBoolUpdate\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\rR\agroupId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value\"F\n" +
	"\x10GroupOwnerUpdate\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\rR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"a\n" +
	"\x10GroupAdminUpdate\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\rR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x19\n" +
	"\bis_admin\x18\x03 \x01(\bR\aisAdmin\"u\n" +
	"\x12GroupMembersUpdate\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\rR\agroupId\x12D\n" +
	"\amembers\x18\x02 \x03(\v2*.gobale.bale.reference.GroupExtendedMemberR\amembers\"\x9c\x01\n" +
	"\x1bGroupMemberPermissionUpdate\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\rR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12I\n" +
	"\vpermissions\x18\x03 \x01(\v2'.gobale.bale.reference.GroupPermissionsR\vpermissions\"\x9f\x01\n" +
	"\x1cGroupDefaultPermissionUpdate\x124\n" +
	"\x05group\x18\x01 \x01(\v2\x1e.gobale.bale.reference.PeerRefR\x05group\x12I\n" +
	"\vpermissions\x18\x02 \x01(\v2'.gobale.bale.reference.GroupPermissionsR\vpermissions\"\xe9\x04\n" +
	"\x13PresenceUpdateUnion\x12;\n" +
	"\x06typing\x18\x06 \x01(\v2#.gobale.bale.reference.TypingUpdateR\x06typing\x12D\n" +
	"\vtyping_stop\x18Q \x01(\v2#.gobale.bale.reference.TypingUpdateR\n" +
	"typingStop\x12B\n" +
	"\x06online\x18\a \x01(\v2*.gobale.bale.reference.PresenceStateUpdateR\x06online\x12D\n" +
	"\aoffline\x18\b \x01(\v2*.gobale.bale.reference.PresenceStateUpdateR\aoffline\x12B\n" +
	"\tlast_seen\x18\t \x01(\v2%.gobale.bale.reference.LastSeenUpdateR\blastSeen\x12K\n" +
	"\treactions\x18\xde\x01 \x01(\v2,.gobale.bale.reference.MessageReactionUpdateR\treactions\x12R\n" +
	"\fnew_reaction\x18\xb3\xa8\x03 \x01(\v2-.gobale.bale.reference.ReactionPositionUpdateR\vnewReaction\x12`\n" +
	"\x14reactions_read_by_me\x18\xe0\x9c\x03 \x01(\v2-.gobale.bale.reference.ReactionPositionUpdateR\x11reactionsReadByMe\"y\n" +
	"\fTypingUpdate\x12/\n" +
	"\x04peer\x18\x01 \x01(\v2\x1b.gobale.bale.reference.PeerR\x04peer\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x1f\n" +
	"\vtyping_type\x18\x03 \x01(\x05R\n" +
	"typingType\"\x9c\x01\n" +
	"\x13PresenceStateUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x1f\n" +
	"\vdevice_type\x18\x02 \x01(\x05R\n" +
	"deviceType\x12K\n" +
	"\x0fdevice_category\x18\x03 \x01(\v2\".gobale.bale.reference.StringValueR\x0edeviceCategory\"\xab\x01\n" +
	"\x0eLastSeenUpdate\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\x03R\x04date\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\x05R\n" +
	"deviceType\x12K\n" +
	"\x0fdevice_category\x18\x04 \x01(\v2\".gobale.bale.reference.StringValueR\x0edeviceCategory\"\xc6\x01\n" +
	"\x15MessageReactionUpdate\x12/\n" +
	"\x04peer\x18\x01 \x01(\v2\x1b.gobale.bale.reference.PeerR\x04peer\x12\x10\n" +
	"\x03rid\x18\x02 \x01(\x03R\x03rid\x12D\n" +
	"\treactions\x18\x03 \x03(\v2&.gobale.bale.reference.ReactionSummaryR\treactions\x12$\n" +
	"\x0ereaction_by_me\x18\x04 \x01(\bR\freactionByMe\"\x8b\x01\n" +
	"\x16ReactionPositionUpdate\x12/\n" +
	"\x04peer\x18\x01 \x01(\v2\x1b.gobale.bale.reference.PeerR\x04peer\x12@\n" +
	"\amessage\x18\x02 \x01(\v2&.gobale.bale.reference.MessagePositionR\amessageB8Z6github.com/mimalef70/gobale/src/internal/balemeow/wireb\x06proto3"

var (
	file_wire_receive_proto_rawDescOnce sync.Once
	file_wire_receive_proto_rawDescData []byte
)

func file_wire_receive_proto_rawDescGZIP() []byte {
	file_wire_receive_proto_rawDescOnce.Do(func() {
		file_wire_receive_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_receive_proto_rawDesc), len(file_wire_receive_proto_rawDesc)))
	})
	return file_wire_receive_proto_rawDescData
}

var file_wire_receive_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_wire_receive_proto_goTypes = []any{
	(*GroupUpdateUnion)(nil),             // 0: gobale.bale.reference.GroupUpdateUnion
	(*GroupIDUpdate)(nil),                // 1: gobale.bale.reference.GroupIDUpdate
	(*GroupStringUpdate)(nil),            // 2: gobale.bale.reference.GroupStringUpdate
	(*GroupTextUpdate)(nil),              // 3: gobale.bale.reference.GroupTextUpdate
	(*GroupNumberUpdate)(nil),            // 4: gobale.bale.reference.GroupNumberUpdate
	(*GroupBoolUpdate)(nil),              // 5: gobale.bale.reference.GroupBoolUpdate
	(*GroupOwnerUpdate)(nil),             // 6: gobale.bale.reference.GroupOwnerUpdate
	(*GroupAdminUpdate)(nil),             // 7: gobale.bale.reference.GroupAdminUpdate
	(*GroupMembersUpdate)(nil),           // 8: gobale.bale.reference.GroupMembersUpdate
	(*GroupMemberPermissionUpdate)(nil),  // 9: gobale.bale.reference.GroupMemberPermissionUpdate
	(*GroupDefaultPermissionUpdate)(nil), // 10: gobale.bale.reference.GroupDefaultPermissionUpdate
	(*PresenceUpdateUnion)(nil),          // 11: gobale.bale.reference.PresenceUpdateUnion
	(*TypingUpdate)(nil),                 // 12: gobale.bale.reference.TypingUpdate
	(*PresenceStateUpdate)(nil),          // 13: gobale.bale.reference.PresenceStateUpdate
	(*LastSeenUpdate)(nil),               // 14: gobale.bale.reference.LastSeenUpdate
	(*MessageReactionUpdate)(nil),        // 15: gobale.bale.reference.MessageReactionUpdate
	(*ReactionPositionUpdate)(nil),       // 16: gobale.bale.reference.ReactionPositionUpdate
	(*StringValue)(nil),                  // 17: gobale.bale.reference.StringValue
	(*GroupExtendedMember)(nil),          // 18: gobale.bale.reference.GroupExtendedMember
	(*GroupPermissions)(nil),             // 19: gobale.bale.reference.GroupPermissions
	(*PeerRef)(nil),                      // 20: gobale.bale.reference.PeerRef
	(*Peer)(nil),                         // 21: gobale.bale.reference.Peer
	(*ReactionSummary)(nil),              // 22: gobale.bale.reference.ReactionSummary
	(*MessagePosition)(nil),              // 23: gobale.bale.reference.MessagePosition
}
var file_wire_receive_proto_depIdxs = []int32{
	4,  // 0: gobale.bale.reference.GroupUpdateUnion.restriction:type_name -> gobale.bale.reference.GroupNumberUpdate
	2,  // 1: gobale.bale.reference.GroupUpdateUnion.title:type_name -> gobale.bale.reference.GroupStringUpdate
	1,  // 2: gobale.bale.reference.GroupUpdateUnion.avatar:type_name -> gobale.bale.reference.GroupIDUpdate
	5,  // 3: gobale.bale.reference.GroupUpdateUnion.member:type_name -> gobale.bale.reference.GroupBoolUpdate
	8,  // 4: gobale.bale.reference.GroupUpdateUnion.members:type_name -> gobale.bale.reference.GroupMembersUpdate
	1,  // 5: gobale.bale.reference.GroupUpdateUnion.async_members:type_name -> gobale.bale.reference.GroupIDUpdate
	3,  // 6: gobale.bale.reference.GroupUpdateUnion.topic:type_name -> gobale.bale.reference.GroupTextUpdate
	3,  // 7: gobale.bale.reference.GroupUpdateUnion.about:type_name -> gobale.bale.reference.GroupTextUpdate
	6,  // 8: gobale.bale.reference.GroupUpdateUnion.owner:type_name -> gobale.bale.reference.GroupOwnerUpdate
	1,  // 9: gobale.bale.reference.GroupUpdateUnion.history_shared:type_name -> gobale.bale.reference.GroupIDUpdate
	4,  // 10: gobale.bale.reference.GroupUpdateUnion.count:type_name -> gobale.bale.reference.GroupNumberUpdate
	5,  // 11: gobale.bale.reference.GroupUpdateUnion.can_send:type_name -> gobale.bale.reference.GroupBoolUpdate
	5,  // 12: gobale.bale.reference.GroupUpdateUnion.can_view_members:type_name -> gobale.bale.reference.GroupBoolUpdate
	5,  // 13: gobale.bale.reference.GroupUpdateUnion.can_invite:type_name -> gobale.bale.reference.GroupBoolUpdate
	7,  // 14: gobale.bale.reference.GroupUpdateUnion.admin:type_name -> gobale.bale.reference.GroupAdminUpdate
	1,  // 15: gobale.bale.reference.GroupUpdateUnion.orphaned:type_name -> gobale.bale.reference.GroupIDUpdate
	2,  // 16: gobale.bale.reference.GroupUpdateUnion.username:type_name -> gobale.bale.reference.GroupStringUpdate
	9,  // 17: gobale.bale.reference.GroupUpdateUnion.member_permissions:type_name -> gobale.bale.reference.GroupMemberPermissionUpdate
	10, // 18: gobale.bale.reference.GroupUpdateUnion.default_permissions:type_name -> gobale.bale.reference.GroupDefaultPermissionUpdate
	17, // 19: gobale.bale.reference.GroupTextUpdate.value:type_name -> gobale.bale.reference.StringValue
	18, // 20: gobale.bale.reference.GroupMembersUpdate.members:type_name -> gobale.bale.reference.GroupExtendedMember
	19, // 21: gobale.bale.reference.GroupMemberPermissionUpdate.permissions:type_name -> gobale.bale.reference.GroupPermissions
	20, // 22: gobale.bale.reference.GroupDefaultPermissionUpdate.group:type_name -> gobale.bale.reference.PeerRef
	19, // 23: gobale.bale.reference.GroupDefaultPermissionUpdate.permissions:type_name -> gobale.bale.reference.GroupPermissions
	12, // 24: gobale.bale.reference.PresenceUpdateUnion.typing:type_name -> gobale.bale.reference.TypingUpdate
	12, // 25: gobale.bale.reference.PresenceUpdateUnion.typing_stop:type_name -> gobale.bale.reference.TypingUpdate
	13, // 26: gobale.bale.reference.PresenceUpdateUnion.online:type_name -> gobale.bale.reference.PresenceStateUpdate
	13, // 27: gobale.bale.reference.PresenceUpdateUnion.offline:type_name -> gobale.bale.reference.PresenceStateUpdate
	14, // 28: gobale.bale.reference.PresenceUpdateUnion.last_seen:type_name -> gobale.bale.reference.LastSeenUpdate
	15, // 29: gobale.bale.reference.PresenceUpdateUnion.reactions:type_name -> gobale.bale.reference.MessageReactionUpdate
	16, // 30: gobale.bale.reference.PresenceUpdateUnion.new_reaction:type_name -> gobale.bale.reference.ReactionPositionUpdate
	16, // 31: gobale.bale.reference.PresenceUpdateUnion.reactions_read_by_me:type_name -> gobale.bale.reference.ReactionPositionUpdate
	21, // 32: gobale.bale.reference.TypingUpdate.peer:type_name -> gobale.bale.reference.Peer
	17, // 33: gobale.bale.reference.PresenceStateUpdate.device_category:type_name -> gobale.bale.reference.StringValue
	17, // 34: gobale.bale.reference.LastSeenUpdate.device_category:type_name -> gobale.bale.reference.StringValue
	21, // 35: gobale.bale.reference.MessageReactionUpdate.peer:type_name -> gobale.bale.reference.Peer
	22, // 36: gobale.bale.reference.MessageReactionUpdate.reactions:type_name -> gobale.bale.reference.ReactionSummary
	21, // 37: gobale.bale.reference.ReactionPositionUpdate.peer:type_name -> gobale.bale.reference.Peer
	23, // 38: gobale.bale.reference.ReactionPositionUpdate.message:type_name -> gobale.bale.reference.MessagePosition
	39, // [39:39] is the sub-list for method output_type
	39, // [39:39] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_wire_receive_proto_init() }
func file_wire_receive_proto_init() {
	if File_wire_receive_proto != nil {
		return
	}
	file_wire_bale_proto_init()
	file_wire_groups_extended_proto_init()
	file_wire_account_extended_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_receive_proto_rawDesc), len(file_wire_receive_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_receive_proto_goTypes,
		DependencyIndexes: file_wire_receive_proto_depIdxs,
		MessageInfos:      file_wire_receive_proto_msgTypes,
	}.Build()
	File_wire_receive_proto = out.File
	file_wire_receive_proto_goTypes = nil
	file_wire_receive_proto_depIdxs = nil
}
