// Bale Web 5.7.0 module 98503 (bale.v1.Images), module 22663 (descriptors).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: wire/stickers_extended.proto

package wire

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StickerDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Emoji         *StringValue           `protobuf:"bytes,2,opt,name=emoji,proto3" json:"emoji,omitempty"`
	Image128      *StickerImage          `protobuf:"bytes,3,opt,name=image128,proto3" json:"image128,omitempty"`
	Image512      *StickerImage          `protobuf:"bytes,4,opt,name=image512,proto3" json:"image512,omitempty"`
	Image256      *StickerImage          `protobuf:"bytes,5,opt,name=image256,proto3" json:"image256,omitempty"`
	Format        int32                  `protobuf:"varint,6,opt,name=format,proto3" json:"format,omitempty"`
	Animation     *StickerImage          `protobuf:"bytes,7,opt,name=animation,proto3" json:"animation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StickerDescriptor) Reset() {
	*x = StickerDescriptor{}
	mi := &file_wire_stickers_extended_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerDescriptor) ProtoMessage() {}

func (x *StickerDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_wire_stickers_extended_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickerDescriptor.ProtoReflect.Descriptor instead.
func (*StickerDescriptor) Descriptor() ([]byte, []int) {
	return file_wire_stickers_extended_proto_rawDescGZIP(), []int{0}
}

func (x *StickerDescriptor) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StickerDescriptor) GetEmoji() *StringValue {
	if x != nil {
		return x.Emoji
	}
	return nil
}

func (x *StickerDescriptor) GetImage128() *StickerImage {
	if x != nil {
		return x.Image128
	}
	return nil
}

func (x *StickerDescriptor) GetImage512() *StickerImage {
	if x != nil {
		return x.Image512
	}
	return nil
}

func (x *StickerDescriptor) GetImage256() *StickerImage {
	if x != nil {
		return x.Image256
	}
	return nil
}

func (x *StickerDescriptor) GetFormat() int32 {
	if x != nil {
		return x.Format
	}
	return 0
}

func (x *StickerDescriptor) GetAnimation() *StickerImage {
	if x != nil {
		return x.Animation
	}
	return nil
}

type AnimatedStickerDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Emoji         *StringValue           `protobuf:"bytes,2,opt,name=emoji,proto3" json:"emoji,omitempty"`
	FileLocation  *StickerImage          `protobuf:"bytes,3,opt,name=file_location,json=fileLocation,proto3" json:"file_location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimatedStickerDescriptor) Reset() {
	*x = AnimatedStickerDescriptor{}
	mi := &file_wire_stickers_extended_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimatedStickerDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimatedStickerDescriptor) ProtoMessage() {}

func (x *AnimatedStickerDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_wire_stickers_extended_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimatedStickerDescriptor.ProtoReflect.Descriptor instead.
func (*AnimatedStickerDescriptor) Descriptor() ([]byte, []int) {
	return file_wire_stickers_extended_proto_rawDescGZIP(), []int{1}
}

func (x *AnimatedStickerDescriptor) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnimatedStickerDescriptor) GetEmoji() *StringValue {
	if x != nil {
		return x.Emoji
	}
	return nil
}

func (x *AnimatedStickerDescriptor) GetFileLocation() *StickerImage {
	if x != nil {
		return x.FileLocation
	}
	return nil
}

type StickerCollection struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	Id               int32                        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccessHash       int64                        `protobuf:"varint,2,opt,name=access_hash,json=accessHash,proto3" json:"access_hash,omitempty"`
	Stickers         []*StickerDescriptor         `protobuf:"bytes,3,rep,name=stickers,proto3" json:"stickers,omitempty"`
	Animated         *BoolValue                   `protobuf:"bytes,4,opt,name=animated,proto3" json:"animated,omitempty"`
	AnimatedStickers []*AnimatedStickerDescriptor `protobuf:"bytes,5,rep,name=animated_stickers,json=animatedStickers,proto3" json:"animated_stickers,omitempty"`
	Name             *StringValue                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StickerCollection) Reset() {
	*x = StickerCollection{}
	mi := &file_wire_stickers_extended_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerCollection) ProtoMessage() {}

func (x *StickerCollection) ProtoReflect() protoreflect.Message {
	mi := &file_wire_stickers_extended_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickerCollection.ProtoReflect.Descriptor instead.
func (*StickerCollection) Descriptor() ([]byte, []int) {
	return file_wire_stickers_extended_proto_rawDescGZIP(), []int{2}
}

func (x *StickerCollection) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StickerCollection) GetAccessHash() int64 {
	if x != nil {
		return x.AccessHash
	}
	return 0
}

func (x *StickerCollection) GetStickers() []*StickerDescriptor {
	if x != nil {
		return x.Stickers
	}
	return nil
}

func (x *StickerCollection) GetAnimated() *BoolValue {
	if x != nil {
		return x.Animated
	}
	return nil
}

func (x *StickerCollection) GetAnimatedStickers() []*AnimatedStickerDescriptor {
	if x != nil {
		return x.AnimatedStickers
	}
	return nil
}

func (x *StickerCollection) GetName() *StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

type StickerListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        *StringValue           `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StickerListRequest) Reset() {
	*x = StickerListRequest{}
	mi := &file_wire_stickers_extended_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerListRequest) ProtoMessage() {}

func (x *StickerListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_stickers_extended_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickerListRequest.ProtoReflect.Descriptor instead.
func (*StickerListRequest) Descriptor() ([]byte, []int) {
	return file_wire_stickers_extended_proto_rawDescGZIP(), []int{3}
}

func (x *StickerListRequest) GetOffset() *StringValue {
	if x != nil {
		return x.Offset
	}
	return nil
}

type StickerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnStickers   []*StickerCollection   `protobuf:"bytes,1,rep,name=own_stickers,json=ownStickers,proto3" json:"own_stickers,omitempty"`
	Offset        *StringValue           `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StickerListResponse) Reset() {
	*x = StickerListResponse{}
	mi := &file_wire_stickers_extended_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerListResponse) ProtoMessage() {}

func (x *StickerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_stickers_extended_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickerListResponse.ProtoReflect.Descriptor instead.
func (*StickerListResponse) Descriptor() ([]byte, []int) {
	return file_wire_stickers_extended_proto_rawDescGZIP(), []int{4}
}

func (x *StickerListResponse) GetOwnStickers() []*StickerCollection {
	if x != nil {
		return x.OwnStickers
	}
	return nil
}

func (x *StickerListResponse) GetOffset() *StringValue {
	if x != nil {
		return x.Offset
	}
	return nil
}

type StickerCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	AccessHash    int64                  `protobuf:"varint,2,opt,name=access_hash,json=accessHash,proto3" json:"access_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StickerCollectionRequest) Reset() {
	*x = StickerCollectionRequest{}
	mi := &file_wire_stickers_extended_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerCollectionRequest) ProtoMessage() {}

func (x *StickerCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_stickers_extended_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickerCollectionRequest.ProtoReflect.Descriptor instead.
func (*StickerCollectionRequest) Descriptor() ([]byte, []int) {
	return file_wire_stickers_extended_proto_rawDescGZIP(), []int{5}
}

func (x *StickerCollectionRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StickerCollectionRequest) GetAccessHash() int64 {
	if x != nil {
		return x.AccessHash
	}
	return 0
}

type StickerCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *StickerCollection     `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StickerCollectionResponse) Reset() {
	*x = StickerCollectionResponse{}
	mi := &file_wire_stickers_extended_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerCollectionResponse) ProtoMessage() {}

func (x *StickerCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wire_stickers_extended_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickerCollectionResponse.ProtoReflect.Descriptor instead.
func (*StickerCollectionResponse) Descriptor() ([]byte, []int) {
	return file_wire_stickers_extended_proto_rawDescGZIP(), []int{6}
}

func (x *StickerCollectionResponse) GetCollection() *StickerCollection {
	if x != nil {
		return x.Collection
	}
	return nil
}

type StickerPackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StickerPackRequest) Reset() {
	*x = StickerPackRequest{}
	mi := &file_wire_stickers_extended_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StickerPackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StickerPackRequest) ProtoMessage() {}

func (x *StickerPackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wire_stickers_extended_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StickerPackRequest.ProtoReflect.Descriptor instead.
func (*StickerPackRequest) Descriptor() ([]byte, []int) {
	return file_wire_stickers_extended_proto_rawDescGZIP(), []int{7}
}

func (x *StickerPackRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_wire_stickers_extended_proto protoreflect.FileDescriptor

const file_wire_stickers_extended_proto_rawDesc = "" +
	"\n" +
	"\x1cwire/stickers_extended.proto\x12\x15gobale.bale.reference\x1a\x0fwire/bale.proto\"\xfb\x02\n" +
	"\x11StickerDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x128\n" +
	"\x05emoji\x18\x02 \x01(\v2\".gobale.bale.reference.StringValueR\x05emoji\x12?\n" +
	"\bimage128\x18\x03 \x01(\v2#.gobale.bale.reference.StickerImageR\bimage128\x12?\n" +
	"\bimage512\x18\x04 \x01(\v2#.gobale.bale.reference.StickerImageR\bimage512\x12?\n" +
	"\bimage256\x18\x05 \x01(\v2#.gobale.bale.reference.StickerImageR\bimage256\x12\x16\n" +
	"\x06format\x18\x06 \x01(\x05R\x06format\x12A\n" +
	"\tanimation\x18\a \x01(\v2#.gobale.bale.reference.StickerImageR\tanimation\"\xaf\x01\n" +
	"\x19AnimatedStickerDescriptor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x128\n" +
	"\x05emoji\x18\x02 \x01(\v2\".gobale.bale.reference.StringValueR\x05emoji\x12H\n" +
	"\rfile_location\x18\x03 \x01(\v2#.gobale.bale.reference.StickerImageR\ffileLocation\"\xdf\x02\n" +
	"\x11StickerCollection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vaccess_hash\x18\x02 \x01(\x03R\n" +
	"accessHash\x12D\n" +
	"\bstickers\x18\x03 \x03(\v2(.gobale.bale.reference.StickerDescriptorR\bstickers\x12<\n" +
	"\banimated\x18\x04 \x01(\v2 .gobale.bale.reference.BoolValueR\banimated\x12]\n" +
	"\x11animated_stickers\x18\x05 \x03(\v20.gobale.bale.reference.AnimatedStickerDescriptorR\x10animatedStickers\x126\n" +
	"\x04name\x18\x06 \x01(\v2\".gobale.bale.reference.StringValueR\x04name\"P\n" +
	"\x12StickerListRequest\x12:\n" +
	"\x06offset\x18\x01 \x01(\v2\".gobale.bale.reference.StringValueR\x06offset\"\x9e\x01\n" +
	"\x13StickerListResponse\x12K\n" +
	"\fown_stickers\x18\x01 \x03(\v2(.gobale.bale.reference.StickerCollectionR\vownStickers\x12:\n" +
	"\x06offset\x18\x02 \x01(\v2\".gobale.bale.reference.StringValueR\x06offset\"K\n" +
	"\x18StickerCollectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1f\n" +
	"\vaccess_hash\x18\x02 \x01(\x03R\n" +
	"accessHash\"e\n" +
	"\x19StickerCollectionResponse\x12H\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2(.gobale.bale.reference.StickerCollectionR\n" +
	"collection\"$\n" +
	"\x12StickerPackRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02idB8Z6github.com/mimalef70/gobale/src/internal/balemeow/wireb\x06proto3"

var (
	file_wire_stickers_extended_proto_rawDescOnce sync.Once
	file_wire_stickers_extended_proto_rawDescData []byte
)

func file_wire_stickers_extended_proto_rawDescGZIP() []byte {
	file_wire_stickers_extended_proto_rawDescOnce.Do(func() {
		file_wire_stickers_extended_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wire_stickers_extended_proto_rawDesc), len(file_wire_stickers_extended_proto_rawDesc)))
	})
	return file_wire_stickers_extended_proto_rawDescData
}

var file_wire_stickers_extended_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_wire_stickers_extended_proto_goTypes = []any{
	(*StickerDescriptor)(nil),         // 0: gobale.bale.reference.StickerDescriptor
	(*AnimatedStickerDescriptor)(nil), // 1: gobale.bale.reference.AnimatedStickerDescriptor
	(*StickerCollection)(nil),         // 2: gobale.bale.reference.StickerCollection
	(*StickerListRequest)(nil),        // 3: gobale.bale.reference.StickerListRequest
	(*StickerListResponse)(nil),       // 4: gobale.bale.reference.StickerListResponse
	(*StickerCollectionRequest)(nil),  // 5: gobale.bale.reference.StickerCollectionRequest
	(*StickerCollectionResponse)(nil), // 6: gobale.bale.reference.StickerCollectionResponse
	(*StickerPackRequest)(nil),        // 7: gobale.bale.reference.StickerPackRequest
	(*StringValue)(nil),               // 8: gobale.bale.reference.StringValue
	(*StickerImage)(nil),              // 9: gobale.bale.reference.StickerImage
	(*BoolValue)(nil),                 // 10: gobale.bale.reference.BoolValue
}
var file_wire_stickers_extended_proto_depIdxs = []int32{
	8,  // 0: gobale.bale.reference.StickerDescriptor.emoji:type_name -> gobale.bale.reference.StringValue
	9,  // 1: gobale.bale.reference.StickerDescriptor.image128:type_name -> gobale.bale.reference.StickerImage
	9,  // 2: gobale.bale.reference.StickerDescriptor.image512:type_name -> gobale.bale.reference.StickerImage
	9,  // 3: gobale.bale.reference.StickerDescriptor.image256:type_name -> gobale.bale.reference.StickerImage
	9,  // 4: gobale.bale.reference.StickerDescriptor.animation:type_name -> gobale.bale.reference.StickerImage
	8,  // 5: gobale.bale.reference.AnimatedStickerDescriptor.emoji:type_name -> gobale.bale.reference.StringValue
	9,  // 6: gobale.bale.reference.AnimatedStickerDescriptor.file_location:type_name -> gobale.bale.reference.StickerImage
	0,  // 7: gobale.bale.reference.StickerCollection.stickers:type_name -> gobale.bale.reference.StickerDescriptor
	10, // 8: gobale.bale.reference.StickerCollection.animated:type_name -> gobale.bale.reference.BoolValue
	1,  // 9: gobale.bale.reference.StickerCollection.animated_stickers:type_name -> gobale.bale.reference.AnimatedStickerDescriptor
	8,  // 10: gobale.bale.reference.StickerCollection.name:type_name -> gobale.bale.reference.StringValue
	8,  // 11: gobale.bale.reference.StickerListRequest.offset:type_name -> gobale.bale.reference.StringValue
	2,  // 12: gobale.bale.reference.StickerListResponse.own_stickers:type_name -> gobale.bale.reference.StickerCollection
	8,  // 13: gobale.bale.reference.StickerListResponse.offset:type_name -> gobale.bale.reference.StringValue
	2,  // 14: gobale.bale.reference.StickerCollectionResponse.collection:type_name -> gobale.bale.reference.StickerCollection
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_wire_stickers_extended_proto_init() }
func file_wire_stickers_extended_proto_init() {
	if File_wire_stickers_extended_proto != nil {
		return
	}
	file_wire_bale_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wire_stickers_extended_proto_rawDesc), len(file_wire_stickers_extended_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_wire_stickers_extended_proto_goTypes,
		DependencyIndexes: file_wire_stickers_extended_proto_depIdxs,
		MessageInfos:      file_wire_stickers_extended_proto_msgTypes,
	}.Build()
	File_wire_stickers_extended_proto = out.File
	file_wire_stickers_extended_proto_goTypes = nil
	file_wire_stickers_extended_proto_depIdxs = nil
}
