version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: /src
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      go-patch-updates:
        update-types: [patch]
  - package-ecosystem: docker
    directory: /docker
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
