import { expect, test } from '@playwright/test'
test.describe('real Go REST and embedded assets', () => {
  test.skip(
    !process.env.GOBALE_E2E_URL,
    'Set GOBALE_E2E_URL to the isolated uismoke server to run integration tests',
  )
  test('real session, device creation, OTP/2FA, webhook and scoped delivery detail', async ({
    page,
  }) => {
    await page.goto('./')
    await page.getByLabel('Username', { exact: true }).fill('admin')
    await page.getByLabel('Password', { exact: true }).fill('synthetic-ui-password')
    await page.getByRole('button', { name: 'Sign in', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Accounts', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Add account', exact: true }).click()
    await page.getByLabel('Connection name').fill(`browser-${Date.now()}`)
    await page.getByRole('button', { name: 'Create connection', exact: true }).click()
    await expect(page.getByLabel('Phone number')).toBeVisible()
    await page.getByLabel('Phone number').fill('+15550000001')
    await page.getByRole('button', { name: 'Request login code' }).click()
    await expect(page.getByLabel('Login code')).toBeVisible()
    await page.reload()
    await expect(page.getByLabel('Login code')).toBeVisible()
    await page.getByLabel('Login code').fill('00000')
    await page.getByRole('button', { name: 'Verify code' }).click()
    await expect(page.getByRole('alert')).toBeVisible()
    await page.getByLabel('Login code').fill('11111')
    await page.getByRole('button', { name: 'Verify code' }).click()
    await expect(page.getByLabel('Two-step verification', { exact: true })).toBeVisible()
    await page
      .getByLabel('Two-step verification', { exact: true })
      .fill('  exact synthetic password  ')
    await page.getByRole('button', { name: 'Verify password' }).click()
    await expect(page.getByRole('heading', { name: 'Account authenticated' })).toBeVisible()
    await page.getByRole('link', { name: 'Webhook', exact: true }).click()
    await page.getByLabel('Destination URL').fill('https://example.test/other-hook')
    await page.getByLabel('Signing secret', { exact: true }).selectOption('replace')
    await page.getByLabel('Replace secret', { exact: true }).fill('synthetic-webhook-key')
    await page.getByText('Delivery filters', { exact: true }).click()
    await page.getByLabel('Include peers', { exact: true }).fill('group:456')
    await page.getByLabel('Exclude sender IDs', { exact: true }).fill('789')
    await page.getByLabel('Groups', { exact: true }).check()
    await page.getByLabel('Incoming', { exact: true }).check()
    await page.getByRole('button', { name: 'Save changes' }).click()
    await expect(page.getByText('https://example.test/other-hook', { exact: true })).toBeVisible()
    await page.reload()
    await page.getByText('Delivery filters', { exact: true }).click()
    await expect(page.getByLabel('Include peers', { exact: true })).toHaveValue('group:456')
    await expect(page.getByLabel('Exclude sender IDs', { exact: true })).toHaveValue('789')
    await expect(page.getByLabel('Incoming', { exact: true })).toBeChecked()
    await page.getByLabel('Include peers', { exact: true }).fill('')
    await page.getByLabel('Exclude sender IDs', { exact: true }).fill('')
    await page.getByLabel('Groups', { exact: true }).uncheck()
    await page.getByLabel('Incoming', { exact: true }).uncheck()
    await page.getByRole('button', { name: 'Save changes' }).click()
    await expect(page.getByText('No additional delivery filters', { exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Accounts', exact: true }).click()
    await page.getByRole('link', { name: 'Manage online-demo' }).click()
    await expect(page.getByRole('heading', { name: 'online-demo', exact: true })).toBeVisible()
    await expect(page.getByText('Recovery gap', { exact: true })).toBeVisible()
    await page.getByRole('link', { name: 'Deliveries', exact: true }).last().click()
    await page.getByLabel('All states', { exact: true }).selectOption('paused')
    await page.getByRole('button', { name: 'Details', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeVisible()
    await expect(page.getByRole('button', { name: 'Retry delivery', exact: true })).toHaveCount(0)
    await expect(page.getByRole('button', { name: 'Replay event', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Close', exact: true }).click()
    await page.getByRole('button', { name: 'Sign out', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Welcome back' })).toBeVisible()
  })
})
